project_id = "otpczgpmpnabbvzthvjv"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.paystack-config]
verify_jwt = false
