project_id = "jznmcpddqxyuvjjweydw"

[functions.seed-jamb-questions]
verify_jwt = false

[functions.seed-science-syllabus]
verify_jwt = false

[functions.seed-art-syllabus]
verify_jwt = false

[functions.seed-commercial-syllabus]
verify_jwt = false

[functions.seed-irs-syllabus]
verify_jwt = false

[functions.generate-topic-content]
verify_jwt = false

[functions.seed-more-questions]
verify_jwt = false
