import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

type Q = { question: string; option_a: string; option_b: string; option_c: string; option_d: string; correct_answer: string; explanation: string; year: number };

const QUESTIONS: Record<string, Q[]> = {
  economics: [
    { question: "Demand refers to:", option_a: "the quantity of goods available", option_b: "the quantity consumers are willing and able to buy at various prices", option_c: "the total production of a firm", option_d: "the cost of producing goods", correct_answer: "B", explanation: "Demand is the quantity of a good that consumers are willing and able to purchase at different price levels.", year: 2025 },
    { question: "The law of demand states that:", option_a: "as price rises, quantity demanded rises", option_b: "as price rises, quantity demanded falls", option_c: "demand is constant regardless of price", option_d: "supply determines price", correct_answer: "B", explanation: "The law of demand shows an inverse relationship between price and quantity demanded.", year: 2025 },
    { question: "Opportunity cost is:", option_a: "the total cost of production", option_b: "the value of the next best alternative foregone", option_c: "the price of a raw material", option_d: "fixed cost plus variable cost", correct_answer: "B", explanation: "Opportunity cost is the benefit given up when choosing one alternative over another.", year: 2025 },
    { question: "Inflation is defined as:", option_a: "a decrease in the money supply", option_b: "a sustained increase in the general price level", option_c: "an increase in unemployment", option_d: "a decrease in GDP", correct_answer: "B", explanation: "Inflation is a persistent rise in the general level of prices in an economy.", year: 2025 },
    { question: "A regressive tax is one where:", option_a: "the tax rate increases with income", option_b: "the tax rate decreases as income increases", option_c: "everyone pays the same amount", option_d: "only corporations are taxed", correct_answer: "B", explanation: "Regressive taxes take a larger percentage of income from low-income earners than high-income earners.", year: 2025 },
    { question: "GDP per capita is calculated by:", option_a: "dividing total GDP by total population", option_b: "multiplying GDP by population", option_c: "subtracting imports from exports", option_d: "adding government spending to savings", correct_answer: "A", explanation: "GDP per capita = Total GDP / Total population, measuring average economic output per person.", year: 2025 },
    { question: "Fiscal policy involves:", option_a: "central bank interest rate decisions", option_b: "government taxation and spending", option_c: "regulation of money supply", option_d: "control of exchange rates", correct_answer: "B", explanation: "Fiscal policy refers to government use of taxation and expenditure to influence the economy.", year: 2025 },
    { question: "Monetary policy is controlled by:", option_a: "the Ministry of Finance", option_b: "the central bank", option_c: "the national assembly", option_d: "commercial banks", correct_answer: "B", explanation: "Monetary policy is managed by the central bank through interest rates and money supply control.", year: 2025 },
    { question: "Scarcity in economics means:", option_a: "goods are free", option_b: "resources are limited relative to unlimited wants", option_c: "there is no demand for goods", option_d: "all goods are expensive", correct_answer: "B", explanation: "Scarcity is the fundamental economic problem of having unlimited wants with limited resources.", year: 2025 },
    { question: "A market economy is one where:", option_a: "the government controls all production", option_b: "decisions are made by supply and demand", option_c: "there is no private ownership", option_d: "prices are fixed by law", correct_answer: "B", explanation: "In a market economy, resource allocation is determined by the interaction of supply and demand.", year: 2025 },
    { question: "Marginal utility refers to:", option_a: "total satisfaction from all goods", option_b: "additional satisfaction from consuming one more unit", option_c: "the cost of the last unit produced", option_d: "average satisfaction per unit", correct_answer: "B", explanation: "Marginal utility is the extra satisfaction gained from consuming one additional unit of a good.", year: 2025 },
    { question: "The multiplier effect means:", option_a: "money supply decreases", option_b: "an initial injection of spending leads to a larger final increase in national income", option_c: "taxes reduce income", option_d: "imports increase GDP", correct_answer: "B", explanation: "The multiplier effect shows how an initial change in spending creates a chain reaction of increased economic activity.", year: 2025 },
    { question: "An inferior good is one whose demand:", option_a: "increases as income increases", option_b: "decreases as income increases", option_c: "stays constant regardless of income", option_d: "depends only on price", correct_answer: "B", explanation: "Inferior goods have lower demand as consumer income rises, as people switch to better alternatives.", year: 2025 },
    { question: "Balance of payments records:", option_a: "only exports of goods", option_b: "all economic transactions between a country and the rest of the world", option_c: "government budget deficits", option_d: "only foreign investment", correct_answer: "B", explanation: "The balance of payments is a comprehensive record of all economic transactions between residents and the rest of the world.", year: 2025 },
    { question: "Devaluation of currency means:", option_a: "increasing the value of money", option_b: "deliberate reduction of a currency's value relative to others", option_c: "printing more money", option_d: "raising interest rates", correct_answer: "B", explanation: "Devaluation is an official downward adjustment of a country's currency value against foreign currencies.", year: 2025 },
    { question: "Public debt is:", option_a: "money owed by individuals", option_b: "the total amount the government owes to domestic and foreign lenders", option_c: "corporate bonds", option_d: "private savings", correct_answer: "B", explanation: "Public debt (national debt) is the total outstanding borrowing by the government.", year: 2025 },
    { question: "Subsidies are payments made by:", option_a: "consumers to producers", option_b: "the government to producers to reduce costs", option_c: "banks to borrowers", option_d: "importers to exporters", correct_answer: "B", explanation: "Subsidies are financial aid from the government to support businesses and keep prices low.", year: 2025 },
    { question: "Price elasticity of demand measures:", option_a: "total revenue changes", option_b: "the responsiveness of quantity demanded to a change in price", option_c: "supply shifts", option_d: "production costs", correct_answer: "B", explanation: "PED shows how much quantity demanded changes when price changes, calculated as %ΔQd / %ΔP.", year: 2025 },
    { question: "A trade deficit occurs when:", option_a: "exports exceed imports", option_b: "imports exceed exports", option_c: "exports equal imports", option_d: "there is no trade", correct_answer: "B", explanation: "A trade deficit means a country buys more from abroad than it sells, resulting in negative net exports.", year: 2025 },
    { question: "Gini coefficient measures:", option_a: "inflation rate", option_b: "income inequality", option_c: "GDP growth", option_d: "unemployment rate", correct_answer: "B", explanation: "The Gini coefficient ranges from 0 (perfect equality) to 1 (perfect inequality), measuring income distribution.", year: 2025 },
    { question: "A commodity is:", option_a: "a unique product", option_b: "a raw material or primary agricultural product that is interchangeable with others", option_c: "a service", option_d: "a type of currency", correct_answer: "B", explanation: "Commodities are basic goods like oil, gold, wheat that are interchangeable with other goods of the same type.", year: 2025 },
    { question: "Human capital refers to:", option_a: "physical machinery", option_b: "the skills, knowledge, and experience of workers", option_c: "government buildings", option_d: "natural resources", correct_answer: "B", explanation: "Human capital is the economic value of workers' abilities, education, and experience.", year: 2025 },
    { question: "Supply-side economics focuses on:", option_a: "increasing consumer demand", option_b: "increasing production and supply through tax cuts and deregulation", option_c: "government spending programs", option_d: "controlling inflation", correct_answer: "B", explanation: "Supply-side economics argues that economic growth comes from lowering barriers to production.", year: 2025 },
    { question: "A progressive tax system is one where:", option_a: "everyone pays the same rate", option_b: "the tax rate increases as taxable amount increases", option_c: "the tax rate decreases as income increases", option_d: "only businesses are taxed", correct_answer: "B", explanation: "Progressive taxation imposes higher tax rates on higher income brackets.", year: 2025 },
    { question: "Ceteris paribus means:", option_a: "all things change", option_b: "all other things being equal", option_c: "nothing is constant", option_d: "everything is free", correct_answer: "B", explanation: "Ceteris paribus is a Latin phrase meaning 'all other things being equal,' used in economic analysis.", year: 2025 },
    { question: "Economies of scale occur when:", option_a: "costs increase as output increases", option_b: "average cost per unit decreases as output increases", option_c: "the firm becomes smaller", option_d: "demand decreases", correct_answer: "B", explanation: "Economies of scale reduce average costs as a firm produces more, through bulk buying and specialization.", year: 2025 },
    { question: "The Phillips curve shows the relationship between:", option_a: "GDP and population", option_b: "inflation and unemployment", option_c: "savings and investment", option_d: "exports and imports", correct_answer: "B", explanation: "The Phillips curve suggests an inverse relationship between inflation and unemployment in the short run.", year: 2025 },
    { question: "A closed economy is one that:", option_a: "trades freely with other countries", option_b: "does not engage in international trade", option_c: "has no government", option_d: "has no currency", correct_answer: "B", explanation: "A closed economy is self-sufficient and does not import or export goods and services.", year: 2025 },
    { question: "Externalities are:", option_a: "costs or benefits affecting third parties not involved in a transaction", option_b: "only positive effects", option_c: "government taxes", option_d: "internal company costs", correct_answer: "A", explanation: "Externalities are side effects (positive or negative) of production or consumption on bystanders.", year: 2025 },
    { question: "The Laffer curve illustrates:", option_a: "the relationship between supply and demand", option_b: "the relationship between tax rates and tax revenue", option_c: "inflation and money supply", option_d: "unemployment and GDP", correct_answer: "B", explanation: "The Laffer curve shows that beyond a certain point, higher tax rates reduce total tax revenue.", year: 2025 },
    { question: "Demand-pull inflation is caused by:", option_a: "increase in production costs", option_b: "excess demand over supply", option_c: "decrease in money supply", option_d: "fall in consumer spending", correct_answer: "B", explanation: "Demand-pull inflation occurs when aggregate demand exceeds aggregate supply.", year: 2025 },
    { question: "Which is NOT a function of money?", option_a: "medium of exchange", option_b: "store of value", option_c: "generator of profit", option_d: "unit of account", correct_answer: "C", explanation: "Money serves as a medium of exchange, store of value, and unit of account, but not as a profit generator.", year: 2025 },
    { question: "A monopoly is undesirable because it:", option_a: "creates too much competition", option_b: "leads to higher prices and lower output due to lack of competition", option_c: "produces too many goods", option_d: "employs too many workers", correct_answer: "B", explanation: "Monopolies can restrict output and raise prices since consumers have no alternative suppliers.", year: 2025 },
    { question: "Depreciation of naira means:", option_a: "naira becomes stronger against dollar", option_b: "naira buys fewer dollars than before", option_c: "dollar value decreases", option_d: "inflation falls", correct_answer: "B", explanation: "When naira depreciates, it loses value relative to foreign currencies like the dollar.", year: 2025 },
    { question: "Commercial banks create money by:", option_a: "printing banknotes", option_b: "lending out a portion of deposits received", option_c: "borrowing from the central bank", option_d: "collecting taxes", correct_answer: "B", explanation: "Banks create money through fractional reserve lending — lending more than they hold in reserves.", year: 2025 },
    { question: "The IS-LM model shows:", option_a: "the relationship between product and money markets", option_b: "supply and demand for goods only", option_c: "trade balance effects", option_d: "exchange rate determination", correct_answer: "A", explanation: "The IS-LM model shows how interest rates and output are determined in the goods and money markets simultaneously.", year: 2025 },
    { question: "Stagflation is a situation of:", option_a: "high growth and low inflation", option_b: "high inflation combined with high unemployment and stagnant growth", option_c: "low inflation and high employment", option_d: "rapid economic growth", correct_answer: "B", explanation: "Stagflation combines stagnant economic growth, high unemployment, and high inflation.", year: 2025 },
    { question: "An economic growth is best measured by:", option_a: "increase in population", option_b: "sustained increase in real GDP over time", option_c: "increase in money supply", option_d: "fall in unemployment", correct_answer: "B", explanation: "Economic growth is measured by the percentage increase in real GDP (adjusted for inflation) over time.", year: 2025 },
    { question: "The circular flow of income shows:", option_a: "how money flows from banks to consumers", option_b: "the flow of income and expenditure between households and firms", option_c: "how taxes are collected", option_d: "international trade flows", correct_answer: "B", explanation: "The circular flow model shows how money, goods, and services move between households and firms in an economy.", year: 2025 },
    { question: "Indirect tax is levied on:", option_a: "income of individuals", option_b: "goods and services rather than directly on income", option_c: "profits of companies", option_d: "savings accounts", correct_answer: "B", explanation: "Indirect taxes (like VAT) are charged on goods and services and passed on to consumers through prices.", year: 2025 },
    { question: "OECD stands for:", option_a: "Organization for Economic Cooperation and Development", option_b: "Office of Economic and Commercial Development", option_c: "Organisation of Export and Commercial Development", option_d: "Official Economic Council for Development", correct_answer: "A", explanation: "The OECD is an intergovernmental organization with 38 member countries promoting economic cooperation.", year: 2025 },
    { question: "In a perfectly competitive market:", option_a: "firms are price makers", option_b: "firms are price takers", option_c: "there are few sellers", option_d: "products are differentiated", correct_answer: "B", explanation: "In perfect competition, firms must accept the market price since no single firm can influence it.", year: 2025 },
    { question: "Which factor shifts the demand curve to the right?", option_a: "decrease in consumer income", option_b: "increase in consumer income (for normal goods)", option_c: "increase in price of the good", option_d: "decrease in population", correct_answer: "B", explanation: "For normal goods, higher income means consumers buy more at every price level, shifting demand right.", year: 2025 },
    { question: "The Bretton Woods system was about:", option_a: "oil pricing", option_b: "international monetary and exchange rate system", option_c: "agricultural trade", option_d: "labor migration", correct_answer: "B", explanation: "The Bretton Woods system (1944) established rules for international monetary relations and fixed exchange rates.", year: 2025 },
    { question: "Efficiency in economics means:", option_a: "producing at the lowest possible cost", option_b: "resources are allocated to maximize output with minimum waste", option_c: "maximum employment", option_d: "highest possible taxes", correct_answer: "B", explanation: "Economic efficiency means resources are used to maximize the production of goods and services with minimal waste.", year: 2025 },
    { question: "Terms of trade measure:", option_a: "domestic price levels", option_b: "the ratio of export prices to import prices", option_c: "government revenue", option_d: "total trade volume", correct_answer: "B", explanation: "Terms of trade = (Export price index / Import price index) × 100, showing a country's trading advantage.", year: 2025 },
    { question: "Economic development differs from economic growth in that it:", option_a: "only measures GDP increase", option_b: "includes improvements in quality of life, health, and education", option_c: "only applies to rich countries", option_d: "measures only industrial output", correct_answer: "B", explanation: "Development goes beyond GDP to include improvements in living standards, human development, and social welfare.", year: 2025 },
    { question: "A budget deficit occurs when:", option_a: "government revenue exceeds expenditure", option_b: "government expenditure exceeds revenue", option_c: "exports exceed imports", option_d: "savings exceed investment", correct_answer: "B", explanation: "A budget deficit happens when the government spends more than it collects in revenue.", year: 2025 },
    { question: "Quantitative easing is:", option_a: "raising interest rates", option_b: "a central bank buying government bonds to increase money supply", option_c: "cutting government spending", option_d: "increasing tax rates", correct_answer: "B", explanation: "QE is an unconventional monetary policy where central banks purchase securities to inject money into the economy.", year: 2025 },
    { question: "The invisible hand concept was introduced by:", option_a: "John Maynard Keynes", option_b: "Adam Smith", option_c: "Karl Marx", option_d: "Milton Friedman", correct_answer: "B", explanation: "Adam Smith used the 'invisible hand' metaphor in 'The Wealth of Nations' to describe self-regulating markets.", year: 2025 },
  ],

  government: [
    { question: "Sovereignty in government means:", option_a: "the power to make laws only", option_b: "supreme authority within a territory", option_c: "military control", option_d: "judicial power", correct_answer: "B", explanation: "Sovereignty is the supreme power or authority of a state to govern itself without external interference.", year: 2025 },
    { question: "A federal system of government is one where:", option_a: "all power is centralized", option_b: "power is divided between a central authority and constituent units", option_c: "only local governments exist", option_d: "there is no constitution", correct_answer: "B", explanation: "Federalism divides power between a central government and regional governments (states, provinces).", year: 2025 },
    { question: "Separation of powers means:", option_a: "all powers belong to the president", option_b: "government powers are divided among different branches", option_c: "power is shared equally by all citizens", option_d: "there is only one branch of government", correct_answer: "B", explanation: "Separation of powers divides government into legislative, executive, and judicial branches.", year: 2025 },
    { question: "A constitution is:", option_a: "a set of rules for playing sports", option_b: "the supreme law that defines how a government operates", option_c: "a type of government policy", option_d: "an executive order", correct_answer: "B", explanation: "A constitution is the fundamental law that establishes the structure and powers of government.", year: 2025 },
    { question: "Democracy literally means:", option_a: "rule by the rich", option_b: "rule by the people", option_c: "rule by the military", option_d: "rule by the elite", correct_answer: "B", explanation: "Democracy comes from Greek 'demos' (people) and 'kratos' (rule), meaning government by the people.", year: 2025 },
    { question: "An autocracy is a system where:", option_a: "power is shared", option_b: "one person holds unlimited power", option_c: "the people elect leaders", option_d: "power is decentralized", correct_answer: "B", explanation: "An autocracy is a system of government where one person has absolute power.", year: 2025 },
    { question: "The principle of checks and balances:", option_a: "gives one branch unlimited power", option_b: "allows each branch of government to limit the powers of others", option_c: "eliminates all branches of government", option_d: "gives all power to the legislature", correct_answer: "B", explanation: "Checks and balances prevent any single branch from becoming too powerful by allowing oversight of others.", year: 2025 },
    { question: "A bicameral legislature has:", option_a: "one chamber", option_b: "two chambers or houses", option_c: "three chambers", option_d: "no chambers", correct_answer: "B", explanation: "A bicameral legislature has two chambers (e.g., Senate and House of Representatives in the US).", year: 2025 },
    { question: "Civil liberties include:", option_a: "the right to free education", option_b: "freedom of speech, religion, and assembly", option_c: "the right to free healthcare", option_d: "the right to own a business", correct_answer: "B", explanation: "Civil liberties are fundamental individual freedoms protected from government interference.", year: 2025 },
    { question: "A referendum is:", option_a: "a vote in parliament", option_b: "a direct vote by the people on a specific issue", option_c: "a type of election", option_d: "a court ruling", correct_answer: "B", explanation: "A referendum is a direct vote by all eligible voters on a particular proposal or issue.", year: 2025 },
    { question: "The rule of law means:", option_a: "the king makes all rules", option_b: "everyone is subject to and accountable under the law", option_c: "only the rich follow the law", option_d: "laws change daily", correct_answer: "B", explanation: "The rule of law ensures no one is above the law — everyone must follow and be accountable to it.", year: 2025 },
    { question: "Anocracy is:", option_a: "a pure democracy", option_b: "a hybrid regime with both democratic and autocratic features", option_c: "a dictatorship", option_d: "a monarchy", correct_answer: "B", explanation: "Anocracy is a regime that combines elements of democracy and autocracy, often unstable.", year: 2025 },
    { question: "Political socialization refers to:", option_a: "campaigning for elections", option_b: "the process by which individuals acquire political beliefs and values", option_c: "forming a political party", option_d: "voting in elections", correct_answer: "B", explanation: "Political socialization is how people learn and form their political attitudes through family, media, and education.", year: 2025 },
    { question: "A lobby group is:", option_a: "a political party", option_b: "an organization that tries to influence government decisions", option_c: "a court of law", option_d: "a government ministry", correct_answer: "B", explanation: "Lobby groups advocate for specific interests and try to influence policy-makers.", year: 2025 },
    { question: "Delegated legislation is:", option_a: "laws made directly by parliament", option_b: "rules and regulations made by ministers under authority from an act of parliament", option_c: "international treaties", option_d: "court judgments", correct_answer: "B", explanation: "Delegated legislation gives ministers and agencies power to create detailed regulations under primary legislation.", year: 2025 },
    { question: "A unitary state is one where:", option_a: "power is shared equally", option_b: "central government holds supreme power and can delegate to local units", option_c: "states have equal power with the center", option_d: "there is no central government", correct_answer: "B", explanation: "In a unitary state, the central government holds all power and may create local governments at its discretion.", year: 2025 },
    { question: "An electoral college is:", option_a: "a group of voters at polling stations", option_b: "a body of electors who formally elect the president", option_c: "a type of school", option_d: "a committee for counting votes", correct_answer: "B", explanation: "An electoral college is a body of electors who formally cast votes to elect a president (e.g., in the US).", year: 2025 },
    { question: "Ratification of a treaty means:", option_a: "signing the treaty", option_b: "formally approving and confirming the treaty", option_c: "rejecting the treaty", option_d: "drafting the treaty", correct_answer: "B", explanation: "Ratification is the formal process by which a state confirms its agreement to be bound by a treaty.", year: 2025 },
    { question: "Bureaucracy refers to:", option_a: "the military", option_b: "the system of government departments and their administrative procedures", option_c: "the judiciary", option_d: "the legislature", correct_answer: "B", explanation: "Bureaucracy is the administrative system of government departments staffed by non-elected officials.", year: 2025 },
    { question: "A hung parliament occurs when:", option_a: "one party wins a large majority", option_b: "no party has enough seats to form a majority government", option_c: "parliament is dissolved", option_d: "all seats are vacant", correct_answer: "B", explanation: "A hung parliament happens when no single party or coalition wins enough seats to control the legislature.", year: 2025 },
    { question: "Judicial review allows courts to:", option_a: "make new laws", option_b: "examine the constitutionality of government actions", option_c: "elect the president", option_d: "collect taxes", correct_answer: "B", explanation: "Judicial review enables courts to assess whether government actions comply with the constitution.", year: 2025 },
    { question: "A coalition government is formed when:", option_a: "one party wins all seats", option_b: "two or more parties join to form a majority", option_c: "the president dismisses parliament", option_d: "elections are cancelled", correct_answer: "B", explanation: "A coalition government occurs when multiple parties cooperate to hold a parliamentary majority.", year: 2025 },
    { question: "Federalism in Nigeria operates at:", option_a: "one level", option_b: "three tiers — federal, state, and local", option_c: "two levels only", option_d: "village level only", correct_answer: "B", explanation: "Nigeria operates a three-tier federal system: federal government, 36 state governments, and 774 local governments.", year: 2025 },
    { question: "The doctrine of necessity is:", option_a: "a legal principle that justifies extra-constitutional actions in emergencies", option_b: "a requirement to hold elections", option_c: "a military protocol", option_d: "an economic policy", correct_answer: "A", explanation: "The doctrine of necessity is used to justify actions that would otherwise be illegal when faced with an emergency.", year: 2025 },
    { question: "Gerrymandering is:", option_a: "fair election practices", option_b: "manipulating electoral district boundaries to favor a party", option_c: "banning political parties", option_d: "counting votes fairly", correct_answer: "B", explanation: "Gerrymandering is the practice of drawing electoral boundaries to give one party an unfair advantage.", year: 2025 },
    { question: "A monarchy is a system where:", option_a: "the people elect leaders", option_b: "a king or queen is the head of state", option_c: "the military rules", option_d: "there is no head of state", correct_answer: "B", explanation: "A monarchy is a form of government where a monarch (king/queen) serves as the head of state.", year: 2025 },
    { question: "Public opinion refers to:", option_a: "the views of government officials", option_b: "the collective attitudes and preferences of the general population", option_c: "a single voter's choice", option_d: "media editorial positions", correct_answer: "B", explanation: "Public opinion is the aggregate of individual views and attitudes of citizens on political matters.", year: 2025 },
    { question: "Suffrage means:", option_a: "the right to speak publicly", option_b: "the right to vote in elections", option_c: "the right to hold office", option_d: "the right to petition", correct_answer: "B", explanation: "Suffrage is the right to vote in political elections, also known as franchise.", year: 2025 },
    { question: "A constitutional monarchy is one where:", option_a: "the monarch has absolute power", option_b: "the monarch's powers are limited by the constitution", option_c: "there is no monarch", option_d: "the monarch makes all laws", correct_answer: "B", explanation: "In a constitutional monarchy, the monarch serves as head of state within the limits of a constitution.", year: 2025 },
    { question: "The principle of federal character in Nigeria ensures:", option_a: "only one region dominates government", option_b: "fair representation of all regions in government appointments", option_c: "equal population in all states", option_d: "same revenue for all states", correct_answer: "B", explanation: "The federal character principle ensures balanced representation of all ethnic groups in government.", year: 2025 },
    { question: "Impeachment is:", option_a: "removing a judge from office by the public", option_b: "the process of formally charging a public official for misconduct", option_c: "electing a new president", option_d: "dissolving parliament", correct_answer: "B", explanation: "Impeachment is a formal process to charge and potentially remove a public official for serious offenses.", year: 2025 },
    { question: "A parliamentary system is one where:", option_a: "the president is both head of state and head of government", option_b: "the executive is drawn from and accountable to the legislature", option_c: "the president rules alone", option_d: "there is no parliament", correct_answer: "B", explanation: "In a parliamentary system, the prime minister and cabinet are members of parliament and answerable to it.", year: 2025 },
    { question: "Political apathy means:", option_a: "enthusiasm for politics", option_b: "lack of interest or engagement in political activities", option_c: "active participation in elections", option_d: "supporting all parties", correct_answer: "B", explanation: "Political apathy is the lack of interest, concern, or motivation to participate in political activities.", year: 2025 },
    { question: "An executive order is:", option_a: "a law passed by parliament", option_b: "a directive issued by the president that has the force of law", option_c: "a court ruling", option_d: "a treaty", correct_answer: "B", explanation: "An executive order is a directive from the president that manages operations of the federal government.", year: 2025 },
    { question: "Sovereignty in international law means:", option_a: "the right to invade other countries", option_b: "the independence and self-governing authority of a state", option_c: "membership in the UN", option_d: "military strength", correct_answer: "B", explanation: "Sovereignty in international law is the principle that each state has supreme authority within its territory.", year: 2025 },
    { question: "The electorate is:", option_a: "all people in a country", option_b: "the body of people eligible to vote", option_c: "elected officials", option_d: "political party members", correct_answer: "B", explanation: "The electorate refers to all citizens who are qualified to vote in elections.", year: 2025 },
    { question: "A plebiscite differs from a referendum in that:", option_a: "it is binding", option_b: "it is usually advisory and not legally binding", option_c: "only parliament votes", option_d: "it is held internationally", correct_answer: "B", explanation: "A plebiscite is typically a non-binding vote to gauge public opinion, while a referendum may be legally binding.", year: 2025 },
    { question: "Civic responsibility includes:", option_a: "ignoring government policies", option_b: "paying taxes, voting, and obeying laws", option_c: "joining the military only", option_d: "running for office only", correct_answer: "B", explanation: "Civic responsibility means citizens have duties to their community, including voting, paying taxes, and obeying laws.", year: 2025 },
    { question: "A shadow cabinet is:", option_a: "a secret government", option_b: "a group of opposition members who shadow and critique government ministers", option_c: "an illegal government", option_d: "the judiciary", correct_answer: "B", explanation: "A shadow cabinet consists of opposition party members assigned to scrutinize each government department.", year: 2025 },
    { question: "Deterrence in national security means:", option_a: "attacking first", option_b: "discouraging aggression through threat of retaliation", option_c: "surrendering immediately", option_d: "forming alliances only", correct_answer: "B", explanation: "Deterrence aims to prevent hostile actions by convincing potential adversaries that the cost would be too high.", year: 2025 },
    { question: "The independence of the judiciary means:", option_a: "judges can make laws", option_b: "courts are free from interference by the executive and legislature", option_c: "judges are elected by the public", option_d: "courts have no power", correct_answer: "B", explanation: "Judicial independence ensures judges decide cases based on law, not political pressure.", year: 2025 },
    { question: "Political ideology refers to:", option_a: "a set of religious beliefs", option_b: "a coherent set of political ideas and values that guide policy preferences", option_c: "personal friendships", option_d: "economic data only", correct_answer: "B", explanation: "Political ideology is a system of ideas that provides a basis for organized political action.", year: 2025 },
    { question: "A politburo is:", option_a: "a democratic parliament", option_b: "a political committee that exercises executive power, typically in communist systems", option_c: "a court system", option_d: "an electoral commission", correct_answer: "B", explanation: "A politburo is the chief executive and policy-making committee in communist and some authoritarian states.", year: 2025 },
    { question: "Decentralization of power means:", option_a: "concentrating all power at the center", option_b: "distributing government authority to lower levels", option_c: "abolishing local government", option_d: "military rule", correct_answer: "B", explanation: "Decentralization transfers decision-making authority from central to local or regional governments.", year: 2025 },
    { question: "A candidate in an election must:", option_a: "be from any country", option_b: "meet eligibility requirements such as age and citizenship", option_c: "be a member of the military", option_d: "have no education", correct_answer: "B", explanation: "Election candidates must meet specific criteria like minimum age, citizenship, and residency requirements.", year: 2025 },
    { question: "Propaganda in politics refers to:", option_a: "neutral news reporting", option_b: "biased or misleading information used to promote a political cause", option_c: "academic research", option_d: "independent journalism", correct_answer: "B", explanation: "Political propaganda is communication designed to influence public opinion, often through selective or misleading information.", year: 2025 },
    { question: "An ex-officio member of a body is one who:", option_a: "is elected by the public", option_b: "is a member by virtue of holding another office", option_c: "is appointed for life", option_d: "is a guest", correct_answer: "B", explanation: "An ex-officio member serves on a body automatically because of another position they hold.", year: 2025 },
    { question: "Public administration involves:", option_a: "private business management", option_b: "the implementation of government policies and programs", option_c: "military operations only", option_d: "political campaigning", correct_answer: "B", explanation: "Public administration is the machinery through which government policies are implemented.", year: 2025 },
    { question: "The electoral process includes:", option_a: "only voting on election day", option_b: "registration, campaigning, voting, and results declaration", option_c: "only appointing judges", option_d: "only political party formation", correct_answer: "B", explanation: "The electoral process encompasses all steps from voter registration through campaigning to vote counting.", year: 2025 },
    { question: "A bill becomes a law when:", option_a: "it is introduced in parliament", option_b: "it is passed by the legislature and assented to by the head of state", option_c: "the prime minister approves it", option_d: "the media supports it", correct_answer: "B", explanation: "A bill becomes law after being passed by the required legislative majority and receiving presidential assent.", year: 2025 },
    { question: "A motion of no confidence is used to:", option_a: "elect a new president", option_b: "remove the government or prime minister from office", option_c: "pass a budget", option_d: "adjourn parliament", correct_answer: "B", explanation: "A motion of no confidence, if passed, indicates the government has lost the legislature's support.", year: 2025 },
    { question: "Nationalism is:", option_a: "opposition to one's own country", option_b: "devotion to and promotion of one's nation's interests", option_c: "international cooperation", option_d: "isolationism", correct_answer: "B", explanation: "Nationalism is loyalty and devotion to one's nation, often emphasizing its interests above others.", year: 2025 },
  ],

  literature: [
    { question: "A tragic hero is a character who:", option_a: "is always happy", option_b: "has a fatal flaw that leads to their downfall", option_c: "never makes mistakes", option_d: "is a villain", correct_answer: "B", explanation: "A tragic hero is a noble character with a hamartia (fatal flaw) that leads to their tragic end.", year: 2025 },
    { question: "The narrative voice in first person is:", option_a: "told by an omniscient narrator", option_b: "told using 'I' by a character in the story", option_c: "told using 'he/she'", option_d: "told using 'you'", correct_answer: "B", explanation: "First person narration uses 'I' and is limited to what the narrator knows and experiences.", year: 2025 },
    { question: "Satire in literature is used to:", option_a: "praise everything", option_b: "criticize vices and follies through humor and irony", option_c: "tell fairy tales", option_d: "describe nature", correct_answer: "B", explanation: "Satire uses humor, irony, and exaggeration to expose and criticize human vices and societal problems.", year: 2025 },
    { question: "The antagonist in a story is:", option_a: "the hero", option_b: "the character who opposes the protagonist", option_c: "the narrator", option_d: "the setting", correct_answer: "B", explanation: "The antagonist is the character or force that creates conflict by opposing the protagonist.", year: 2025 },
    { question: "An allegory is:", option_a: "a short poem", option_b: "a story with a hidden moral or political meaning", option_c: "a type of essay", option_d: "a biography", correct_answer: "B", explanation: "An allegory is a narrative where characters and events symbolize deeper moral or political meanings.", year: 2025 },
    { question: "Foreshadowing in a story:", option_a: "repeats events", option_b: "gives hints about what will happen later", option_c: "ends the story", option_d: "introduces characters", correct_answer: "B", explanation: "Foreshadowing is a literary device that provides clues about events that will occur later in the story.", year: 2025 },
    { question: "A ballad is:", option_a: "a prose essay", option_b: "a poem that tells a story, often set to music", option_c: "a dramatic monologue", option_d: "a novel", correct_answer: "B", explanation: "A ballad is a narrative poem, usually in quatrains, that tells a story and was originally meant to be sung.", year: 2025 },
    { question: "Wole Soyinka's 'Death and the King's Horseman' is set in:", option_a: "modern Lagos", option_b: "colonial-era Yoruba land", option_c: "London", option_d: "Northern Nigeria", correct_answer: "B", explanation: "The play is set in a Yoruba town during British colonial rule, dealing with the conflict between traditional and colonial values.", year: 2025 },
    { question: "The protagonist of 'Things Fall Apart' is:", option_a: "Obi Okonkwo", option_b: "Okonkwo", option_c: "Nwoye", option_d: "Ikemefuna", correct_answer: "B", explanation: "Okonkwo is the central character whose pride and fear of weakness drive the novel's tragedy.", year: 2025 },
    { question: "Free verse poetry is characterized by:", option_a: "strict rhyme scheme", option_b: "no regular meter or rhyme pattern", option_c: "exactly 14 lines", option_d: "three stanzas only", correct_answer: "B", explanation: "Free verse poetry does not follow a regular rhyme scheme or meter, giving the poet greater freedom.", year: 2025 },
    { question: "An unreliable narrator is one who:", option_a: "tells the truth always", option_b: "whose account cannot be fully trusted due to bias or limited knowledge", option_c: "is the main character", option_d: "never speaks", correct_answer: "B", explanation: "An unreliable narrator's credibility is compromised, requiring readers to question their account.", year: 2025 },
    { question: "In 'Second Class Citizen', Adah struggles primarily against:", option_a: "foreign invaders", option_b: "gender inequality and racial discrimination", option_c: "natural disasters", option_d: "religious persecution", correct_answer: "B", explanation: "Adah faces dual oppression as a woman and as a Black immigrant in England.", year: 2025 },
    { question: "The chorus in Greek tragedy:", option_a: "performs the main action", option_b: "comments on the action and represents public opinion", option_c: "is the protagonist", option_d: "introduces the play", correct_answer: "B", explanation: "The Greek chorus provides commentary, reflects public sentiment, and enhances the thematic depth.", year: 2025 },
    { question: "An epistolary novel is one written:", option_a: "as a series of poems", option_b: "in the form of letters or documents", option_c: "as a play script", option_d: "as a news report", correct_answer: "B", explanation: "An epistolary novel tells its story through documents, often letters, diary entries, or emails.", year: 2025 },
    { question: "The theme of 'The Lion and the Jewel' includes:", option_a: "war and peace", option_b: "tradition versus modernity", option_c: "religious conversion", option_d: "colonial resistance", correct_answer: "B", explanation: "Soyinka's play explores the tension between traditional Yoruba culture and Western modernization.", year: 2025 },
    { question: "Pathetic fallacy refers to:", option_a: "a character's lie", option_b: "attributing human emotions to nature or weather", option_c: "a type of dialogue", option_d: "a plot device", correct_answer: "B", explanation: "Pathetic fallacy uses weather and nature to reflect the mood or emotions of characters.", year: 2025 },
    { question: "Dramatic irony occurs when:", option_a: "the audience and character know the same things", option_b: "the audience knows something the character does not", option_c: "the character deceives the audience", option_d: "there is no conflict", correct_answer: "B", explanation: "Dramatic irony creates tension when the audience has knowledge that a character lacks.", year: 2025 },
    { question: "Chinua Achebe wrote in response to:", option_a: "African folk traditions only", option_b: "colonial literature that misrepresented Africa", option_c: "European poetry", option_d: "Islamic texts", correct_answer: "B", explanation: "Achebe wrote to correct the distorted portrayals of Africa in colonial literature like 'Heart of Darkness'.", year: 2025 },
    { question: "A couplet is:", option_a: "a group of four lines", option_b: "two consecutive lines of poetry that rhyme", option_c: "a single line of poetry", option_d: "three lines of poetry", correct_answer: "B", explanation: "A couplet consists of two successive lines of verse, usually with the same meter and rhyme.", year: 2025 },
    { question: "The setting of 'A Raisin in the Sun' is:", option_a: "Africa", option_b: "a cramped apartment in Chicago", option_c: "a plantation", option_d: "a university", correct_answer: "B", explanation: "Lorraine Hansberry's play is set in the South Side of Chicago, depicting a Black family's struggles.", year: 2025 },
    { question: "Symbolism in literature means:", option_a: "using big words", option_b: "using objects or ideas to represent deeper meanings", option_c: "writing in code", option_d: "using excessive descriptions", correct_answer: "B", explanation: "Symbolism uses tangible elements (objects, colors, settings) to represent abstract ideas or concepts.", year: 2025 },
    { question: "The genre of 'Native Son' by Richard Wright is:", option_a: "comedy", option_b: "social protest novel", option_c: "science fiction", option_d: "poetry", correct_answer: "B", explanation: "'Native Son' is a protest novel exposing the effects of systemic racism on Black Americans.", year: 2025 },
    { question: "An oxymoron is:", option_a: "a long speech", option_b: "a combination of contradictory terms", option_c: "a type of stanza", option_d: "a poetic meter", correct_answer: "B", explanation: "An oxymoron combines opposite words for effect (e.g., 'deafening silence', 'bittersweet').", year: 2025 },
    { question: "Protagonist vs. antagonist conflict is:", option_a: "man vs. nature", option_b: "character vs. character", option_c: "man vs. self", option_d: "man vs. society", correct_answer: "B", explanation: "The protagonist-antagonist conflict is an external conflict between two opposing characters.", year: 2025 },
    { question: "Stream of consciousness is a narrative technique that:", option_a: "follows a strict timeline", option_b: "presents the continuous flow of a character's thoughts", option_c: "uses only dialogue", option_d: "tells the story in reverse", correct_answer: "B", explanation: "Stream of consciousness presents the character's inner thoughts as a continuous, often unstructured flow.", year: 2025 },
    { question: "The novel 'Faceless' by Ayisi is about:", option_a: "a football match", option_b: "the life and struggles of homeless children on the streets of Accra", option_c: "a love story in Europe", option_d: "a political campaign", correct_answer: "B", explanation: "'Faceless' depicts the plight of street children ('Alayaman') in Accra, Ghana.", year: 2025 },
    { question: "A soliloquy differs from an aside in that:", option_a: "an aside is spoken to the audience", option_b: "a soliloquy is a longer speech where a character reveals thoughts when alone", option_c: "both are the same", option_d: "a soliloquy is spoken to another character", correct_answer: "B", explanation: "A soliloquy is a long speech revealing inner thoughts when alone; an aside is a brief remark to the audience.", year: 2025 },
    { question: "Naturalism in literature emphasizes:", option_a: "supernatural events", option_b: "how heredity and environment determine character", option_c: "romantic ideals", option_d: "religious themes", correct_answer: "B", explanation: "Naturalism portrays characters as products of their heredity and environment, often in bleak settings.", year: 2025 },
    { question: "In poetry, a stanza is:", option_a: "a single line", option_b: "a group of lines forming a unit within a poem", option_c: "the entire poem", option_d: "the title", correct_answer: "B", explanation: "A stanza is a structured group of lines in a poem, similar to a paragraph in prose.", year: 2025 },
    { question: "The protagonist of 'The Unexpected Joy of Answering' is:", option_a: "a male doctor", option_b: "a woman navigating identity and belonging in London", option_c: "a student in Nigeria", option_d: "a farmer", correct_answer: "B", explanation: "The novel follows a female protagonist's experiences as an immigrant in London.", year: 2025 },
    { question: "A flashback in literature:", option_a: "moves the story to the future", option_b: "interrupts the present narrative to show past events", option_c: "ends the story", option_d: "is a type of character", correct_answer: "B", explanation: "A flashback is a narrative technique that takes the reader back in time to show earlier events.", year: 2025 },
    { question: "Didactic literature is written primarily to:", option_a: "entertain", option_b: "teach a moral or lesson", option_c: "confuse readers", option_d: "describe nature", correct_answer: "B", explanation: "Didactic literature aims to instruct readers, often conveying moral, ethical, or practical lessons.", year: 2025 },
    { question: "The use of dialect in a novel:", option_a: "makes the text harder to understand deliberately", option_b: "adds authenticity and reflects characters' cultural backgrounds", option_c: "is always grammatically incorrect", option_d: "is used only in comedy", correct_answer: "B", explanation: "Dialect gives characters distinctive voices and grounds the narrative in a specific cultural context.", year: 2025 },
    { question: "A preface in a novel is:", option_a: "the last chapter", option_b: "an introductory section explaining the author's purpose or background", option_c: "a poem at the end", option_d: "a character list", correct_answer: "B", explanation: "A preface provides context about the work's creation, the author's intentions, or background information.", year: 2025 },
    { question: "The climax of a drama is:", option_a: "the opening scene", option_b: "the point of highest tension or turning point", option_c: "the final scene", option_d: "the exposition", correct_answer: "B", explanation: "The climax is the dramatic peak where the central conflict reaches its most intense moment.", year: 2025 },
    { question: "Realism in literature aims to:", option_a: "present life as it actually is", option_b: "create fantasy worlds", option_c: "use supernatural elements", option_d: "focus only on nature", correct_answer: "A", explanation: "Realism portrays everyday life and society as it is, without idealization or romantic elements.", year: 2025 },
    { question: "A haiku is a Japanese poem with:", option_a: "five lines", option_b: "three lines of 5, 7, and 5 syllables", option_c: "ten lines", option_d: "no structure", correct_answer: "B", explanation: "A traditional haiku has three lines with a syllable pattern of 5-7-5.", year: 2025 },
    { question: "Archetype in literature refers to:", option_a: "a new type of character", option_b: "a universally recognized symbol, character, or pattern", option_c: "a modern invention", option_d: "a specific author's style", correct_answer: "B", explanation: "Archetypes are recurring symbols, settings, or character types found across cultures and literature.", year: 2025 },
    { question: "The unreliable narrator device creates:", option_a: "clarity", option_b: "uncertainty and invites readers to question the story", option_c: "a predictable plot", option_d: "a happy ending", correct_answer: "B", explanation: "An unreliable narrator creates ambiguity and engages readers in interpreting the true story.", year: 2025 },
  ],

  commerce: [
    { question: "A joint venture is:", option_a: "a type of bank loan", option_b: "a business arrangement where two or more parties agree to pool resources for a specific task", option_c: "a type of insurance", option_d: "a government agency", correct_answer: "B", explanation: "A joint venture involves two or more parties combining resources for a specific business project.", year: 2025 },
    { question: "Insurable risk must be:", option_a: "certain to happen", option_b: "uncertain, fortuitous, and measurable", option_c: "deliberately caused", option_d: "too small to matter", correct_answer: "B", explanation: "Insurable risks must be accidental, measurable, and have a determinable probability and financial impact.", year: 2025 },
    { question: "A bill of lading serves as:", option_a: "a receipt for goods shipped", option_b: "a contract of carriage", option_c: "a document of title to goods", option_d: "all of the above", correct_answer: "D", explanation: "A bill of lading functions as a receipt, contract of carriage, and document of title for shipped goods.", year: 2025 },
    { question: "The principle of indemnity in insurance means:", option_a: "the insured profits from a claim", option_b: "the insured is restored to the same financial position as before the loss", option_c: "the insurer profits from claims", option_d: "claims are never paid", correct_answer: "B", explanation: "Indemnity ensures the insured is compensated only to the extent of the actual loss, no more.", year: 2025 },
    { question: "E-commerce refers to:", option_a: "traditional shop trading", option_b: "buying and selling goods online", option_c: "barter trade", option_d: "wholesale trading", correct_answer: "B", explanation: "E-commerce is the buying and selling of goods and services over the internet.", year: 2025 },
    { question: "Stock exchange is a market for:", option_a: "buying groceries", option_b: "trading shares and securities", option_c: "buying land", option_d: "exchanging currencies", correct_answer: "B", explanation: "A stock exchange is a regulated marketplace where shares and securities are bought and sold.", year: 2025 },
    { question: "A warehouse receipt is:", option_a: "proof of payment", option_b: "a document acknowledging goods stored in a warehouse", option_c: "a shipping label", option_d: "a tax receipt", correct_answer: "B", explanation: "A warehouse receipt confirms that goods have been deposited in a warehouse for safekeeping.", year: 2025 },
    { question: "The Consumer Protection Council in Nigeria:", option_a: "manufactures goods", option_b: "protects consumers from harmful products and unfair business practices", option_c: "sets prices for all goods", option_d: "controls imports only", correct_answer: "B", explanation: "The CPC safeguards consumer interests by ensuring product safety and fair treatment in the marketplace.", year: 2025 },
    { question: "Mercantilism is an economic theory that:", option_a: "advocates free trade", option_b: "promotes exports and restricts imports to accumulate wealth", option_c: "supports government ownership of all industries", option_d: "encourages only agriculture", correct_answer: "B", explanation: "Mercantilism主张通过贸易顺差积累国家财富，鼓励出口限制进口。", year: 2025 },
    { question: "A factor is a person who:", option_a: "sells goods directly to consumers", option_b: "acts as an agent selling goods on commission", option_c: "manufactures products", option_d: "transports goods", correct_answer: "B", explanation: "A factor acts as an agent, selling goods on behalf of principals and earning commission.", year: 2025 },
    { question: "Goodwill in business valuation:", option_a: "is a tangible asset", option_b: "represents the reputation and customer loyalty of a business", option_c: "is always zero", option_d: "equals total assets", correct_answer: "B", explanation: "Goodwill is an intangible asset reflecting a business's reputation, customer base, and brand value.", year: 2025 },
    { question: "Dumping in international trade means:", option_a: "shipping goods legally", option_b: "selling goods in a foreign market below cost or below home market price", option_c: "recycling products", option_d: "donating goods to charity", correct_answer: "B", explanation: "Dumping occurs when a company exports goods at prices lower than domestic market prices.", year: 2025 },
    { question: "The Association of Southeast Asian Nations (ASEAN) was formed to:", option_a: "promote military alliance", option_b: "accelerate economic growth and promote regional peace", option_c: "ban all trade", option_d: "control population growth", correct_answer: "B", explanation: "ASEAN promotes economic growth, social progress, and cultural development in Southeast Asia.", year: 2025 },
    { question: "Insider trading is:", option_a: "legal stock trading", option_b: "trading stocks based on confidential, non-public information", option_c: "trading within a company's premises", option_d: "buying company products", correct_answer: "B", explanation: "Insider trading is illegal — using confidential corporate information to gain advantage in stock markets.", year: 2025 },
    { question: "A trademark is:", option_a: "a type of patent", option_b: "a recognizable sign or design identifying products or services", option_c: "a business license", option_d: "a financial document", correct_answer: "B", explanation: "A trademark distinguishes a company's products from competitors and is legally protected.", year: 2025 },
    { question: "Strategic alliances in business:", option_a: "are always between competitors", option_b: "involve cooperation between firms to achieve mutually beneficial goals", option_c: "eliminate competition entirely", option_d: "only work in agriculture", correct_answer: "B", explanation: "Strategic alliances allow companies to share resources and capabilities while remaining independent.", year: 2025 },
    { question: "Brand loyalty means:", option_a: "customers switch brands frequently", option_b: "consumers consistently prefer and repurchase the same brand", option_c: "the brand is cheapest", option_d: "the brand has no competitors", correct_answer: "B", explanation: "Brand loyalty reflects a consumer's consistent preference for and repeat purchase of a particular brand.", year: 2025 },
    { question: "The Consumer Price Index (CPI) measures:", option_a: "stock market performance", option_b: "changes in the general price level of goods and services over time", option_c: "company profits", option_d: "exchange rates", correct_answer: "B", explanation: "CPI tracks the average change in prices paid by consumers for a basket of goods and services.", year: 2025 },
    { question: "A franchise is:", option_a: "a government permit", option_b: "a license to operate a business using the brand and model of an established company", option_c: "a type of loan", option_d: "a trade union", correct_answer: "B", explanation: "A franchise allows an individual to operate a business under an established brand's name and system.", year: 2025 },
    { question: "Central clearing in financial markets:", option_a: "increases risk", option_b: "reduces counterparty risk by acting as intermediary", option_c: "eliminates all trading", option_d: "only applies to commodities", correct_answer: "B", explanation: "Central clearing houses act as intermediaries, reducing the risk of default by either party.", year: 2025 },
    { question: "Price discrimination means:", option_a: "giving discounts to all customers", option_b: "charging different prices to different buyers for the same product", option_c: "selling only expensive products", option_d: "refusing to sell to some customers", correct_answer: "B", explanation: "Price discrimination charges different prices based on willingness to pay, not cost differences.", year: 2025 },
    { question: "A sweat equity is:", option_a: "physical exercise", option_b: "equity earned through work or effort rather than financial investment", option_c: "tax on labor", option_d: "a type of bond", correct_answer: "B", explanation: "Sweat equity is ownership interest obtained through contributions of labor rather than capital.", year: 2025 },
    { question: "Market capitalization is:", option_a: "total assets of a company", option_b: "the total market value of a company's outstanding shares", option_c: "annual revenue", option_d: "net profit", correct_answer: "B", explanation: "Market cap = Share price × Number of outstanding shares, indicating a company's total equity value.", year: 2025 },
    { question: "Barter trade involves:", option_a: "using money", option_b: "direct exchange of goods and services without money", option_c: "online payments", option_d: "bank transfers", correct_answer: "B", explanation: "Barter is a system of exchange where goods or services are directly traded for other goods or services.", year: 2025 },
    { question: "A trade union is:", option_a: "a government body", option_b: "an organized association of workers formed to protect and advance their interests", option_c: "a business corporation", option_d: "a type of bank", correct_answer: "B", explanation: "Trade unions negotiate with employers on behalf of workers for better wages and working conditions.", year: 2025 },
    { question: "Foreign direct investment (FDI) is:", option_a: "lending money abroad", option_b: "an investment made by a firm in one country into business interests in another country", option_c: "tourism abroad", option_d: "sending remittances", correct_answer: "B", explanation: "FDI involves establishing business operations or acquiring business assets in another country.", year: 2025 },
    { question: "The World Trade Organization (WTO) promotes:", option_a: "military cooperation", option_b: "rules for international trade and resolving trade disputes", option_c: "cultural exchange only", option_d: "environmental protection", correct_answer: "B", explanation: "The WTO oversees global trade rules, promotes free trade, and resolves disputes between member nations.", year: 2025 },
    { question: "A holding company is one that:", option_a: "manufactures products directly", option_b: "owns controlling interests in other companies", option_c: "provides retail services", option_d: "mines raw materials", correct_answer: "B", explanation: "A holding company owns enough stock in other companies to control their management and policies.", year: 2025 },
    { question: "Supply chain management involves:", option_a: "only manufacturing", option_b: "managing the flow of goods from raw materials to the final consumer", option_c: "only retail sales", option_d: "only accounting", correct_answer: "B", explanation: "Supply chain management coordinates all activities from sourcing raw materials to delivering products to consumers.", year: 2025 },
    { question: "An oligopsony is a market with:", option_a: "many buyers and one seller", option_b: "few buyers and many sellers", option_c: "one buyer and one seller", option_d: "many buyers and many sellers", correct_answer: "B", explanation: "An oligopsony is a market structure where a small number of buyers dominate the market.", year: 2025 },
    { question: "Corporate governance refers to:", option_a: "employee benefits", option_b: "the system of rules and practices by which a company is directed and controlled", option_c: "product quality", option_d: "marketing strategies", correct_answer: "B", explanation: "Corporate governance ensures accountability, fairness, and transparency in company management.", year: 2025 },
    { question: "The Commodity Exchange Act regulates:", option_a: "stock markets", option_b: "futures and options trading to prevent fraud and manipulation", option_c: "banking operations", option_d: "insurance companies", correct_answer: "B", explanation: "The CEA provides a regulatory framework for commodity futures and options markets.", year: 2025 },
    { question: "A leveraged buyout (LBO) is:", option_a: "buying assets with cash", option_b: "acquiring a company using mostly borrowed money", option_c: "selling company assets", option_d: "merging two companies", correct_answer: "B", explanation: "An LBO is the acquisition of a company where a significant portion is financed through debt.", year: 2025 },
    { question: "Trade credit is:", option_a: "a bank loan", option_b: "an agreement to defer payment for goods purchased", option_c: "credit card debt", option_d: "a mortgage", correct_answer: "B", explanation: "Trade credit allows buyers to purchase goods now and pay the supplier at a later date.", year: 2025 },
    { question: "Comparative advantage means:", option_a: "having the cheapest products", option_b: "being able to produce a good at a lower opportunity cost than others", option_c: "having more resources", option_d: "producing more total output", correct_answer: "B", explanation: "Comparative advantage exists when a country can produce a good at a lower opportunity cost.", year: 2025 },
    { question: "The Lagos Chamber of Commerce and Industry (LCCI) promotes:", option_a: "military activities", option_b: "commercial and industrial interests of businesses in Nigeria", option_c: "agriculture only", option_d: "religious activities", correct_answer: "B", explanation: "LCCI advocates for business-friendly policies and supports commercial activities in Nigeria.", year: 2025 },
    { question: "Trade barriers include all of the following EXCEPT:", option_a: "tariffs", option_b: "quotas", option_c: "free trade agreements", option_d: "embargoes", correct_answer: "C", explanation: "Free trade agreements reduce barriers, while tariffs, quotas, and embargoes restrict trade.", year: 2025 },
    { question: "A promissory note is:", option_a: "a receipt", option_b: "a written promise to pay a specified amount of money", option_c: "an insurance policy", option_d: "a business license", correct_answer: "B", explanation: "A promissory note is a financial instrument containing a written promise to pay a stated sum.", year: 2025 },
    { question: "Economic integration aims to:", option_a: "increase trade barriers between countries", option_b: "reduce or eliminate trade barriers between participating countries", option_c: "isolate economies", option_d: "create monopolies", correct_answer: "B", explanation: "Economic integration involves agreements between countries to reduce trade barriers and coordinate policies.", year: 2025 },
    { question: "An initial public offering (IPO) is:", option_a: "a company's first sale of stock to the public", option_b: "a private loan", option_c: "a government bond sale", option_d: "a merger", correct_answer: "A", explanation: "An IPO is when a private company first offers its shares to the public on a stock exchange.", year: 2025 },
  ],

  accounting: [
    { question: "The trial balance is prepared to:", option_a: "calculate profit", option_b: "check that total debits equal total credits", option_c: "prepare the income statement", option_d: "calculate tax", correct_answer: "B", explanation: "A trial balance lists all account balances to verify that debits and credits are equal.", year: 2025 },
    { question: "Amortization refers to:", option_a: "increasing asset value", option_b: "spreading the cost of an intangible asset over its useful life", option_c: "depreciating buildings", option_d: "valuing inventory", correct_answer: "B", explanation: "Amortization allocates the cost of intangible assets (patents, copyrights) over their useful life.", year: 2025 },
    { question: "A current asset is one that:", option_a: "will last more than a year", option_b: "is expected to be converted to cash within one year", option_c: "is a building", option_d: "cannot be sold", correct_answer: "B", explanation: "Current assets are expected to be converted to cash, sold, or consumed within one year.", year: 2025 },
    { question: "The balance sheet shows:", option_a: "revenue and expenses only", option_b: "assets, liabilities, and equity at a specific point in time", option_c: "cash flow only", option_d: "profit for the year", correct_answer: "B", explanation: "The balance sheet presents the financial position (Assets = Liabilities + Equity) at a specific date.", year: 2025 },
    { question: "Depreciation is NOT charged on:", option_a: "buildings", option_b: "motor vehicles", option_c: "land", option_d: "equipment", correct_answer: "C", explanation: "Land is not depreciated because it has an unlimited useful life and does not wear out.", year: 2025 },
    { question: "Accounts receivable is:", option_a: "money owed to the business by customers", option_b: "money the business owes to suppliers", option_c: "cash on hand", option_d: "bank loans", correct_answer: "A", explanation: "Accounts receivable represents amounts owed to the business by customers who bought on credit.", year: 2025 },
    { question: "The accounting concept of going concern assumes:", option_a: "the business will close soon", option_b: "the business will continue operating indefinitely", option_c: "the business is new", option_d: "the business has no debts", correct_answer: "B", explanation: "The going concern concept assumes the business will continue to operate for the foreseeable future.", year: 2025 },
    { question: "Inventory valuation methods include all EXCEPT:", option_a: "FIFO", option_b: "LIFO", option_c: "average cost", option_d: "straight-line", correct_answer: "D", explanation: "FIFO, LIFO, and average cost are inventory valuation methods; straight-line is a depreciation method.", year: 2025 },
    { question: "The gross profit is calculated as:", option_a: "revenue minus all expenses", option_b: "revenue minus cost of goods sold", option_c: "net income plus tax", option_d: "total assets minus liabilities", correct_answer: "B", explanation: "Gross Profit = Revenue - Cost of Goods Sold (COGS), before operating expenses.", year: 2025 },
    { question: "Provision for doubtful debts is:", option_a: "actual bad debts written off", option_b: "an estimate of receivables that may not be collected", option_c: "cash received from debtors", option_d: "a type of revenue", correct_answer: "B", explanation: "A provision for doubtful debts is an estimated loss from receivables that may prove uncollectible.", year: 2025 },
    { question: "An income statement shows:", option_a: "financial position at a date", option_b: "revenues, expenses, and profit or loss over a period", option_c: "only cash transactions", option_d: "only assets", correct_answer: "B", explanation: "The income statement (P&L) reports revenues, expenses, and the resulting profit or loss over a period.", year: 2025 },
    { question: "Working capital is calculated as:", option_a: "total assets minus total liabilities", option_b: "current assets minus current liabilities", option_c: "net income plus depreciation", option_d: "fixed assets minus long-term debt", correct_answer: "B", explanation: "Working Capital = Current Assets - Current Liabilities, measuring short-term financial health.", year: 2025 },
    { question: "A credit note is issued when:", option_a: "goods are sold", option_b: "goods are returned by a customer or an overcharge is corrected", option_c: "cash is received", option_d: "new stock is purchased", correct_answer: "B", explanation: "A credit note reduces the amount a customer owes, issued when goods are returned or overcharged.", year: 2025 },
    { question: "The concept of consistency in accounting requires:", option_a: "changing methods every year", option_b: "using the same accounting methods from period to period", option_c: "ignoring accounting standards", option_d: "preparing reports quarterly only", correct_answer: "B", explanation: "Consistency requires using the same accounting policies and methods to ensure comparability over time.", year: 2025 },
    { question: "Accrual accounting recognizes revenue:", option_a: "only when cash is received", option_b: "when earned, regardless of when cash is received", option_c: "at the end of the year only", option_d: "never", correct_answer: "B", explanation: "Accrual accounting records revenue when it is earned, not necessarily when cash is received.", year: 2025 },
    { question: "A suspense account is used to:", option_a: "hide fraudulent transactions", option_b: "temporarily hold entries until the correct account is determined", option_c: "store confidential data", option_d: "record depreciation", correct_answer: "B", explanation: "A suspense account is a temporary account used when the correct account for a transaction is uncertain.", year: 2025 },
    { question: "The acid test ratio uses:", option_a: "current assets and current liabilities", option_b: "(current assets - inventory) / current liabilities", option_c: "total assets / total liabilities", option_d: "cash / long-term debt", correct_answer: "B", explanation: "The acid test (quick) ratio excludes inventory: (Current Assets - Inventory) / Current Liabilities.", year: 2025 },
    { question: "Intangible assets include:", option_a: "buildings", option_b: "patents, trademarks, and goodwill", option_c: "machinery", option_d: "vehicles", correct_answer: "B", explanation: "Intangible assets lack physical substance but provide value (patents, trademarks, copyrights, goodwill).", year: 2025 },
    { question: "The cash basis of accounting records transactions:", option_a: "when earned or incurred", option_b: "only when cash is received or paid", option_c: "at the end of the financial year", option_d: "never", correct_answer: "B", explanation: "Cash basis accounting recognizes transactions only when cash changes hands.", year: 2025 },
    { question: "Fixed assets are also known as:", option_a: "current assets", option_b: "non-current assets or property, plant, and equipment", option_c: "liquid assets", option_d: "intangible assets", correct_answer: "B", explanation: "Fixed assets (PP&E) are long-term tangible assets used in operations, not intended for resale.", year: 2025 },
    { question: "The purpose of depreciation is to:", option_a: "reduce tax legally", option_b: "allocate the cost of a tangible asset over its useful life", option_c: "increase asset value", option_d: "calculate profit", correct_answer: "B", explanation: "Depreciation allocates the cost of a fixed asset over its useful life to match expense with revenue.", year: 2025 },
    { question: "An audit trail means:", option_a: "following a criminal", option_b: "a chronological record that allows tracing of transactions from source to financial statements", option_c: "hiding financial records", option_d: "destroying old documents", correct_answer: "B", explanation: "An audit trail is a step-by-step record allowing verification of transactions from origin to report.", year: 2025 },
    { question: "VAT (Value Added Tax) is:", option_a: "a tax on income", option_b: "a tax on the value added at each stage of production and distribution", option_c: "a property tax", option_d: "a payroll tax", correct_answer: "B", explanation: "VAT is collected at each stage of the supply chain on the value added to goods and services.", year: 2025 },
    { question: "The cash flow statement classifies cash flows into:", option_a: "income and expenses", option_b: "operating, investing, and financing activities", option_c: "assets and liabilities", option_d: "debits and credits", correct_answer: "B", explanation: "Cash flow statement reports cash movements in three categories: operating, investing, and financing.", year: 2025 },
    { question: "A petty cash fund is used for:", option_a: "large capital purchases", option_b: "small, routine expenses", option_c: "paying salaries", option_d: "bank transfers", correct_answer: "B", explanation: "Petty cash covers small day-to-day expenses like office supplies, postage, and minor purchases.", year: 2025 },
    { question: "The conservatism principle requires:", option_a: "overstating assets", option_b: "anticipating no profits but providing for all possible losses", option_c: "understating liabilities", option_d: "ignoring bad debts", correct_answer: "B", explanation: "Conservatism requires recognizing expenses and liabilities as soon as possible, but revenue only when assured.", year: 2025 },
    { question: "A ledger is:", option_a: "a book of original entry", option_b: "a book containing all accounts with their debits and credits", option_c: "a bank statement", option_d: "an invoice", correct_answer: "B", explanation: "The ledger (or general ledger) is the main book containing all accounts and their balances.", year: 2025 },
    { question: "The return on equity (ROE) formula is:", option_a: "net income / total assets", option_b: "net income / shareholders' equity", option_c: "revenue / total assets", option_d: "gross profit / revenue", correct_answer: "B", explanation: "ROE = Net Income / Shareholders' Equity, measuring how effectively equity is used to generate profit.", year: 2025 },
    { question: "Cost accounting primarily focuses on:", option_a: "financial reporting to external parties", option_b: "determining and controlling costs of production", option_c: "tax preparation", option_d: "auditing financial statements", correct_answer: "B", explanation: "Cost accounting records and analyzes costs to help management control operations and make decisions.", year: 2025 },
    { question: "A contingent liability is:", option_a: "a liability that is certain to occur", option_b: "a potential obligation that depends on a future event", option_c: "an asset", option_d: "shareholders' equity", correct_answer: "B", explanation: "A contingent liability depends on the outcome of a future event (e.g., pending lawsuits).", year: 2025 },
    { question: "The hierarchy of accounting standards in Nigeria includes:", option_a: "IFRS only", option_b: "IFRS, IFRS for SMEs, and Nigerian GAAP", option_c: "US GAAP only", option_d: "no standards exist", correct_answer: "B", explanation: "Nigeria follows IFRS for public companies, IFRS for SMEs for smaller entities, and some local GAAP.", year: 2025 },
    { question: "An adjusted trial balance is prepared:", option_a: "before making adjustments", option_b: "after adjusting entries are posted to verify equality", option_c: "only at company formation", option_d: "before the unadjusted trial balance", correct_answer: "B", explanation: "The adjusted trial balance is prepared after adjusting entries to confirm debits still equal credits.", year: 2025 },
    { question: "Equity financing means:", option_a: "borrowing from a bank", option_b: "raising capital by selling shares of the company", option_c: "taking a mortgage", option_d: "issuing bonds", correct_answer: "B", explanation: "Equity financing raises capital by selling ownership shares in the company to investors.", year: 2025 },
    { question: "The true and fair view principle requires:", option_a: "showing only profit", option_b: "financial statements to accurately reflect the company's financial position", option_c: "hiding losses", option_d: "using only estimates", correct_answer: "B", explanation: "Financial statements must present a true and fair view of the entity's financial position and performance.", year: 2025 },
    { question: "An operating lease is:", option_a: "a purchase of an asset", option_b: "a short-term rental agreement without transfer of ownership", option_c: "a long-term loan", option_d: "a type of bond", correct_answer: "B", explanation: "An operating lease is a rental agreement where the asset is returned at the end of the lease term.", year: 2025 },
    { question: "The debit side of an account records:", option_a: "only revenue", option_b: "increases in assets and expenses, and decreases in liabilities and equity", option_c: "only cash payments", option_d: "only credit sales", correct_answer: "B", explanation: "Debits increase assets/expenses and decrease liabilities/equity/revenue.", year: 2025 },
    { question: "Internal audit is conducted by:", option_a: "external auditors", option_b: "employees within the organization to review controls and operations", option_c: "tax authorities", option_d: "shareholders", correct_answer: "B", explanation: "Internal audit is performed by company staff to evaluate internal controls, risk management, and governance.", year: 2025 },
    { question: "Barter accounting is NOT applicable in:", option_a: "ancient civilizations", option_b: "modern monetary economies", option_c: "underdeveloped communities", option_d: "rural areas", correct_answer: "B", explanation: "Barter accounting is not used in modern monetary economies where money is the medium of exchange.", year: 2025 },
    { question: "Statement of changes in equity shows:", option_a: "only profit", option_b: "movements in equity including share issues, dividends, and profit or loss", option_c: "cash inflows only", option_d: "assets only", correct_answer: "B", explanation: "This statement reconciles the opening and closing equity balances, showing all equity movements.", year: 2025 },
    { question: "Financial leverage refers to:", option_a: "using equity only", option_b: "using borrowed funds to increase potential return on investment", option_c: "selling assets", option_d: "reducing debt", correct_answer: "B", explanation: "Financial leverage uses debt to amplify returns, but also increases risk.", year: 2025 },
  ],
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    let insertedCount = 0;
    let skippedCount = 0;
    const results: Record<string, { inserted: number; skipped: number }> = {};

    for (const [subject, questions] of Object.entries(QUESTIONS)) {
      results[subject] = { inserted: 0, skipped: 0 };

      for (const q of questions) {
        const { data: existing } = await supabase
          .from('jamb_questions')
          .select('id')
          .eq('question', q.question)
          .eq('subject', subject)
          .maybeSingle();

        if (existing) {
          skippedCount++;
          results[subject].skipped++;
          continue;
        }

        const { error } = await supabase
          .from('jamb_questions')
          .insert({
            subject,
            question: q.question,
            option_a: q.option_a,
            option_b: q.option_b,
            option_c: q.option_c,
            option_d: q.option_d,
            correct_answer: q.correct_answer,
            explanation: q.explanation,
            year: q.year,
          });

        if (!error) {
          insertedCount++;
          results[subject].inserted++;
        }
      }
    }

    const { count } = await supabase
      .from('jamb_questions')
      .select('*', { count: 'exact', head: true });

    return new Response(
      JSON.stringify({
        success: true,
        message: `Seeded ${insertedCount} new questions, skipped ${skippedCount} duplicates`,
        inserted: insertedCount,
        skipped: skippedCount,
        total_in_database: count,
        by_subject: results,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ success: false, error: message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
