import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type' };

type SeedQuestion = { question: string; option_a: string; option_b: string; option_c: string; option_d: string; correct_answer: string; explanation: string };
function q(s: string, a: string, b: string, c: string, d: string, ca: string, e: string): SeedQuestion {
  return { question: s, option_a: a, option_b: b, option_c: c, option_d: d, correct_answer: ca, explanation: e };
}

const LIT = [
  q("The main character in a literary work is the:", "Antagonist", "Protagonist", "Narrator", "Author", "B", "The protagonist is the central character."),
  q("A stanza of two lines is called:", "Couplet", "Tercet", "Quatrain", "Sestet", "A", "A couplet has two lines."),
  q("'The boy's clothes were rags' is an example of:", "Metaphor", "Imagery", "Hyperbole", "Symbolism", "B", "Imagery creates vivid mental pictures."),
  q("The literary term for the sequence of events is:", "Plot", "Theme", "Setting", "Character", "A", "Plot is the sequence of events in a story."),
  q("A tragedy ends:", "Happily", "Sadly or disastrously", "Comically", "Ambiguously", "B", "Tragedy ends in disaster for the protagonist."),
  q("Rhyme scheme ABAB is typical of:", "Sonnet", "Limerick", "Free verse", "Blank verse", "A", "Shakespearean sonnets use ABAB CDCD EFEF GG."),
  q("The atmosphere of a literary work is its:", "Plot", "Mood", "Theme", "Climax", "B", "Mood is the emotional atmosphere created."),
  q("A foil character is one who:", "Opposes the hero", "Contrasts with another", "Narrates the story", "Dies at the end", "B", "A foil highlights traits of another by contrast."),
  q("'The curfew tolls the knell of parting day' contains:", "Alliteration", "Assonance", "Onomatopoeia", "Rhyme", "A", "Alliteration: repetition of 't' and 'k' sounds."),
  q("The setting of a novel includes:", "Time and place", "Only time", "Only place", "Characters", "A", "Setting is the time and place of the story."),
  q("A metaphor that extends throughout a passage is:", "Simile", "Extended metaphor", "Personification", "Oxymoron", "B", "Extended metaphor runs through multiple sentences."),
  q("Dramatic monologue features:", "One speaker", "Two speakers", "Multiple speakers", "No speaker", "A", "Dramatic monologue has a single speaker addressing an audience."),
  q("The point of view where narrator knows all is:", "First person", "Second person", "Third person limited", "Third person omniscient", "D", "Omniscient narrator knows all thoughts and feelings."),
  q("'Ode to a Nightingale' was written by:", "Wordsworth", "Keats", "Shelley", "Byron", "B", "John Keats wrote 'Ode to a Nightingale'."),
  q("A short story typically focuses on:", "One incident", "Many generations", "Multiple plots", "Historical events", "A", "Short stories focus on a single incident or character."),
  q("Satire uses humor to:", "Entertain only", "Criticize or expose folly", "Describe nature", "Teach grammar", "B", "Satire ridicules human vice or folly."),
  q("Genre refers to:", "The title", "The category or type", "The author", "The publisher", "B", "Genre categorizes works by style/form."),
  q("The character who opposes the protagonist is the:", "Hero", "Antagonist", "Confidante", "Narrator", "B", "Antagonist opposes the protagonist."),
  q("A soliloquy reveals:", "Inner thoughts", "Dialogue", "Action", "Description", "A", "Soliloquy reveals a character's private thoughts aloud."),
  q("'Things Fall Apart' is set in:", "Nigeria", "Ghana", "Kenya", "South Africa", "A", "Achebe's novel is set in pre-colonial Nigeria."),
  q("Meter in poetry refers to:", "Rhyme scheme", "Rhythmic pattern", "Line length", "Stanza form", "B", "Meter is the pattern of stressed/unstressed syllables."),
  q("A bildungsroman is a novel about:", "War", "Coming of age", "Detective work", "Romance", "B", "Bildungsroman focuses on protagonist's moral/psychological growth."),
  q("The climax of a play is its:", "Beginning", "Highest point of tension", "Resolution", "Introduction", "B", "Climax is the turning point of highest tension."),
  q("The word 'tragic flaw' is also called:", "Hubris", "Catharsis", "Anagnorisis", "Peripeteia", "A", "Hubris is the protagonist's fatal pride or flaw."),
  q("A parody imitates a work for:", "Comic effect", "Serious criticism", "Educational purpose", "Legal reason", "A", "Parody imitates for humor or ridicule."),
  q("The line 'To be or not to be' is from:", "Macbeth", "Hamlet", "Othello", "King Lear", "B", "This famous soliloquy is from Shakespeare's Hamlet."),
  q("Foreshadowing hints at:", "Past events", "Future events", "The setting", "The theme", "B", "Foreshadowing hints at events to come."),
  q("'Weep not, my wanton, smile upon my knee' uses:", "Alliteration", "Assonance", "Consonance", "Onomatopoeia", "A", "Alliteration with repeated 'w' sound."),
  q("The main theme of 'The Great Gatsby' is:", "War", "The American Dream", "Technology", "Nature", "B", "The novel critiques the American Dream."),
  q("Stream of consciousness technique was used by:", "Chaucer", "Joyce", "Shakespeare", "Dickens", "B", "James Joyce pioneered stream of consciousness."),
  q("Epistolary novel is written in:", "Letters", "Verse", "Dialogue", "Diary entries", "A", "Epistolary novels use letters between characters."),
  q("Suspense keeps the reader:", "Bored", "Anxious about outcome", "Sleepy", "Angry", "B", "Suspense creates anxious uncertainty about events."),
  q("Context in literature refers to:", "Word definition", "Circumstances around the work", "Grammar rules", "Paragraph structure", "B", "Context includes historical, social, and cultural background."),
  q("'The sun smiled down on us' is:", "Simile", "Metaphor", "Personification", "Hyperbole", "C", "Personification gives human traits to the sun."),
  q("A novella is shorter than:", "A short story", "A novel", "A poem", "An essay", "B", "Novella is between short story and novel in length."),
];

const ECON = [
  q("Economics is the study of:", "Money only", "Scarcity and choice", "Banks only", "Markets only", "B", "Economics studies allocation of scarce resources."),
  q("The basic economic problem is:", "Inflation", "Scarcity", "Unemployment", "Taxation", "B", "Scarcity is the fundamental economic problem."),
  q("Demand refers to quantity ___ at a given price.", "Supplied", "Wanted and able to buy", "Produced", "Exported", "B", "Demand = willingness + ability to purchase."),
  q("When price increases, quantity demanded typically:", "Increases", "Decreases", "Stays same", "Doubles", "B", "Law of demand: price up, quantity down."),
  q("The law of supply states that as price rises, supply:", "Falls", "Rises", "Stays constant", "Becomes zero", "B", "Supply rises with price (ceteris paribus)."),
  q("A market with many sellers of identical products is:", "Monopoly", "Oligopoly", "Perfect competition", "Monopolistic", "C", "Perfect competition has many sellers, identical products."),
  q("GDP measures:", "Total output of a country", "Population", "Tax revenue", "Exports only", "A", "GDP is the total value of goods/services produced."),
  q("Inflation is a sustained increase in:", "Employment", "General price level", "Exports", "Population", "B", "Inflation is rising general price levels."),
  q("The central bank of Nigeria is:", "First Bank", "CBN", "UBA", "Access Bank", "B", "Central Bank of Nigeria is the central bank."),
  q("Fiscal policy involves changes in:", "Interest rates", "Government spending and taxes", "Money supply", "Exchange rates", "B", "Fiscal policy: government revenue and expenditure."),
  q("Opportunity cost is the ___ option forgone.", "Best alternative", "Cheapest", "Most expensive", "Next best", "D", "Opportunity cost is the next best alternative forgone."),
  q("Which is a direct tax?", "VAT", "Income tax", "Excise duty", "Import duty", "B", "Income tax is paid directly to government."),
  q("Privatization means transferring from:", "Public to private sector", "Private to public", "Local to foreign", "None", "A", "Privatization: government assets sold to private sector."),
  q("The demand curve slopes:", "Upward", "Downward", "Vertical", "Horizontal", "B", "Demand curve slopes downward (inverse relationship)."),
  q("Monopoly has ___ seller(s).", "One", "Two", "Few", "Many", "A", "Monopoly has a single seller."),
  q("Unemployment occurs when people:", "Are working", "Are willing but cannot find work", "Are retired", "Are in school", "B", "Unemployment: able and willing but no job."),
  q("Balance of trade records:", "Visible exports and imports", "All international transactions", "Capital flows", "Tourism", "A", "Balance of trade = visible exports - visible imports."),
  q("The multiplier effect describes:", "Tax increase", "Initial spending causing larger income change", "Interest rate effect", "Exchange rate change", "B", "Multiplier amplifies initial spending through the economy."),
  q("Utility means:", "Usefulness", "Price", "Cost", "Supply", "A", "Utility is the satisfaction from consuming a good."),
  q("A minimum price set above equilibrium creates:", "Shortage", "Surplus", "Equilibrium", "Black market", "B", "Price floor above equilibrium creates excess supply."),
  q("Division of labor increases:", "Boredom", "Productivity", "Unemployment", "Cost", "B", "Specialization increases efficiency and output."),
  q("Per capita income is:", "Total GDP", "GDP per person", "Total tax", "Total savings", "B", "Per capita income = GDP / population."),
  q("Money serves as a:", "Medium of exchange", "Store of value", "Unit of account", "All of the above", "D", "Money has three primary functions."),
  q("An inferior good has ___ demand as income rises.", "Rising", "Falling", "Constant", "Zero", "B", "Demand for inferior goods falls as income rises."),
  q("Cartel is a formal agreement among:", "Buyers", "Sellers to fix prices", "Workers", "Banks", "B", "Cartels collude to fix prices/output."),
  q("Depreciation of currency makes exports:", "Cheaper", "More expensive", "Unchanged", "Zero", "A", "Depreciation: exports cheaper, imports costlier."),
  q("Production possibility curve shows:", "Maximum output combinations", "Actual output", "Market demand", "Price levels", "A", "PPC shows alternative combinations of two goods."),
  q("Commercial banks create:", "Goods", "Credit/money", "Taxes", "Laws", "B", "Banks create credit through lending."),
  q("Elastic demand means quantity is ___ to price changes.", "Unresponsive", "Responsive", "Equal", "Inverse", "B", "Elastic: Qd changes significantly with price."),
  q("A budget deficit occurs when:", "Revenue > expenditure", "Expenditure > revenue", "Revenue = expenditure", "No revenue", "B", "Deficit: spending exceeds revenue."),
  q("Microeconomics studies:", "Individual units", "Entire economy", "Global trade", "National income", "A", "Micro focuses on individual firms/households."),
  q("Macroeconomics studies:", "Individual firms", "Entire economy aggregates", "Single markets", "Prices only", "B", "Macro studies economy-wide phenomena."),
  q("The World Bank provides:", "Loans for development", "Short-term trade finance", "Insurance", "Currency exchange", "A", "World Bank gives development loans."),
  q("Tax evasion is:", "Legal avoidance", "Illegal non-payment", "Tax reduction", "Government subsidy", "B", "Evasion: illegally not paying taxes due."),
  q("Labor is a factor of production rewarded with:", "Rent", "Wages", "Interest", "Profit", "B", "Labor earns wages/salaries."),
  q("Capital in economics refers to:", "Money", "Machines and equipment", "Stocks and shares", "Bank deposits", "B", "Capital are man-made goods for production."),
  q("Land earns ___ as factor reward.", "Rent", "Wages", "Interest", "Profit", "A", "Land earns rent in factor payments."),
  q("Economic growth is measured by GDP:", "Level", "Growth rate", "Distribution", "Composition", "B", "Growth = rate of increase in GDP."),
];

const GEO = [
  q("The largest continent is:", "Africa", "Asia", "Europe", "North America", "B", "Asia is the largest continent by area."),
  q("The latitude of the equator is:", "0°", "23.5°N", "66.5°N", "90°N", "A", "Equator is at 0° latitude."),
  q("A map scale of 1:50,000 means 1 cm represents:", "50 m", "500 m", "5 km", "50 km", "B", "1:50,000 means 1 cm = 500 m on ground."),
  q("The longest river in the world is:", "Nile", "Amazon", "Mississippi", "Yangtze", "A", "The Nile is the world's longest river."),
  q("The savanna vegetation is characterized by:", "Dense forest", "Grasses and scattered trees", "Desert", "Ice", "B", "Savanna has grasses with few trees."),
  q("The main export of Nigeria is:", "Gold", "Crude oil", "Diamonds", "Coal", "B", "Nigeria's main export is crude oil."),
  q("Latitude lines run:", "East-west", "North-south", "Diagonal", "Circular", "A", "Latitudes run parallel to the equator (east-west)."),
  q("Longitude lines run:", "East-west", "North-south", "Diagonal", "Circular", "B", "Longitudes run from pole to pole (north-south)."),
  q("GMT stands for:", "Greenwich Mean Time", "Global Mean Time", "General Meridian Time", "Great Meridian Time", "A", "GMT is the time at the Prime Meridian."),
  q("The earth's core is mainly composed of:", "Silicon", "Iron and nickel", "Carbon", "Aluminum", "B", "Earth's core is iron-nickel alloy."),
  q("Weather refers to ___ conditions.", "Short-term atmospheric", "Long-term climate", "Oceanic", "Soil", "A", "Weather is day-to-day atmospheric conditions."),
  q("The world's largest desert is:", "Sahara", "Gobi", "Kalahari", "Antarctic", "D", "Antarctic is the largest cold desert."),
  q("The capital of Nigeria is:", "Lagos", "Abuja", "Kano", "Port Harcourt", "B", "Abuja is Nigeria's capital city."),
  q("Convectional rainfall occurs due to:", "Mountains", "Heating of ground surface", "Fronts", "Winds", "B", "Convectional: ground heating causes rising air."),
  q("The relief feature formed by volcanic eruption is:", "Plateau", "Volcano", "Delta", "Escarpment", "B", "Volcanoes form from lava/magma eruptions."),
  q("Population density is:", "Total population", "People per square km", "Birth rate", "Death rate", "B", "Density = population / area."),
  q("Arable land is suitable for:", "Building", "Farming/crops", "Mining", "Forestry", "B", "Arable land is farmland for crops."),
  q("The main cause of desertification is:", "Afforestation", "Overgrazing", "Irrigation", "Industrialization", "B", "Overgrazing removes vegetation, causing desert expansion."),
  q("International Date Line roughly follows:", "Equator", "180° longitude", "Prime Meridian", "Tropic of Cancer", "B", "IDL is near 180° longitude."),
  q("The smallest ocean is:", "Pacific", "Atlantic", "Indian", "Arctic", "D", "Arctic Ocean is the smallest."),
  q("Nigeria is located in:", "East Africa", "West Africa", "North Africa", "Southern Africa", "B", "Nigeria is in West Africa."),
  q("The highest mountain in Africa is:", "Kilimanjaro", "Everest", "Atlas", "Ruwenzori", "A", "Mount Kilimanjaro is Africa's highest."),
  q("Urbanization is the movement from:", "City to village", "Rural to urban areas", "North to south", "East to west", "B", "Urbanization: rural-to-urban migration."),
  q("The earth rotates on its axis from:", "East to west", "West to east", "North to south", "South to north", "B", "Earth rotates west to east (counterclockwise)."),
  q("The Tropic of Cancer is at:", "23.5°N", "23.5°S", "66.5°N", "0°", "A", "Tropic of Cancer is 23.5° north."),
  q("Deforestation leads to:", "Soil erosion", "More rainfall", "Fertile soil", "Cooler climate", "A", "Removing trees causes soil erosion."),
  q("The three main rock types are:", "Igneous, sedimentary, metamorphic", "Hard, soft, medium", "Old, new, ancient", "Acid, base, neutral", "A", "Three rock types: igneous, sedimentary, metamorphic."),
  q("A port is a place for:", "Air travel", "Ships to dock", "Trains", "Buses", "B", "Ports handle ship loading/unloading."),
  q("The hydrosphere includes all:", "Rocks", "Water on earth", "Living things", "Gases", "B", "Hydrosphere: earth's water bodies."),
  q("Nigeria shares border with ___ countries.", "2", "3", "4", "5", "C", "Nigeria borders Niger, Chad, Cameroon, Benin (4)."),
  q("Contour lines on a map join points of:", "Equal rainfall", "Equal height", "Equal population", "Equal temperature", "B", "Contours connect points of equal elevation."),
  q("The main industrial area in Nigeria is:", "Kano", "Lagos", "Abuja", "Jos", "B", "Lagos is Nigeria's main industrial hub."),
  q("Greenhouse effect causes:", "Global warming", "Cooling", "More rain", "Less oxygen", "A", "Greenhouse gases trap heat, warming the earth."),
  q("Rivers flowing into the sea form:", "Waterfalls", "Deltas", "Mountains", "Canyons", "B", "Deltas form at river mouths entering sea."),
  q("Mining is an example of ___ industry.", "Primary", "Secondary", "Tertiary", "Quaternary", "A", "Primary industry: extraction of natural resources."),
  q("Wind erosion is common in:", "Rainforest", "Desert regions", "Tundra", "Forests", "B", "Wind erosion dominates in arid desert areas."),
  q("Population pyramid shows:", "Age-sex structure", "Birth rates", "Death rates", "Migration", "A", "Population pyramids display age and sex distribution."),
];

const IRS_Q = [
  q("The first revelation came to Prophet Muhammad at age:", "25", "35", "40", "45", "C", "He received first revelation at age 40."),
  q("The Angel that brought revelation was:", "Mikail", "Jibril", "Israfil", "Malik", "B", "Angel Jibril (Gabriel) brought revelation."),
  q("The first Kalimah is:", "Bismillah", "La ilaha illallah", "Alhamdulillah", "Allahu Akbar", "B", "First Kalimah: 'There is no god but Allah'."),
  q("Surah Al-Fatiha has ___ verses.", "5", "6", "7", "8", "C", "Al-Fatiha has 7 verses."),
  q("The Quran has ___ chapters (Surahs).", "100", "110", "114", "120", "C", "Quran has 114 Surahs."),
  q("The night the Quran was revealed is:", "Lailatul Qadr", "Lailatul Miraj", "Lailatul Bara'at", "Ashura", "A", "Lailatul Qadr (Night of Power) in Ramadan."),
  q("Wudu is the Islamic:", "Prayer", "Ablution", "Fasting", "Charity", "B", "Wudu is ritual purification before prayer."),
  q("The direction Muslims face for prayer is:", "Qibla", "Mihrab", "Minbar", "Kaaba", "A", "Qibla is the direction to Makkah."),
  q("Jumu'ah prayer is on:", "Saturday", "Sunday", "Friday", "Monday", "C", "Friday congregational prayer is Jumu'ah."),
  q("Tayammum is dry ablution using:", "Water", "Sand/clean earth", "Oil", "Perfume", "B", "Tayammum uses clean earth when water unavailable."),
  q("The four rightly guided caliphs are called:", "Mujtahidun", "Khulafa Rashidun", "Sahabah", "Tabieen", "B", "Khulafa Rashidun: Abu Bakr, Umar, Uthman, Ali."),
  q("Hijrah refers to migration to:", "Jerusalem", "Madinah", "Makkah", "Egypt", "B", "Hijrah: migration from Makkah to Madinah."),
  q("The battle of Badr occurred in:", "1 AH", "2 AH", "3 AH", "5 AH", "B", "Battle of Badr in 2 AH."),
  q("Zakatul Fitr is paid at the end of:", "Dhul Hijjah", "Ramadan", "Muharram", "Safar", "B", "Zakatul Fitr at end of Ramadan before Eid."),
  q("The Islamic calendar begins with:", "Muharram", "Ramadan", "Dhul Hijjah", "Rabiul Awwal", "A", "Islamic year starts with Muharram."),
  q("Eid al-Adha commemorates:", "End of Ramadan", "Sacrifice of Ibrahim", "Birth of Prophet", "Revelation of Quran", "B", "Eid al-Adha honors Ibrahim's willingness to sacrifice."),
  q("Makkah is located in:", "Egypt", "Saudi Arabia", "Iraq", "Yemen", "B", "Makkah is in present-day Saudi Arabia."),
  q("The first woman to accept Islam was:", "Aisha", "Khadijah", "Fatimah", "Maryam", "B", "Khadijah, the Prophet's wife, was first."),
  q("The six articles of faith include belief in:", "Five pillars", "Angels", "Imams", "Caliphs", "B", "Belief in angels is an article of faith."),
  q("Sunnah refers to the:", "Quran", "Prophet's teachings and actions", "Islamic law", "Prayers", "B", "Sunnah: sayings and actions of the Prophet."),
  q("Halal means:", "Forbidden", "Permissible", "Recommended", "Obligatory", "B", "Halal means permissible in Islam."),
  q("Haram means:", "Permissible", "Forbidden", "Recommended", "Optional", "B", "Haram is forbidden in Islam."),
  q("The longest Surah in the Quran is:", "Al-Baqarah", "Yasin", "Ar-Rahman", "Al-Fatiha", "A", "Surah Al-Baqarah is the longest."),
  q("Riba (interest) is ___ in Islam.", "Permissible", "Forbidden", "Recommended", "Neutral", "B", "Riba is forbidden (haram)."),
  q("The Prophet's night journey is called:", "Hijrah", "Isra wal Miraj", "Jihad", "Dawah", "B", "Isra wal Miraj: night journey to Jerusalem and ascension."),
  q("Eid prayer consists of ___ rakats.", "2", "4", "6", "8", "A", "Eid prayer is 2 rakats."),
  q("The first muezzin of Islam was:", "Abu Bakr", "Bilal", "Umar", "Uthman", "B", "Bilal ibn Rabah was the first muezzin."),
  q("Salatul Janazah is prayer for:", "Rain", "Deceased", "Eid", "Travel", "B", "Janazah is funeral prayer."),
  q("Dawah means:", "Prayer", "Invitation to Islam", "Fasting", "Pilgrimage", "B", "Dawah: inviting others to Islam."),
  q("The Islamic term for charity is:", "Zakat", "Sadaqah", "Riba", "Gharar", "B", "Sadaqah is voluntary charity."),
  q("The treaty of Hudaybiyyah was in:", "3 AH", "6 AH", "8 AH", "10 AH", "B", "Treaty of Hudaybiyyah in 6 AH."),
  q("The first mosque in Islam was built in:", "Makkah", "Madinah", "Jerusalem", "Quba", "D", "Quba Mosque was the first."),
  q("Sawm (fasting) is obligatory in:", "Shawwal", "Muharram", "Ramadan", "Dhul Qadah", "C", "Fasting is obligatory in Ramadan."),
  q("Nikah is the Islamic:", "Divorce", "Marriage contract", "Prayer", "Burial", "B", "Nikah is Islamic marriage."),
  q("The four schools of Islamic law are called:", "Sects", "Madhabs", "Sunnahs", "Ijmah", "B", "Four madhabs: Hanafi, Maliki, Shafi'i, Hanbali."),
  q("Istikhara is prayer for:", "Rain", "Guidance", "Forgiveness", "Protection", "B", "Istikhara: prayer for guidance in decisions."),
];

const CRS_Q = [
  q("The first book of the Bible is:", "Exodus", "Genesis", "Leviticus", "Deuteronomy", "B", "Genesis is the first book of the Bible."),
  q("God created the world in ___ days.", "5", "6", "7", "10", "B", "Creation completed in 6 days; 7th day rest."),
  q("The first man created was:", "Noah", "Adam", "Abraham", "Moses", "B", "Adam was the first man created by God."),
  q("Cain killed his brother:", "Abel", "Seth", "Noah", "Enoch", "A", "Cain killed Abel out of jealousy."),
  q("Noah built an ark to survive the:", "Earthquake", "Flood", "Famine", "Plague", "B", "Noah built the ark for the great flood."),
  q("The Ten Commandments were given to:", "Abraham", "Isaac", "Moses", "Joshua", "C", "Moses received the Ten Commandments on Sinai."),
  q("The first miracle of Jesus was:", "Healing a blind man", "Water to wine", "Feeding 5,000", "Walking on water", "B", "First miracle: turning water to wine at Cana."),
  q("Jesus was born in:", "Nazareth", "Jerusalem", "Bethlehem", "Capernaum", "C", "Jesus was born in Bethlehem."),
  q("The number of books in the Bible is:", "27", "39", "66", "73", "C", "Protestant Bible has 66 books."),
  q("The Psalm 23 begins with 'The Lord is my ___':", "Rock", "Shepherd", "Light", "Fortress", "B", "Psalm 23: The Lord is my Shepherd."),
  q("The Israelites crossed the ___ Sea.", "Dead", "Red", "Mediterranean", "Galilee", "B", "Moses parted the Red Sea for Israel's escape."),
  q("David defeated Goliath with a:", "Sword", "Sling", "Shield", "Spear", "B", "David killed Goliath using a sling and stone."),
  q("The birthright of Esau was bought by Jacob with:", "Gold", "Stew", "Land", "Cattle", "B", "Esau sold his birthright for a bowl of stew."),
  q("The angel who announced Jesus' birth was:", "Michael", "Gabriel", "Raphael", "Uriel", "B", "Gabriel announced Jesus' birth to Mary."),
  q("The Last Supper was a ___ meal.", "Wedding", "Passover", "Harvest", "Birthday", "B", "Last Supper was a Passover meal with disciples."),
  q("Judas betrayed Jesus for ___ pieces of silver.", "20", "30", "40", "50", "B", "Judas betrayed Jesus for 30 silver pieces."),
  q("Paul was converted on the road to:", "Rome", "Damascus", "Jerusalem", "Antioch", "B", "Paul's conversion happened on the Damascus road."),
  q("The fruit of the Spirit includes:", "Pride", "Love", "Greed", "Anger", "B", "Love is a fruit of the Spirit (Galatians 5:22)."),
  q("The name 'Jesus' means:", "King", "Savior", "Teacher", "Prophet", "B", "Jesus (Yeshua) means 'the Lord saves'."),
  q("Solomon was known for his:", "Strength", "Wisdom", "Wealth", "Bravery", "B", "Solomon asked God for wisdom."),
  q("Gethsemane was a:", "Temple", "Garden", "Mountain", "River", "B", "Gethsemane was a garden where Jesus prayed."),
  q("The Great Commission commands disciples to:", "Build churches", "Make disciples of all nations", "Write books", "Pray only", "B", "Great Commission: go and make disciples."),
  q("Ruth was known for her:", "Loyalty", "Wealth", "Beauty", "Strength", "A", "Ruth showed loyalty to Naomi."),
  q("Pentecost celebrates the coming of the:", "Angels", "Holy Spirit", "Prophets", "Apostles", "B", "Pentecost: Holy Spirit descended on apostles."),
  q("The good Samaritan parable teaches:", "Prayer", "Love for neighbor", "Fasting", "Tithing", "B", "Parable teaches compassion for all people."),
  q("Moses' mother hid him in a:", "Cave", "Basket on Nile", "House", "Field", "B", "Baby Moses was hidden in a basket on the Nile."),
  q("The golden calf was made while Moses was on:", "Mount Sinai", "Mount Zion", "Mount Carmel", "Mount Tabor", "A", "Israelites made the golden calf at Sinai."),
  q("Elijah was taken to heaven in a:", "Cloud", "Chariot of fire", "Boat", "Whirlwind", "B", "Elijah ascended in a chariot of fire."),
  q("The parable of the prodigal son is about:", "Wealth", "Repentance and forgiveness", "Farming", "Building", "B", "Prodigal son: repentance and father's forgiveness."),
  q("John the Baptist baptized in the:", "Sea of Galilee", "River Jordan", "Nile River", "Dead Sea", "B", "John baptized in the Jordan River."),
  q("The beatitudes are found in:", "Psalms", "Sermon on the Mount", "Proverbs", "Exodus", "B", "Beatitudes are part of Jesus' Sermon on the Mount."),
  q("Jonah was swallowed by a:", "Whale", "Big fish", "Shark", "Serpent", "B", "Jonah was swallowed by a large fish."),
  q("The Israelites wandered in the desert for ___ years.", "20", "30", "40", "50", "C", "Israel wandered 40 years in the wilderness."),
  q("The birthright blessing was passed through:", "Isaac", "Ishmael", "Esau", "Jacob", "D", "Blessing passed through Jacob (Israel)."),
  q("Armageddon refers to:", "A mountain", "Place of final battle", "A river", "A city", "B", "Armageddon: final battle site in Revelation."),
  q("Thomas doubted Jesus' resurrection until he:", "Saw the tomb", "Saw and touched Jesus' wounds", "Heard others", "Read scripture", "B", "Doubting Thomas needed to see and touch."),
];

const COMM = [
  q("Commerce is defined as:", "Buying and selling only", "Trade and aids to trade", "Manufacturing", "Farming", "B", "Commerce = trade + activities facilitating trade."),
  q("Trade includes:", "Home trade only", "Foreign trade only", "Both home and foreign trade", "Neither", "C", "Trade encompasses both internal and external exchange."),
  q("A wholesaler buys from:", "Consumers", "Manufacturers", "Retailers", "Other wholesalers", "B", "Wholesalers purchase from manufacturers in bulk."),
  q("A retailer sells directly to:", "Manufacturers", "Wholesalers", "Consumers", "Importers", "C", "Retailers sell to final consumers."),
  q("The document listing goods shipped is:", "Invoice", "Bill of lading", "Receipt", "Cheque", "B", "Bill of lading lists shipped goods."),
  q("A cheque drawn by a bank on itself is:", "Personal cheque", "Bank draft", "Crossed cheque", "Post-dated", "B", "Bank draft is drawn by bank on itself."),
  q("Insurance is based on the principle of:", "Profit", "Indemnity", "Competition", "Monopoly", "B", "Indemnity: insurer compensates for loss."),
  q("Premium in insurance is the:", "Payout amount", "Regular payment for coverage", "Claim value", "Policy document", "B", "Premium is the cost of insurance coverage."),
  q("Advertising aims to:", "Reduce prices", "Promote products", "Limit supply", "Increase taxes", "B", "Advertising promotes goods/services to consumers."),
  q("Warehousing provides:", "Storage", "Transport", "Insurance", "Banking", "A", "Warehousing stores goods until needed."),
  q("The central bank is the ___ of last resort.", "Lender", "Borrower", "Guarantor", "Insurer", "A", "Central bank lends to commercial banks as last resort."),
  q("A sole proprietorship has ___ owner(s).", "One", "Two", "Many", "Unlimited", "A", "Sole proprietorship: single owner."),
  q("Partnership requires at least:", "1 person", "2 persons", "3 persons", "5 persons", "B", "Partnership: 2 to 20 persons."),
  q("A company limited by shares has ___ liability.", "Unlimited", "Limited to shares owned", "No liability", "Joint", "B", "Shareholders liable only for unpaid shares."),
  q("Co-operative societies are based on:", "Profit", "Self-help and mutual aid", "Competition", "Government control", "B", "Cooperatives: member-owned for mutual benefit."),
  q("The stock exchange trades in:", "Government bonds only", "Securities and shares", "Currency", "Commodities", "B", "Stock exchange trades securities/shares."),
  q("Export means selling goods:", "Within the country", "To foreign countries", "To government", "Online", "B", "Export: selling to other countries."),
  q("Import duty is a tax on:", "Exported goods", "Imported goods", "Local goods", "Services", "B", "Import duty: tax on goods brought into country."),
  q("A supermarket is a type of:", "Wholesaler", "Retailer", "Manufacturer", "Agent", "B", "Supermarket is a large self-service retailer."),
  q("Hire purchase transfers ownership after:", "First payment", "Final installment", "Signing contract", "Delivery", "B", "Ownership transfers after all installments paid."),
  q("Transportation adds ___ utility.", "Time", "Place", "Form", "Possession", "B", "Transport creates place utility by moving goods."),
  q("Communication in business includes:", "Only calls", "Phone, email, fax, letters", "Only letters", "Only email", "B", "Business communication uses multiple channels."),
  q("A prospectus invites the public to:", "Attend a meeting", "Buy shares", "Donate", "Vote", "B", "Prospectus invites share subscription."),
  q("Dividend is paid to:", "Employees", "Shareholders", "Managers", "Creditors", "B", "Dividend: profit distribution to shareholders."),
  q("Market research helps:", "Increase costs", "Understand consumer needs", "Reduce quality", "Limit choice", "B", "Market research identifies consumer preferences."),
  q("Branding differentiates:", "Prices", "Products from competitors", "Tax rates", "Employees", "B", "Branding makes a product distinctive."),
  q("A receipt is evidence of:", "Agreement", "Payment received", "Delivery", "Order", "B", "Receipt confirms payment has been made."),
  q("Bank overdraft allows:", "Free banking", "Withdrawing more than balance", "Foreign exchange", "Investment advice", "B", "Overdraft: withdraw beyond account balance."),
  q("Monopoly exists where there is ___ seller.", "One", "Two", "Many", "Few", "A", "Monopoly: single seller controls the market."),
  q("The Nigeria Stock Exchange is in:", "Abuja", "Lagos", "Kano", "Port Harcourt", "B", "NSE is headquartered in Lagos."),
];

const ACC = [
  q("Accounting is the process of recording:", "Only sales", "Financial transactions", "Employees", "Inventory", "B", "Accounting records financial transactions systematically."),
  q("The accounting equation is:", "Assets = Liabilities + Capital", "Assets = Capital - Liabilities", "Liabilities = Assets + Capital", "Capital = Assets + Liabilities", "A", "Assets = Liabilities + Owners' Equity."),
  q("Double entry bookkeeping records:", "One side only", "Both debit and credit", "Cash only", "Credit only", "B", "Double entry: every transaction has debit and credit."),
  q("A debit entry increases:", "Liability accounts", "Asset or expense accounts", "Income accounts", "Capital accounts", "B", "Debits increase assets and expenses."),
  q("A credit entry increases:", "Asset accounts", "Liability or income accounts", "Expense accounts", "Drawing accounts", "B", "Credits increase liabilities, income, and capital."),
  q("The ledger is a book of:", "Original entry", "Final entry", "Secondary entry", "Trial entry", "B", "Ledger is the principal book of accounts."),
  q("Trial balance checks:", "Profitability", "Arithmetical accuracy", "Cash position", "Asset value", "B", "Trial balance verifies debits = credits."),
  q("Profit and Loss account shows:", "Assets", "Revenue and expenses", "Liabilities", "Capital", "B", "P&L summarizes income and expenses over a period."),
  q("Balance sheet shows:", "Profit or loss", "Financial position", "Cash flow", "Budget", "B", "Balance sheet shows assets, liabilities, capital at a date."),
  q("Depreciation allocates cost of ___ over useful life.", "Inventory", "Fixed asset", "Revenue", "Expense", "B", "Depreciation spreads fixed asset cost over useful life."),
  q("Working capital =", "Current assets", "Current assets - Current liabilities", "Total assets - Total liabilities", "Fixed assets", "B", "Working capital = current assets - current liabilities."),
  q("Goodwill is an ___ asset.", "Current", "Intangible", "Liquid", "Fictitious", "B", "Goodwill is an intangible asset (non-physical)."),
  q("A creditor is a person who ___ money.", "Owes the business", "Is owed by the business", "Invests in business", "Manages the business", "B", "Creditor is owed money by the business."),
  q("A debtor is a person who ___ money.", "Owes the business", "Is owed by the business", "Lends to business", "Audits", "A", "Debtor owes money to the business."),
  q("Cash discount encourages:", "Bulk buying", "Prompt payment", "Credit sales", "Returns", "B", "Cash discount incentivizes early payment."),
  q("Trade discount is allowed on:", "List price", "Invoice price", "Cash price", "Net price", "A", "Trade discount is deducted from list/catalog price."),
  q("A suspense account is used to:", "Store cash", "Correct errors temporarily", "Calculate profit", "Record sales", "B", "Suspense account holds differences until corrected."),
  q("The petty cash book records:", "Large payments", "Small incidental expenses", "Bank deposits", "Credit sales", "B", "Petty cash handles minor expenses."),
  q("Bank reconciliation compares:", "Two banks", "Cash book and bank statement", "Income and expenses", "Assets and liabilities", "B", "Bank reconciliation matches records with bank's."),
  q("Capital expenditure benefits:", "Current period only", "More than one accounting period", "No period", "The owner only", "B", "Capital expenditure: long-term benefit (assets)."),
  q("Revenue expenditure is charged to:", "Balance sheet", "Profit and Loss account", "Cash book", "Capital account", "B", "Revenue expenditure: expensed in P&L."),
  q("Drawing reduces:", "Assets", "Capital", "Liabilities", "Expenses", "B", "Drawings reduce owner's capital."),
  q("Bad debt is an expense of:", "Cash sales", "Credit sales", "Purchases", "Returns", "B", "Bad debt: credit sales that become uncollectible."),
  q("Closing stock is valued at:", "Cost price", "Market price", "Lower of cost or net realizable value", "Selling price", "C", "Stock valued at lower of cost/NRV."),
  q("Straight line depreciation charges ___ amount yearly.", "Increasing", "Decreasing", "Equal", "Variable", "C", "Straight line: equal annual depreciation."),
  q("A journal entry for cash sales debits:", "Sales account", "Cash account", "Purchases account", "Capital account", "B", "Dr Cash; Cr Sales."),
  q("A purchase return is recorded in:", "Purchase journal", "Returns inwards journal", "Returns outwards journal", "Cash book", "C", "Returns outwards: goods returned to suppliers."),
  q("A sales return is recorded in:", "Sales journal", "Returns inwards journal", "Returns outwards journal", "Ledger", "B", "Returns inwards: goods returned by customers."),
  q("Double entry for paying rent is:", "Dr Rent, Cr Cash", "Dr Cash, Cr Rent", "Dr Rent, Cr Capital", "Dr Capital, Cr Rent", "A", "Rent is an expense: debit expense, credit cash."),
  q("Accrual accounting records revenue when:", "Cash received", "Earned regardless of cash", "Invoice sent", "Goods delivered", "B", "Accrual: revenue when earned, not when cash received."),
  q("Prepaid expense is a ___ in balance sheet.", "Liability", "Current asset", "Fixed asset", "Capital", "B", "Prepaid expense: asset (benefit yet to be consumed)."),
  q("Accrued expense is a ___ in balance sheet.", "Current asset", "Current liability", "Fixed asset", "Revenue", "B", "Accrued expense: liability (expense incurred but unpaid)."),
  q("The accounting period concept divides life into:", "Daily", "Monthly", "Annual periods", "Decades", "C", "Accounting period: usually one year."),
  q("Going concern assumes business will:", "Close soon", "Continue indefinitely", "Be sold", "Merge", "B", "Going concern: business will continue operating."),
  q("Consistency concept requires:", "Same methods each period", "Different methods", "No accounting", "Cash only", "A", "Consistency: use same accounting methods year to year."),
  q("Prudence concept means:", "Overstate profits", "Understate losses", "Be cautious, anticipate losses", "No estimates", "C", "Prudence: not overstate assets/profits."),
];

const AGRIC = [
  q("Agriculture is the production of:", "Only crops", "Crops and livestock", "Only livestock", "Manufactured goods", "B", "Agriculture: crop cultivation and animal rearing."),
  q("The main food crop in Nigeria is:", "Maize", "Rice", "Cassava", "Yam", "C", "Cassava is Nigeria's main food staple."),
  q("A cash crop is grown for:", "Home consumption", "Sale for profit", "Animal feed", "Decoration", "B", "Cash crops: sold for income (cocoa, cotton, palm oil)."),
  q("Fertilizers enrich the:", "Water supply", "Soil fertility", "Air quality", "Sunlight", "B", "Fertilizers provide nutrients to the soil."),
  q("Irrigation supplies water to crops:", "Naturally", "Artificially", "By rainfall only", "By rivers only", "B", "Irrigation: artificial water application."),
  q("A tractor is an example of:", "Hand tool", "Farm machinery", "Simple implement", "Harvesting tool", "B", "Tractor is mechanized farm machinery."),
  q("Poultry farming involves rearing:", "Sheep", "Chickens", "Cattle", "Fish", "B", "Poultry: domestic birds (chickens, ducks, turkeys)."),
  q("Fish farming takes place in:", "Oceans", "Ponds/tanks", "Rivers", "Lakes", "B", "Fish farming in ponds, tanks, or cages."),
  q("Soil erosion removes:", "Topsoil", "Subsoil", "Bedrock", "Rocks", "A", "Erosion removes the fertile topsoil layer."),
  q("Crop rotation helps:", "Increase pests", "Maintain soil fertility", "Reduce yield", "Increase weeds", "B", "Rotating crops prevents nutrient depletion."),
  q("A nursery is used for:", "Raising young plants", "Storing harvest", "Processing crops", "Keeping animals", "A", "Nursery nurtures seedlings before transplanting."),
  q("Mulching covers soil with:", "Water", "Organic material", "Plastic only", "Rocks", "B", "Mulch: straw, leaves, or plastic to conserve moisture."),
  q("A weed is a plant growing:", "Intentionally", "Where it is unwanted", "In the garden", "In the farm", "B", "Weed: plant growing where it's not wanted."),
  q("Herbicides control:", "Insects", "Weeds", "Fungi", "Bacteria", "B", "Herbicides kill or inhibit weeds."),
  q("Ruminant animals have ___ stomachs.", "One", "Two", "Three", "Four", "D", "Ruminants (cattle, sheep) have four stomach chambers."),
  q("The gestation period of cattle is about:", "3 months", "6 months", "9 months", "12 months", "C", "Cattle gestation ~9 months."),
  q("Apiculture is the rearing of:", "Fish", "Bees", "Snails", "Silkworms", "B", "Apiculture: beekeeping for honey and wax."),
  q("Agro-processing involves:", "Farming only", "Transforming farm produce", "Distribution only", "Storage only", "B", "Agro-processing adds value to raw agricultural products."),
  q("The extension officer ___ to farmers.", "Sells equipment", "Gives advice", "Buys produce", "Builds roads", "B", "Extension officers provide agricultural advisory services."),
  q("Green manure involves:", "Chemical spray", "Plowing green plants into soil", "Watering crops", "Harvesting", "B", "Green manure: growing then plowing under plants."),
  q("A silo is used for storing:", "Water", "Grains", "Animals", "Fertilizers", "B", "Silos store bulk grains."),
  q("The most common soil type for farming is:", "Sandy", "Clay", "Loam", "Laterite", "C", "Loam is best: balanced sand/silt/clay."),
  q("Photosynthesis in crops produces:", "Carbon dioxide", "Oxygen and glucose", "Nitrogen", "Water", "B", "Photosynthesis: CO₂ + H₂O → glucose + O₂."),
  q("Ranching involves ___ livestock.", "Rearing free-range", "Rearing in enclosed fields", "Zero grazing", "Household keeping", "B", "Ranching: raising livestock in fenced areas."),
  q("The rainy season in southern Nigeria is:", "March-October", "November-February", "All year", "January-June", "A", "Southern Nigeria: long rainy season March-October."),
  q("A compost heap consists of:", "Chemicals", "Decayed organic matter", "Plastic waste", "Metal scraps", "B", "Compost: decomposed organic material for fertilizer."),
  q("Selective breeding aims to:", "Reduce size", "Improve desired traits", "Increase diseases", "Reduce productivity", "B", "Selective breeding: breeding for desirable characteristics."),
  q("Pasture is land used for:", "Crop farming", "Grazing livestock", "Building", "Forestry", "B", "Pasture: grazing land for animals."),
  q("The Nigerian government body overseeing agriculture is:", "CBN", "FMARD", "NCC", "NPA", "B", "FMARD = Federal Ministry of Agriculture and Rural Development."),
  q("Horticulture involves growing:", "Field crops only", "Vegetables, fruits, flowers", "Forest trees", "Only grains", "B", "Horticulture: intensive cultivation of garden crops."),
];

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });
  try {
    const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
    const ALL = [
      ...LIT.map(q => ({ ...q, subject: 'literature' })),
      ...ECON.map(q => ({ ...q, subject: 'economics' })),
      ...GEO.map(q => ({ ...q, subject: 'geography' })),
      ...IRS_Q.map(q => ({ ...q, subject: 'irs' })),
      ...CRS_Q.map(q => ({ ...q, subject: 'crs' })),
      ...COMM.map(q => ({ ...q, subject: 'commerce' })),
      ...ACC.map(q => ({ ...q, subject: 'accounting' })),
      ...AGRIC.map(q => ({ ...q, subject: 'agricultural_science' })),
    ];
    let inserted = 0; let skipped = 0;
    const bySubject: Record<string, number> = {};
    for (const q of ALL) {
      const { data: existing } = await supabase.from('jamb_questions').select('id').eq('question', q.question).maybeSingle();
      if (existing) { skipped++; continue; }
      await supabase.from('jamb_questions').insert({
        subject: q.subject, question: q.question,
        option_a: q.option_a, option_b: q.option_b, option_c: q.option_c, option_d: q.option_d,
        correct_answer: q.correct_answer, explanation: q.explanation, year: 2025,
      });
      inserted++; bySubject[q.subject] = (bySubject[q.subject] || 0) + 1;
    }
    return new Response(JSON.stringify({
      success: true, message: `Seeded ${inserted} new, skipped ${skipped}`,
      inserted, skipped, by_subject: bySubject,
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
