import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

type SeedQuestion = { question: string; option_a: string; option_b: string; option_c: string; option_d: string; correct_answer: string; explanation: string };
function q(s: string, a: string, b: string, c: string, d: string, ca: string, e: string): SeedQuestion {
  return { question: s, option_a: a, option_b: b, option_c: c, option_d: d, correct_answer: ca, explanation: e };
}

const E = [
  q("Choose the correct spelling:", "Accommodate", "Acomodate", "Accomodate", "Acommodate", "A", "Accommodate has two c's and two m's."),
  q("The word 'benevolent' means:", "Kind-hearted", "Angry", "Weak", "Fast", "A", "Benevolent means well-meaning, kindly."),
  q("Choose the antonym of 'ancient':", "Old", "Modern", "Rare", "Broken", "B", "Modern is the opposite of ancient."),
  q("The idiom 'once in a blue moon' means:", "Daily", "Very rarely", "Always", "Never", "B", "It means something that happens very infrequently."),
  q("The word 'pragmatic' means:", "Idealistic", "Practical", "Emotional", "Lazy", "B", "Pragmatic means dealing with things practically."),
  q("Identify the figure of speech: 'The wind whispered through the trees.'", "Simile", "Metaphor", "Personification", "Hyperbole", "C", "Wind is given human quality of whispering."),
  q("The word 'ambiguous' means:", "Clear", "Having multiple meanings", "Short", "Happy", "B", "Ambiguous means open to more than one interpretation."),
  q("Choose the correct preposition: 'He is afraid ___ darkness.'", "From", "Of", "To", "At", "B", "Correct: afraid of darkness."),
  q("A synonym for 'generous' is:", "Selfish", "Bountiful", "Greedy", "Mean", "B", "Bountiful means giving freely."),
  q("The correct plural of 'sheep' is:", "Sheeps", "Sheep", "Sheepes", "Sheep's", "B", "Sheep is both singular and plural."),
  q("The word 'elaborate' (verb) stresses on:", "ELaborate", "eLABorate", "elaboRATE", "ELABorate", "B", "As a verb, stress is on the second syllable."),
  q("'Brevity is the soul of wit' is from:", "Shakespeare", "Chaucer", "Milton", "Achebe", "A", "This quote is from Shakespeare's Hamlet."),
  q("The word 'candid' means:", "Secretive", "Frank", "Dishonest", "Confused", "B", "Candid means truthful and straightforward."),
  q("Which is a complex sentence?", "I ate and left", "Although tired, he continued", "She runs", "Come here", "B", "A complex sentence has a dependent clause."),
  q("The word 'ephemeral' means:", "Eternal", "Short-lived", "Strong", "Heavy", "B", "Ephemeral means lasting a very short time."),
  q("The literary term 'denouement' refers to:", "Beginning", "Climax", "Resolution", "Conflict", "C", "Denouement is the final resolution of a story."),
  q("Fill the blank: 'Neither the teacher ___ the students was present.'", "Or", "Nor", "And", "But", "B", "Neither...nor is the correct pair."),
  q("The word 'voracious' means:", "Hungry", "Honest", "Weak", "Quiet", "A", "Voracious means having a huge appetite."),
  q("Choose the correctly stressed word:", "PHOtography", "phoTOgraphy", "phoTOGraphy", "photograPHY", "B", "Photography stresses the second syllable."),
  q("An epilogue is:", "A preface", "A concluding section", "A chapter", "An index", "B", "Epilogue comes at the end of a literary work."),
  q("The word 'tenacious' means:", "Weak", "Determined", "Confused", "Gentle", "B", "Tenacious means holding firmly; persistent."),
  q("The sentence 'If I were you' uses:", "Indicative mood", "Imperative mood", "Subjunctive mood", "Interrogative mood", "C", "The subjunctive expresses hypothetical situations."),
  q("A synonym for 'hinder' is:", "Help", "Obstruct", "Speed", "Create", "B", "Hinder means to create obstacles."),
  q("The word 'conspicuous' means:", "Hidden", "Easily seen", "Quiet", "Normal", "B", "Conspicuous means standing out; easily noticeable."),
  q("Oxymoron combines:", "Similar ideas", "Contradictory terms", "Rhyming words", "Short phrases", "B", "Oxymoron like 'deafening silence' combines opposites."),
  q("The word 'resilient' means:", "Weak", "Able to recover quickly", "Angry", "Slow", "B", "Resilient means able to withstand or recover from difficulty."),
  q("Choose the correct article: '___ honest man always tells truth.'", "A", "An", "The", "None", "B", "'An' is used before a silent 'h' sound."),
  q("A synonym for 'abundant' is:", "Scarce", "Plentiful", "Empty", "Small", "B", "Abundant means existing in large quantities."),
  q("The word 'eloquent' describes:", "Confused speech", "Fluent and persuasive speech", "Angry speech", "Quiet speech", "B", "Eloquent means fluent or persuasive in speaking."),
  q("A metaphor is a comparison without using:", "Nouns", "Like or as", "Adjectives", "Verbs", "B", "Metaphors compare directly without 'like' or 'as'."),
  q("The word 'meticulous' means:", "Careless", "Very careful", "Fast", "Bored", "B", "Meticulous means showing great attention to detail."),
  q("Which word has the /θ/ sound?", "This", "Thin", "The", "That", "B", "/θ/ is the voiceless 'th' as in 'thin'."),
  q("'To cry wolf' means:", "To call for help when not needed", "To be brave", "To be sad", "To sing", "A", "Crying wolf means raising a false alarm."),
  q("The word 'compelling' means:", "Weak", "Unconvincing", "Forcefully persuasive", "Boring", "C", "Compelling means evoking interest or attention irresistibly."),
  q("An interrogative sentence asks:", "A command", "A question", "A statement", "An exclamation", "B", "Interrogative sentences ask questions."),
  q("The word 'adept' means:", "Clumsy", "Skilled", "Slow", "Lazy", "B", "Adept means very skilled or proficient."),
  q("Pun intended is a form of:", "Wordplay", "Grammar", "Punctuation", "Syntax", "A", "A pun is a form of wordplay."),
  q("The word 'taciturn' means:", "Talkative", "Reserved in speech", "Angry", "Happy", "B", "Taciturn means saying very little."),
  q("Choose the correct: 'Each of the students ___ assigned a task.'", "Were", "Was", "Are", "Have", "B", "'Each' takes a singular verb."),
  q("The word 'frugal' means:", "Wasteful", "Economical", "Generous", "Lavish", "B", "Frugal means sparing or economical with money or food."),
  q("A limerick is a type of:", "Poem", "Novel", "Drama", "Essay", "A", "A limerick is a humorous five-line poem."),
  q("The word 'zealous' means:", "Apathetic", "Enthusiastic", "Lazy", "Slow", "B", "Zealous means having great energy or enthusiasm."),
  q("'He ran quickly' - 'quickly' is:", "Noun", "Adjective", "Adverb", "Verb", "C", "Quickly modifies the verb 'ran'."),
  q("The word 'pensive' means:", "Happy", "Thoughtful", "Angry", "Excited", "B", "Pensive means engaged in deep thought."),
  q("Alliteration repeats:", "Vowel sounds", "Initial consonant sounds", "End sounds", "Words", "B", "Alliteration repeats initial consonant sounds."),
  q("The word 'docile' means:", "Stubborn", "Submissive", "Wild", "Loud", "B", "Docile means ready to accept control or instruction."),
  q("Which is a compound word?", "Beautiful", "Sunflower", "Running", "Quickly", "B", "Sunflower is made of two words: sun + flower."),
  q("The word 'jubilant' means:", "Sad", "Triumphantly happy", "Tired", "Bored", "B", "Jubilant means feeling great happiness and triumph."),
  q("Onomatopoeia is a word that:", "Describes an action", "Imitates a sound", "Shows possession", "Connects ideas", "B", "Onomatopoeia imitates natural sounds like 'buzz'."),
  q("The word 'scrutinize' means:", "Ignore", "Examine closely", "Praise", "Destroy", "B", "Scrutinize means to examine or inspect closely."),
  q("A palindrome reads:", "The same forward and backward", "Only forward", "Only backward", "Upside down", "A", "Palindrome like 'radar' reads the same both ways."),
  q("The word 'wary' means:", "Careless", "Cautious", "Sleepy", "Angry", "B", "Wary means feeling or showing caution."),
  q("Correct: 'The data ___ collected.'", "Is", "Are", "Was", "Both A and B", "D", "Data can be singular or plural in modern usage."),
  q("Hyperbole is:", "Understatement", "Exaggeration", "Comparison", "Repetition", "B", "Hyperbole is extreme exaggeration for effect."),
  q("The word 'nonchalant' means:", "Worried", "Calmly casual", "Excited", "Angry", "B", "Nonchalant means feeling calm and relaxed."),
  q("A biography is written by:", "The subject", "Someone else", "A publisher", "A historian", "B", "A biography is about someone, written by someone else."),
  q("The word 'pristine' means:", "Dirty", "In original condition", "Broken", "Empty", "B", "Pristine means in its original, unspoiled condition."),
  q("Homophones are words that:", "Sound the same", "Look the same", "Mean the same", "Are opposite", "A", "Homophones sound alike but differ in meaning/spelling."),
  q("The word 'stoic' means:", "Emotional", "Enduring without complaint", "Fearful", "Excited", "B", "Stoic means enduring pain without showing feelings."),
  q("Correct: 'The jury ___ divided in their opinion.'", "Is", "Was", "Were", "Has", "C", "Collective noun 'jury' takes plural verb when members act individually."),
  q("The word 'intrepid' means:", "Fearful", "Fearless", "Tired", "Bored", "B", "Intrepid means fearless and adventurous."),
  q("Aside in drama is:", "A speech heard by all", "Words for the audience only", "A song", "A dance", "B", "An aside reveals private thoughts to the audience."),
  q("The word 'lethargic' means:", "Energetic", "Sluggish", "Excited", "Happy", "B", "Lethargic means affected by lack of energy."),
  q("A suffix is added to the:", "Beginning", "End", "Middle", "Anywhere", "B", "A suffix is added at the end of a word."),
  q("The word 'omnipotent' means:", "All-knowing", "All-powerful", "Present everywhere", "Invisible", "B", "Omnipotent means having unlimited power."),
  q("Author's purpose in a persuasive text is:", "To inform", "To entertain", "To convince", "To describe", "C", "Persuasive texts aim to convince the reader."),
  q("The word 'profound' means:", "Shallow", "Very deep", "Simple", "Short", "B", "Profound means very great or intense; deep."),
  q("Dialect is a form of language specific to:", "A region", "A school", "A book", "A time", "A", "Dialects are regional varieties of a language."),
  q("The word 'empathy' means:", "Feeling sorry", "Understanding others' feelings", "Being angry", "Being happy", "B", "Empathy is the ability to understand others' emotions."),
  q("Correct: 'The news ___ good today.'", "Are", "Is", "Were", "Have", "B", "'News' is a singular uncountable noun."),
  q("The word 'arduous' means:", "Easy", "Difficult", "Fast", "Soft", "B", "Arduous means involving great effort; difficult."),
  q("Irony involves:", "Direct meaning", "Opposite of literal meaning", "Exaggeration", "Rhyme", "B", "Irony expresses meaning using language that signifies the opposite."),
  q("The word 'capricious' means:", "Predictable", "Given to sudden changes", "Steady", "Calm", "B", "Capricious means changing mood suddenly."),
  q("A précis is:", "A summary", "A long essay", "A poem", "A play", "A", "A précis is a concise summary of a text."),
  q("The word 'diligent' means:", "Lazy", "Hardworking", "Careless", "Slow", "B", "Diligent means showing careful persistent effort."),
  q("Connotation is the:", "Dictionary meaning", "Emotional association", "Grammar", "Spelling", "B", "Connotation is the implied cultural/emotional meaning."),
  q("The word 'whimsical' means:", "Serious", "Playfully quirky", "Angry", "Boring", "B", "Whimsical means playfully unusual or fanciful."),
  q("Past perfect tense uses:", "Had + past participle", "Has + past", "Was + ing", "Will have", "A", "Past perfect = had + past participle."),
  q("The word 'vivid' means:", "Dull", "Bright and clear", "Dark", "Quiet", "B", "Vivid means producing powerful images in the mind."),
  q("Euphemism replaces:", "A harsh word with milder one", "A noun with pronoun", "Question to command", "Plural to singular", "A", "Euphemism softens harsh reality: 'passed away' for 'died'."),
  q("The word 'affluent' means:", "Poor", "Wealthy", "Average", "Anxious", "B", "Affluent means having great wealth."),
  q("An acronym is formed from:", "First letters of words", "Last letters", "Random letters", "Numbers", "A", "Acronym uses initial letters: NATO, AIDS."),
  q("The word 'courteous' means:", "Rude", "Polite", "Loud", "Fast", "B", "Courteous means polite and respectful."),
  q("Subject-verb agreement means:", "Subject and verb must match in number", "Subject must be first", "Verb must be action", "Subject is plural", "A", "Singular subject needs singular verb."),
  q("The word 'industrious' means:", "Lazy", "Hardworking", "Slow", "Quiet", "B", "Industrious means diligent and hardworking."),
  q("Flashback in literature:", "Goes forward in time", "Goes back in time", "Stays present", "Skips time", "B", "Flashback interrupts the narrative to show past events."),
  q("The word 'cognizant' means:", "Unaware", "Aware", "Confused", "Asleep", "B", "Cognizant means having knowledge or awareness."),
  q("Active voice: 'The boy kicked the ball.' Passive is:", "The ball was kicked by the boy", "The boy was kicked", "The ball kicks", "Kicked the boy", "A", "Passive: object becomes subject + be + past participle."),
  q("The word 'empirical' means:", "Based on theory", "Based on observation", "Imaginary", "Ancient", "B", "Empirical means based on observation or experience."),
  q("Climax in a story is:", "The beginning", "The turning point", "The end", "The introduction", "B", "Climax is the highest point of tension in a narrative."),
  q("The word 'salient' means:", "Hidden", "Most noticeable", "Salty", "Weak", "B", "Salient means most noticeable or important."),
  q("Phonetics is the study of:", "Word meanings", "Speech sounds", "Sentence structure", "Punctuation", "B", "Phonetics studies the sounds of human speech."),
  q("The word 'vivacious' means:", "Lifeless", "Lively and animated", "Quiet", "Sad", "B", "Vivacious means attractively energetic and animated."),
  q("Semicolon (;) indicates:", "A pause stronger than comma", "End of sentence", "Question", "Possession", "A", "Semicolons join related independent clauses."),
  q("The word 'reciprocal' means:", "One-sided", "Mutual", "Single", "Broken", "B", "Reciprocal means given, felt, or done in return."),
];

const M = [
  q("What is 15% of 200?", "15", "30", "20", "25", "B", "15% of 200 = 0.15 × 200 = 30."),
  q("Find the next number: 2, 6, 18, 54, ?", "108", "162", "72", "96", "B", "Multiply by 3 each time: 54 × 3 = 162."),
  q("The sum of the first 10 positive integers is:", "45", "50", "55", "60", "C", "Sum = n(n+1)/2 = 10×11/2 = 55."),
  q("If x/3 = 5, then x =", "8", "10", "15", "12", "C", "x = 3 × 5 = 15."),
  q("Convert 3/5 to decimal:", "0.35", "0.5", "0.6", "0.65", "C", "3 divided by 5 equals 0.6."),
  q("The square root of 144 is:", "12", "14", "10", "16", "A", "12 × 12 = 144, so √144 = 12."),
  q("How many sides does a hexagon have?", "4", "5", "6", "8", "C", "A hexagon has six sides."),
  q("Solve: 2(x + 3) = 12", "x = 2", "x = 3", "x = 4", "x = 6", "B", "2(x+3)=12; x+3=6; x=3."),
  q("The LCM of 6 and 8 is:", "14", "24", "48", "12", "B", "LCM of 6 and 8 is 24."),
  q("Write 0.75 as a fraction:", "1/4", "1/2", "3/4", "2/3", "C", "0.75 = 75/100 = 3/4."),
  q("The mean of 5, 10, 15, 20 is:", "10", "12.5", "15", "20", "B", "Mean = (5+10+15+20)/4 = 50/4 = 12.5."),
  q("If a = 2 and b = 3, find a² + b²:", "4", "9", "13", "25", "C", "2² + 3² = 4 + 9 = 13."),
  q("1 kilometer = ___ meters", "100", "1000", "10000", "10", "B", "1 km = 1000 meters."),
  q("What is the probability of rolling an even number on a die?", "1/2", "1/3", "1/6", "2/3", "A", "3 even numbers out of 6 = 3/6 = 1/2."),
  q("Simplify: 12 - 3 × 2", "9", "6", "18", "15", "B", "BODMAS: multiplication first: 3×2=6; 12-6=6."),
  q("What is 2/3 + 1/6?", "1/2", "1/3", "5/6", "3/9", "C", "2/3 = 4/6; 4/6 + 1/6 = 5/6."),
  q("The perimeter of a square of side 5 cm is:", "10 cm", "15 cm", "20 cm", "25 cm", "C", "Perimeter = 4 × 5 = 20 cm."),
  q("If 5 = 2x - 1, find x:", "1", "2", "3", "4", "C", "2x - 1 = 5; 2x = 6; x = 3."),
  q("How many degrees in a right angle?", "45°", "90°", "180°", "360°", "B", "A right angle is exactly 90°."),
  q("The reciprocal of 4 is:", "4", "1/4", "-4", "0.4", "B", "Reciprocal of 4 is 1/4."),
  q("What is the next prime after 7?", "8", "9", "10", "11", "D", "11 is the next prime number after 7."),
  q("If y = 2x + 1 and x = 3, then y =", "5", "6", "7", "8", "C", "y = 2(3) + 1 = 6 + 1 = 7."),
  q("The volume of a cube of side 3 m is:", "9 m³", "18 m³", "27 m³", "30 m³", "C", "Volume = s³ = 3³ = 27 m³."),
  q("What is 20% of 500?", "50", "100", "150", "200", "B", "20% of 500 = 0.2 × 500 = 100."),
  q("The GCF of 12 and 18 is:", "3", "4", "6", "9", "C", "Greatest common factor of 12 and 18 is 6."),
  q("If 3x = 27, then x =", "3", "6", "9", "12", "C", "3x = 27; x = 9."),
  q("1 hectare = ___ square meters", "100", "1000", "10000", "100000", "C", "1 hectare = 10,000 m²."),
  q("The diameter of a circle with radius 7 cm is:", "3.5 cm", "7 cm", "14 cm", "21 cm", "C", "Diameter = 2 × radius = 14 cm."),
  q("What is i² in complex numbers?", "1", "-1", "i", "-i", "B", "i² = -1."),
  q("Express 2:5 as a fraction:", "2/3", "2/5", "3/5", "5/2", "B", "2:5 means 2/5."),
  q("The product of 7 and 8 is:", "48", "54", "56", "64", "C", "7 × 8 = 56."),
  q("What type of angle is 120°?", "Acute", "Right", "Obtuse", "Reflex", "C", "120° is obtuse (between 90° and 180°)."),
  q("Solve: x² = 49", "x = 7", "x = ±7", "x = -7", "x = 49", "B", "x² = 49 has two solutions: x = ±7."),
  q("The base of binary number system is:", "2", "8", "10", "16", "A", "Binary system uses base 2."),
  q("How many vertices does a cube have?", "4", "6", "8", "12", "C", "A cube has 8 vertices (corners)."),
  q("Which is a proper fraction?", "5/3", "3/4", "7/5", "9/8", "B", "Proper fraction has numerator < denominator: 3/4."),
  q("The value of 2³ is:", "4", "5", "6", "8", "D", "2³ = 2 × 2 × 2 = 8."),
  q("If 6 men can do a job in 4 days, one man takes:", "4 days", "6 days", "12 days", "24 days", "D", "One man takes 6 × 4 = 24 days."),
  q("The supplement of 60° is:", "30°", "60°", "120°", "300°", "C", "Supplementary angles sum to 180°: 180-60=120."),
  q("Round 3.75 to 1 decimal:", "3.7", "3.8", "4.0", "3.5", "B", "3.75 → 3.8 (round up from 5)."),
  q("What is the mode of 1, 2, 2, 3, 4?", "1", "2", "3", "4", "B", "Mode is the most frequent value: 2."),
  q("If 2x - 5 = 7, find x:", "4", "5", "6", "7", "C", "2x = 12; x = 6."),
  q("The number of edges on a cuboid is:", "6", "8", "10", "12", "D", "A cuboid has 12 edges."),
  q("Evaluate: 2 + 3 × 4", "14", "20", "24", "34", "A", "BODMAS: 3×4=12; 2+12=14."),
  q("1 liter = ___ milliliters", "10", "100", "1000", "10000", "C", "1 L = 1000 mL."),
  q("The complement of 35° is:", "35°", "55°", "145°", "325°", "B", "Complementary sum to 90°: 90-35=55."),
  q("Simplify: 4² - 2²", "2", "4", "12", "16", "C", "16 - 4 = 12."),
  q("How many zeros in 1 million?", "4", "5", "6", "7", "C", "1,000,000 has 6 zeros."),
  q("If 3 : x = 6 : 8, find x:", "2", "3", "4", "5", "C", "3/x = 6/8; 6x = 24; x = 4."),
  q("The sum of 10 and 15 divided by 5 is:", "3", "5", "7", "25", "B", "(10+15)/5 = 25/5 = 5."),
  q("What is the difference between 100 and 37?", "63", "73", "137", "67", "A", "100 - 37 = 63."),
  q("The place value of 7 in 5,678 is:", "7", "70", "700", "7,000", "B", "7 is in the tens place: 70."),
  q("How many grams in 2 kg?", "20 g", "200 g", "2000 g", "20,000 g", "C", "2 kg = 2 × 1000 = 2000 g."),
  q("If 4x = 36, find x:", "4", "6", "8", "9", "D", "x = 36/4 = 9."),
  q("The average of 3, 7, and 11 is:", "5", "6", "7", "8", "C", "(3+7+11)/3 = 21/3 = 7."),
  q("What is 10% of 50?", "2", "5", "10", "20", "B", "10% of 50 = 5."),
  q("The numeral for sixty thousand is:", "600", "6,000", "60,000", "600,000", "C", "60,000 = sixty thousand."),
  q("Simplify: 8 + 12 ÷ 4", "5", "8", "11", "20", "C", "12÷4=3; 8+3=11."),
  q("How many faces on a triangular prism?", "3", "4", "5", "6", "C", "A triangular prism has 5 faces."),
  q("The value of 10² is:", "10", "20", "100", "1000", "C", "10² = 10 × 10 = 100."),
  q("If a:b = 2:3 and b = 9, find a:", "2", "3", "6", "9", "C", "a/9 = 2/3; a = 6."),
  q("1 tonne = ___ kg", "100", "500", "1000", "2000", "C", "1 tonne = 1000 kg."),
  q("The smallest odd prime is:", "1", "2", "3", "5", "C", "3 is the smallest odd prime number."),
  q("If today is Monday, what day is day after tomorrow?", "Tuesday", "Wednesday", "Thursday", "Friday", "B", "Tuesday tomorrow; Wednesday day after."),
  q("The sum of angles in a quadrilateral is:", "180°", "270°", "360°", "450°", "C", "(n-2)×180 = 2×180 = 360°."),
  q("Evaluate: 3! (3 factorial)", "3", "6", "9", "12", "B", "3! = 3×2×1 = 6."),
  q("If 6x = 42, find x:", "6", "7", "8", "9", "B", "x = 42/6 = 7."),
  q("What is 0.1 as a fraction?", "1/10", "1/5", "1/2", "1/100", "A", "0.1 = 1/10."),
  q("How many minutes in 3 hours?", "120", "150", "180", "210", "C", "3 × 60 = 180 minutes."),
  q("The ordinal for 9 is:", "Nineth", "Ninth", "Nineth", "Nineteenth", "B", "9th = ninth."),
  q("√36 + √16 =", "10", "12", "14", "16", "A", "6 + 4 = 10."),
  q("What is 1/2 of 50?", "15", "20", "25", "30", "C", "50/2 = 25."),
  q("The next in sequence: 1, 1, 2, 3, 5, 8, ?", "10", "11", "12", "13", "D", "Fibonacci: 5+8 = 13."),
  q("If a pen costs ₦30, how many for ₦150?", "3", "4", "5", "6", "C", "150/30 = 5 pens."),
  q("The Roman numeral for 50 is:", "X", "L", "C", "D", "B", "L = 50 in Roman numerals."),
  q("How many seconds in 5 minutes?", "60", "120", "240", "300", "D", "5 × 60 = 300 seconds."),
  q("If 7x = 49, find x:", "5", "6", "7", "8", "C", "x = 49/7 = 7."),
  q("What is a triangle with no equal sides called?", "Isosceles", "Equilateral", "Scalene", "Right", "C", "Scalene has three unequal sides."),
  q("Express 25% as a fraction:", "1/2", "1/4", "1/5", "2/5", "B", "25% = 25/100 = 1/4."),
  q("The number 0.5 × 0.5 =", "0.025", "0.05", "0.25", "2.5", "C", "0.5 × 0.5 = 0.25."),
  q("If 2 = 8, 3 = 27, 4 = 64, then 5 = ?", "100", "120", "125", "150", "C", "Pattern: n³, so 5³ = 125."),
  q("What is the area of a 6 cm square?", "12 cm²", "24 cm²", "36 cm²", "48 cm²", "C", "Area = s² = 36 cm²."),
  q("The first day of the week is:", "Monday", "Sunday", "Tuesday", "Saturday", "B", "Sunday is considered the first day."),
  q("How many months have 31 days?", "5", "6", "7", "8", "C", "7 months have 31 days."),
  q("Simplify: 5 + 5 × 5 - 5", "5", "15", "25", "45", "C", "BODMAS: 5×5=25; 5+25-5=25."),
  q("What is 2/5 of 100?", "20", "25", "40", "50", "C", "2/5 × 100 = 40."),
  q("The product of 9 and 6 is:", "45", "52", "54", "56", "C", "9 × 6 = 54."),
  q("If 3x + 2 = 11, find x:", "2", "3", "4", "5", "B", "3x = 9; x = 3."),
  q("1 millimeter = ___ meter", "0.001", "0.01", "0.1", "1", "A", "1 mm = 0.001 m."),
  q("The smallest 3-digit number is:", "99", "100", "101", "999", "B", "100 is the smallest 3-digit number."),
  q("What is 500 - 237?", "237", "263", "273", "363", "B", "500 - 237 = 263."),
  q("Half of 1/4 is:", "1/2", "1/6", "1/8", "1/10", "C", "1/4 ÷ 2 = 1/4 × 1/2 = 1/8."),
  q("The cube root of 27 is:", "3", "6", "9", "27", "A", "∛27 = 3 (3×3×3=27)."),
  q("How many sides on a pentagon?", "4", "5", "6", "7", "B", "A pentagon has 5 sides."),
  q("If x - 4 = 10, find x:", "4", "6", "10", "14", "D", "x = 10 + 4 = 14."),
  q("The value of 100 ÷ 4 =", "15", "20", "25", "50", "C", "100 ÷ 4 = 25."),
  q("What is the next number: 1, 4, 9, 16, ?", "20", "24", "25", "36", "C", "Pattern: 1², 2², 3², 4², 5² = 25."),
  q("If a dozen costs ₦600, one costs:", "₦30", "₦50", "₦60", "₦100", "B", "600/12 = 50."),
  q("The total cost of ₦250 and ₦350 is:", "₦400", "₦500", "₦600", "₦700", "C", "250 + 350 = 600."),
];

const P = [
  q("The SI unit of mass is:", "Newton", "Gram", "Kilogram", "Pound", "C", "Kilogram is the SI unit of mass."),
  q("Heat transfer by convection occurs in:", "Solids", "Liquids and gases", "Vacuum", "All media", "B", "Convection occurs in fluids (liquids and gases)."),
  q("The speed of light in vacuum is:", "3×10⁶ m/s", "3×10⁷ m/s", "3×10⁸ m/s", "3×10⁹ m/s", "C", "Speed of light c = 3×10⁸ m/s."),
  q("Which is a scalar quantity?", "Force", "Velocity", "Speed", "Acceleration", "C", "Speed has magnitude only."),
  q("Ohm's law relates:", "V and I", "V and R", "I and R", "All", "D", "V = IR relates voltage, current, and resistance."),
  q("The image in a plane mirror is:", "Real and inverted", "Virtual and upright", "Real and upright", "Virtual and inverted", "B", "Plane mirror images are virtual, upright, same size."),
  q("Ultrasound has frequency:", "Below 20 Hz", "20-20,000 Hz", "Above 20,000 Hz", "Above 200 kHz", "C", "Ultrasound is above human hearing range."),
  q("Latent heat is absorbed during:", "Temperature rise", "Change of state", "Expansion", "Contraction", "B", "Latent heat is absorbed/released during phase changes."),
  q("Momentum is calculated as:", "m × a", "m × v", "F × d", "m × g", "B", "Momentum p = mass × velocity."),
  q("The center of gravity of a uniform rod is at:", "One end", "The middle", "Quarter point", "Anywhere", "B", "Uniform rod's center of gravity is at its midpoint."),
  q("A step-down transformer ___ voltage:", "Increases", "Decreases", "Maintains", "Doubles", "B", "Step-down reduces voltage."),
  q("Hooke's law relates to:", "Elasticity", "Gravity", "Friction", "Pressure", "A", "Hooke's law: extension is proportional to force."),
  q("The process of adding impurity to a semiconductor is:", "Doping", "Alloying", "Electroplating", "Distillation", "A", "Doping adds impurities to modify conductivity."),
  q("The angle of incidence equals angle of ___ for reflection:", "Refraction", "Emergence", "Reflection", "Deviation", "C", "Law of reflection: i = r."),
  q("Sound cannot travel through:", "Air", "Water", "Steel", "Vacuum", "D", "Sound needs a medium; cannot travel through vacuum."),
  q("Brownian motion shows:", "Movement of molecules", "Speed of light", "Gravity", "Magnetism", "A", "Brownian motion is random movement of particles in fluid."),
  q("Magnetic field lines go from:", "South to north", "North to south", "East to west", "Random", "B", "Field lines go from N to S outside a magnet."),
  q("Which wave requires a medium?", "Light", "X-ray", "Radio", "Sound", "D", "Sound is mechanical and needs a medium."),
  q("Pressure in a fluid at rest depends on:", "Depth and density", "Area only", "Volume only", "Temperature", "A", "Pressure = hρg (depth × density × gravity)."),
  q("The electromagnet is used in:", "Electric bell", "Light bulb", "Rheostat", "Capacitor", "A", "Electric bells use electromagnets."),
  q("Alcohol evaporates faster than water due to:", "Lower boiling point", "Higher density", "More viscosity", "Surface tension", "A", "Alcohol has lower boiling point, so evaporates faster."),
  q("LED stands for:", "Light Emission Diode", "Light Emitting Diode", "Light Energy Device", "Low Energy Diode", "B", "LED = Light Emitting Diode."),
  q("The wavelength of red light is ___ than blue:", "Longer", "Shorter", "Equal", "Variable", "A", "Red light has longer wavelength than blue."),
  q("Night vision cameras use:", "Visible light", "Infrared", "Ultraviolet", "X-rays", "B", "Infrared detects heat signatures for night vision."),
  q("The law of conservation of energy states energy cannot be:", "Transferred", "Transformed", "Created or destroyed", "Used", "C", "Energy is conserved; it cannot be created or destroyed."),
  q("Friction is ___ force that opposes motion.", "Gravitational", "Nuclear", "Contact", "Magnetic", "C", "Friction is a contact force between surfaces."),
  q("Electric current is measured in:", "Volts", "Amperes", "Watts", "Ohms", "B", "Current is measured in amperes (A)."),
  q("The gravitational pull on the moon is ___ Earth's:", "1/2", "1/4", "1/6", "1/8", "C", "Moon's gravity is about 1/6 of Earth's."),
  q("A converging lens is also called:", "Concave", "Convex", "Plano", "Cylindrical", "B", "Convex (converging) lenses bring rays together."),
  q("The SI unit of energy is:", "Newton", "Joule", "Watt", "Pascal", "B", "Energy is measured in Joules (J)."),
  q("Thermometers use the principle of:", "Expansion", "Contraction", "Density change", "Both expansion and contraction", "D", "Thermometers use thermal expansion/contraction of liquids."),
  q("Electricity is generated in power plants using:", "Turbines", "Capacitors", "Resistors", "Diodes", "A", "Turbines spin generators to produce electricity."),
  q("The longest bone in the body is:", "Femur", "Tibia", "Humerus", "Radius", "A", "The femur (thigh bone) is the longest."),
  q("Satellites orbit Earth due to:", "Magnetism", "Gravity", "Friction", "Air pressure", "B", "Gravity keeps satellites in orbit."),
  q("Ice floats on water because its density is:", "Higher", "Lower", "Equal", "Infinite", "B", "Ice density is lower than water (hence it floats)."),
  q("The heart pumps blood to the lungs via:", "Aorta", "Pulmonary artery", "Vena cava", "Trachea", "B", "Pulmonary artery carries blood to lungs."),
  q("Renewable energy includes:", "Oil", "Solar", "Coal", "Natural gas", "B", "Solar is renewable; fossil fuels are not."),
  q("As altitude increases, atmospheric pressure:", "Increases", "Decreases", "Stays same", "Varies randomly", "B", "Pressure decreases with increasing altitude."),
  q("The function of the fuse is to:", "Save energy", "Prevent overcurrent", "Store charge", "Amplify signal", "B", "Fuses break the circuit during current overload."),
  q("Gamma rays are used in:", "Radiotherapy", "Radio", "TV", "Hearing aids", "A", "Gamma rays are used in cancer treatment."),
];

const C = [
  q("The chemical symbol for gold is:", "Go", "Gd", "Au", "Ag", "C", "Au from Latin 'aurum' meaning gold."),
  q("The pH of pure water is:", "5", "6", "7", "8", "C", "Pure water has pH 7 (neutral)."),
  q("Which is NOT a greenhouse gas?", "CO₂", "Methane", "Nitrogen", "Water vapor", "C", "Nitrogen is not a greenhouse gas."),
  q("The smallest particle of an element is:", "Molecule", "Atom", "Electron", "Proton", "B", "An atom is the smallest particle of an element."),
  q("Rusting of iron requires:", "Oxygen only", "Water only", "Oxygen and water", "Air only", "C", "Rust requires both oxygen and water."),
  q("The chemical name of common salt is:", "Sodium nitrate", "Sodium chloride", "Potassium chloride", "Calcium carbonate", "B", "Common salt is sodium chloride (NaCl)."),
  q("Alloy of copper and tin is called:", "Brass", "Steel", "Bronze", "Solder", "C", "Bronze is copper (Cu) + tin (Sn)."),
  q("Which gas is used in fire extinguishers?", "Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen", "C", "CO₂ extinguishes fire by smothering it."),
  q("The atomic number of carbon is:", "4", "6", "8", "12", "B", "Carbon has 6 protons."),
  q("Distillation separates mixtures based on:", "Density", "Boiling point", "Solubility", "Color", "B", "Distillation uses boiling point differences."),
  q("The chemical formula of water is:", "HO", "H₂O", "H₂O₂", "OH₂", "B", "Water = H₂O."),
  q("Which element is liquid at room temperature?", "Iron", "Mercury", "Lead", "Zinc", "B", "Mercury is liquid at room temperature."),
  q("Substances with pH below 7 are:", "Acids", "Bases", "Salts", "Neutral", "A", "Acids have pH < 7; bases have pH > 7."),
  q("The main component of natural gas is:", "Ethane", "Propane", "Butane", "Methane", "D", "Natural gas is mostly methane (CH₄)."),
  q("Valency of oxygen is:", "1", "2", "3", "4", "B", "Oxygen has valency 2 (needs 2 electrons)."),
  q("Chemical bond between metals and non-metals is:", "Covalent", "Ionic", "Metallic", "Hydrogen", "B", "Metals and non-metals form ionic bonds."),
  q("Atomic mass unit is measured in:", "Grams", "Daltons", "Kilograms", "Newtons", "B", "Atomic mass unit = Dalton (Da)."),
  q("LPG stands for:", "Liquid Petroleum Gas", "Liquefied Petroleum Gas", "Light Petroleum Gas", "Low Pressure Gas", "B", "LPG = Liquefied Petroleum Gas."),
  q("The color of copper(II) sulfate solution is:", "Green", "Blue", "Red", "Yellow", "B", "CuSO₄ solution is characteristic blue."),
  q("Which acid is found in lemon?", "Sulfuric acid", "Hydrochloric acid", "Citric acid", "Acetic acid", "C", "Lemons contain citric acid."),
  q("The formula for sulfuric acid is:", "HCl", "HNO₃", "H₂SO₄", "H₂CO₃", "C", "Sulfuric acid = H₂SO₄."),
  q("Catalyst ___ the rate of reaction.", "Decreases", "Increases", "Stops", "Reverses", "B", "Catalysts speed up reactions without being consumed."),
  q("Isotopes have same number of:", "Neutrons", "Protons", "Electrons and protons", "Mass number", "C", "Isotopes have same protons but different neutrons."),
  q("The periodic table is organized by:", "Mass number", "Atomic number", "Density", "Color", "B", "Elements are ordered by increasing atomic number."),
  q("The process of electrolysis uses:", "Heat", "Electricity", "Light", "Pressure", "B", "Electrolysis uses electrical energy for reactions."),
  q("The air pollutant that causes acid rain is:", "CO₂", "SO₂", "O₂", "N₂", "B", "Sulfur dioxide (SO₂) causes acid rain."),
  q("Molar mass of water (H₂O) is:", "16 g/mol", "17 g/mol", "18 g/mol", "20 g/mol", "C", "H₂O = 2(1) + 16 = 18 g/mol."),
  q("Which family includes neon and argon?", "Halogens", "Noble gases", "Alkali metals", "Transition", "B", "Ne and Ar are noble gases (Group 18)."),
  q("The most abundant gas in the atmosphere is:", "Oxygen", "CO₂", "Nitrogen", "Hydrogen", "C", "Nitrogen is ~78% of atmosphere."),
  q("Endothermic reactions ___ heat.", "Release", "Absorb", "Neither", "Double", "B", "Endothermic means heat is absorbed."),
  q("Orbitals are regions where ___ are found.", "Protons", "Neutrons", "Electrons", "Nuclei", "C", "Orbitals describe electron locations around nucleus."),
  q("The gas produced when zinc reacts with HCl is:", "Oxygen", "Hydrogen", "Chlorine", "Nitrogen", "B", "Zn + 2HCl → ZnCl₂ + H₂."),
  q("The pure substance that cannot be split chemically is:", "Compound", "Mixture", "Element", "Solution", "C", "Elements are the simplest pure substances."),
  q("The symbol for potassium is:", "Po", "Pt", "K", "P", "C", "K from Latin 'kalium'."),
  q("Hydrolysis is reaction with:", "Water", "Acid", "Base", "Salt", "A", "Hydrolysis involves splitting bonds using water."),
  q("The density of water is maximum at:", "0°C", "4°C", "10°C", "100°C", "B", "Water has maximum density at 4°C."),
  q("Empirical formula shows:", "Actual number of atoms", "Simplest ratio of atoms", "Molecular weight", "Structure", "B", "Empirical formula is the simplest whole-number ratio."),
  q("Covalent bonds involve:", "Electron transfer", "Electron sharing", "Proton transfer", "Neutron sharing", "B", "Covalent bonds share electron pairs."),
  q("The pH of gastric juice is about:", "2", "5", "7", "9", "A", "Stomach acid has pH ~2 (very acidic)."),
  q("Sublimation is direct change from:", "Solid to gas", "Liquid to gas", "Solid to liquid", "Gas to liquid", "A", "Sublimation bypasses the liquid state."),
];

const B = [
  q("The powerhouse of the cell is the:", "Nucleus", "Mitochondrion", "Ribosome", "Golgi body", "B", "Mitochondria produce ATP through cellular respiration."),
  q("The human skeleton has ___ bones:", "106", "206", "306", "406", "B", "Adult human skeleton has 206 bones."),
  q("Blood group ___ is known as universal donor:", "A", "B", "AB", "O", "D", "Blood group O can donate to all."),
  q("A pathogen is a:", "Medicine", "Disease-causing organism", "Vitamin", "Mineral", "B", "Pathogens cause diseases."),
  q("The largest organ in the human body is:", "Liver", "Brain", "Skin", "Heart", "C", "The skin is the largest organ."),
  q("Which vitamin is produced when skin is exposed to sunlight?", "A", "B", "C", "D", "D", "Sunlight on skin produces vitamin D."),
  q("The tube that carries urine from kidney to bladder is:", "Urethra", "Ureter", "Nephron", "Bronchiole", "B", "Ureters connect kidneys to bladder."),
  q("The green pigment in plants is:", "Melanin", "Chlorophyll", "Hemoglobin", "Xanthophyll", "B", "Chlorophyll absorbs light for photosynthesis."),
  q("The basic unit of life is:", "Atom", "Molecule", "Cell", "Tissue", "C", "The cell is the basic structural unit of life."),
  q("Malaria is caused by:", "Virus", "Bacterium", "Protozoan", "Fungus", "C", "Malaria is caused by Plasmodium protozoan."),
  q("An ecosystem includes:", "Living things only", "Non-living things only", "Both living and non-living", "Plants only", "C", "Ecosystem = biotic + abiotic components."),
  q("The human heart has ___ chambers:", "2", "3", "4", "6", "C", "The heart has 4 chambers: 2 atria, 2 ventricles."),
  q("The scientific name for humans is:", "Homo erectus", "Homo habilis", "Homo sapiens", "Homo neanderthalensis", "C", "Modern humans = Homo sapiens."),
  q("Decomposers in an ecosystem are:", "Plants", "Animals", "Bacteria and fungi", "Producers", "C", "Decomposers break down dead organisms."),
  q("The respiratory pigment in blood is:", "Insulin", "Hemoglobin", "Melanin", "Keratin", "B", "Hemoglobin in RBCs carries oxygen."),
  q("The units of heredity are called:", "Chromosomes", "Genes", "Cells", "Nuclei", "B", "Genes are the units of heredity."),
  q("Which organ filters blood?", "Liver", "Heart", "Kidney", "Lungs", "C", "Kidneys filter waste from blood to produce urine."),
  q("The process by which plants make food is:", "Respiration", "Digestion", "Photosynthesis", "Fermentation", "C", "Photosynthesis: CO₂ + H₂O → glucose + O₂."),
  q("An organism that lives on dead matter is a:", "Parasite", "Saprophyte", "Predator", "Host", "B", "Saprophytes feed on dead organic matter."),
  q("The part of the brain responsible for balance is:", "Cerebrum", "Cerebellum", "Medulla", "Hypothalamus", "B", "Cerebellum controls balance and coordination."),
  q("Which is a vector-borne disease?", "Typhoid", "Cholera", "Malaria", "Tetanus", "C", "Malaria is transmitted by Anopheles mosquitoes."),
  q("Fertilization in humans occurs in the:", "Ovary", "Uterus", "Fallopian tube", "Vagina", "C", "Fertilization occurs in the fallopian tube."),
  q("DNA structure was discovered by:", "Darwin", "Mendel", "Watson and Crick", "Pasteur", "C", "Watson and Crick discovered DNA double helix."),
  q("The tough outer covering of insects is:", "Skin", "Fur", "Exoskeleton", "Shell", "C", "Insects have exoskeleton made of chitin."),
  q("Binary fission is a type of:", "Sexual reproduction", "Asexual reproduction", "Fertilization", "Pollination", "B", "Binary fission is asexual (splitting into two)."),
  q("Diplopia means:", "Double vision", "Nearsightedness", "Farsightedness", "Blindness", "A", "Diplopia is seeing double images."),
  q("The primary function of roots is:", "Photosynthesis", "Absorption of water", "Reproduction", "Support only", "B", "Roots absorb water and minerals from soil."),
  q("Animals without backbones are called:", "Mammals", "Vertebrates", "Invertebrates", "Reptiles", "C", "Invertebrates lack a vertebral column."),
  q("The human organ that produces bile is:", "Pancreas", "Stomach", "Liver", "Gallbladder", "C", "The liver produces bile for fat digestion."),
  q("The theory of natural selection was proposed by:", "Lamarck", "Darwin", "Mendel", "Wallace", "B", "Darwin proposed natural selection theory."),
  q("Osmosis is the movement of water across a:", "Semi-permeable membrane", "Solid barrier", "Gas", "Vacuum", "A", "Osmosis: water through semi-permeable membrane."),
  q("The human life cycle begins with:", "Birth", "Fertilization", "Growth", "Death", "B", "Life cycle starts with fertilization of egg."),
  q("A food chain always begins with a:", "Consumer", "Producer", "Decomposer", "Predator", "B", "Food chains start with producers (plants)."),
  q("The number of chromosomes in human cells is:", "23", "44", "46", "48", "C", "Humans have 46 chromosomes (23 pairs)."),
  q("Bacteria reproduce by:", "Mitosis", "Binary fission", "Meiosis", "Spores", "B", "Bacteria reproduce by binary fission."),
  q("Which part of the eye focuses light?", "Retina", "Cornea", "Lens", "Iris", "C", "The lens focuses light onto the retina."),
  q("Vaccination creates:", "Active immunity", "Passive immunity", "Natural immunity", "Innate immunity", "A", "Vaccines stimulate active immunity."),
  q("The group of mammals that lay eggs are:", "Marsupials", "Monotremes", "Placentals", "Primates", "B", "Monotremes like platypus lay eggs."),
  q("The waste product of respiration is:", "Oxygen", "Glucose", "Carbon dioxide", "Water", "C", "Cellular respiration produces CO₂ as waste."),
  q("The tongue detects:", "Light", "Sound", "Taste", "Touch", "C", "The tongue has taste buds for detecting flavors."),
];

const G = [
  q("Which is a tier of government in Nigeria?", "County", "State", "Province", "District", "B", "Nigeria has federal, state, and local tiers."),
  q("The Nigerian constitution is:", "Written and rigid", "Unwritten", "Flexible only", "Common law", "A", "Nigeria's constitution is written and rigid."),
  q("The head of the Nigerian Senate is called:", "President", "Speaker", "Chief Justice", "Senate President", "D", "The Senate is led by the Senate President."),
  q("Universal suffrage means:", "Only men vote", "Only women vote", "All adults vote", "No one votes", "C", "Universal suffrage: all adults have voting rights."),
  q("Separation of powers divides government into:", "Two branches", "Three branches", "Four branches", "Five branches", "B", "Three branches: Executive, Legislative, Judiciary."),
  q("A political party aims to:", "Make profits", "Win elections", "Educate citizens", "Build roads", "B", "Political parties aim to gain power through elections."),
  q("Nigeria became a republic in:", "1960", "1963", "1966", "1979", "B", "Nigeria became a republic in 1963."),
  q("The current Nigerian constitution was enacted in:", "1979", "1989", "1999", "2005", "C", "The 1999 Constitution is currently in force."),
  q("Democracy means government by the:", "Rich", "Few", "People", "Military", "C", "Democracy: rule by the people."),
  q("The highest court in Nigeria is:", "Appeal Court", "Supreme Court", "High Court", "Tribunal", "B", "The Supreme Court is Nigeria's highest court."),
  q("A bill becomes law when assented by:", "Senate President", "Chief Justice", "President", "Governor", "C", "The President assents bills to become law."),
  q("OPEC is an organization of:", "Oil exporting countries", "African nations", "European union", "Asian countries", "A", "OPEC coordinates petroleum policies."),
  q("Civil service is ___ in politics.", "Active", "Involved", "Neutral", "Partisan", "C", "Civil service is politically neutral."),
  q("The first prime minister of Nigeria was:", "Azikiwe", "Balewa", "Awolowo", "Ironsi", "B", "Sir Abubakar Tafawa Balewa was first PM."),
  q("Pressure groups aim to:", "Win elections", "Influence policy", "Form government", "Make laws", "B", "Pressure groups influence government decisions."),
  q("Local governments in Nigeria are headed by:", "Governor", "Chairman", "Mayor", "Commissioner", "B", "Local government is headed by a Chairman."),
  q("The National Assembly has ___ chambers.", "1", "2", "3", "4", "B", "Bicameral: Senate and House of Representatives."),
  q("Franchise means the right to:", "Speak", "Vote", "Travel", "Work", "B", "Franchise is the right to vote."),
  q("Which is a fundamental human right?", "Right to vote only", "Right to life", "Right to free data", "Right to travel abroad", "B", "Right to life is a fundamental human right."),
  q("The Economic Community of West African States is:", "ECOWAS", "AU", "UN", "OPEC", "A", "ECOWAS is the West African economic bloc."),
  q("A constitution can be:", "Written or unwritten", "Only written", "Only verbal", "Only customary", "A", "Constitutions can be written or unwritten."),
  q("Judicial review allows courts to:", "Make laws", "Interpret the constitution", "Appoint judges", "Veto bills", "B", "Courts interpret the constitution via judicial review."),
  q("The first military coup in Nigeria was in:", "1960", "1963", "1966", "1975", "C", "The first military coup was January 15, 1966."),
  q("Indirect election means voting for:", "Candidates directly", "Representatives who vote", "The president only", "No one", "B", "Indirect: electors choose representatives to vote."),
  q("The United Nations was formed in:", "1918", "1945", "1960", "1991", "B", "The UN was established in 1945."),
  q("Sovereignty means:", "Freedom to trade", "Supreme power of a state", "Economic policy", "Diplomatic immunity", "B", "Sovereignty is supreme authority within a territory."),
  q("Which is NOT a function of government?", "Maintaining order", "Providing education", "Maximizing profit", "National defense", "C", "Profit maximization is business, not government."),
  q("The legislature in the UK is called:", "Congress", "Parliament", "National Assembly", "Diet", "B", "UK's legislature is Parliament."),
  q("Corruption is a challenge to:", "Development only", "Democracy only", "Both development and democracy", "None", "C", "Corruption undermines both development and democracy."),
  q("A referendum is a vote on:", "A person", "A policy or issue", "A party", "A budget", "B", "Referendum is direct vote on a specific issue."),
  q("The Ombudsman investigates:", "Military matters", "Citizen complaints against govt", "Tax evasion", "Election results", "B", "Ombudsman addresses citizen grievances."),
  q("Public opinion influences:", "Government policy", "Only elections", "Court rulings", "Military decisions", "A", "Public opinion shapes government policies."),
  q("The chief law officer of Nigeria is:", "Chief Justice", "Attorney General", "Solicitor General", "Justice Minister", "B", "Attorney General is the chief law officer."),
  q("An absolute monarchy has ___ ruler.", "Elected", "Hereditary", "Appointed", "Ceremonial", "B", "Absolute monarchy: hereditary ruler has full power."),
  q("Bicameral legislature has:", "One house", "Two houses", "Three houses", "No houses", "B", "Bicameral means two legislative chambers."),
  q("A political ideology is a set of:", "Laws", "Beliefs about society", "Trade rules", "Medical practices", "B", "Political ideology: coherent set of beliefs about governance."),
  q("The first Executive President of Nigeria was:", "Obasanjo", "Shagari", "Buhari", "Yar'Adua", "B", "Shehu Shagari was first Executive President (1979)."),
  q("Delegated legislation is made by:", "Parliament directly", "Ministers under Parliament's authority", "Courts", "Local governments", "B", "Delegated: ministers make regulations under enabling act."),
  q("The principle of checks and balances prevents:", "Democracy", "Power abuse", "Elections", "Legislation", "B", "Checks and balances prevent concentration/abuse of power."),
  q("The Hausa/Fulani pre-colonial system was:", "Democratic", "Republican", "Emirate", "Military", "C", "The Hausa/Fulani had an emirate system."),
];

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    const ALL = [
      ...E.map(q => ({ ...q, subject: 'english' })),
      ...M.map(q => ({ ...q, subject: 'mathematics' })),
      ...P.map(q => ({ ...q, subject: 'physics' })),
      ...C.map(q => ({ ...q, subject: 'chemistry' })),
      ...B.map(q => ({ ...q, subject: 'biology' })),
      ...G.map(q => ({ ...q, subject: 'government' })),
    ];

    let inserted = 0;
    let skipped = 0;
    const bySubject: Record<string, number> = {};

    for (const q of ALL) {
      const { data: existing } = await supabase
        .from('jamb_questions')
        .select('id')
        .eq('question', q.question)
        .maybeSingle();

      if (existing) { skipped++; continue; }

      await supabase.from('jamb_questions').insert({
        subject: q.subject, question: q.question,
        option_a: q.option_a, option_b: q.option_b, option_c: q.option_c, option_d: q.option_d,
        correct_answer: q.correct_answer, explanation: q.explanation, year: 2025,
      });
      inserted++;
      bySubject[q.subject] = (bySubject[q.subject] || 0) + 1;
    }

    const total = ALL.length;
    return new Response(JSON.stringify({
      success: true,
      message: `Seeded ${inserted}/${total} new questions, skipped ${skipped}`,
      inserted, skipped, total_attempted: total, by_subject: bySubject,
    }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
