import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Consolidated questions from seed-more-questions + seed-more-questions-v2 + new questions
const QUESTIONS = [
  // ============ PHYSICS (30 questions) ============
  { subject: "physics", year: 2024, question: "A body of mass 5 kg is acted upon by a force of 20 N. Its acceleration is:", option_a: "2 m/s²", option_b: "4 m/s²", option_c: "10 m/s²", option_d: "25 m/s²", correct_answer: "B", explanation: "F = ma → a = F/m = 20/5 = 4 m/s².", topics: ["motion", "forces"] },
  { subject: "physics", year: 2023, question: "The momentum of a 2 kg object moving at 3 m/s is:", option_a: "1.5 kg·m/s", option_b: "5 kg·m/s", option_c: "6 kg·m/s", option_d: "0.67 kg·m/s", correct_answer: "C", explanation: "p = mv = 2 × 3 = 6 kg·m/s.", topics: ["motion"] },
  { subject: "physics", year: 2024, question: "Which of the following energy conversions occurs in a battery?", option_a: "Heat to light", option_b: "Chemical to electrical", option_c: "Mechanical to electrical", option_d: "Solar to chemical", correct_answer: "B", explanation: "Batteries convert stored chemical energy into electrical energy.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2023, question: "The pressure exerted by a 50 N force on an area of 0.5 m² is:", option_a: "25 Pa", option_b: "50 Pa", option_c: "100 Pa", option_d: "200 Pa", correct_answer: "C", explanation: "P = F/A = 50/0.5 = 100 Pa.", topics: ["pressure"] },
  { subject: "physics", year: 2024, question: "An object is placed 30 cm in front of a convex lens of focal length 10 cm. The image distance is:", option_a: "7.5 cm", option_b: "15 cm", option_c: "20 cm", option_d: "30 cm", correct_answer: "B", explanation: "1/f = 1/v + 1/u → 1/10 = 1/v + 1/30 → 1/v = 1/10 − 1/30 = 2/30 → v = 15 cm.", topics: ["optics"] },
  { subject: "physics", year: 2023, question: "The SI unit of electric current is:", option_a: "Volt", option_b: "Ohm", option_c: "Ampere", option_d: "Watt", correct_answer: "C", explanation: "Ampere (A) is the SI unit of electric current.", topics: ["electricity"] },
  { subject: "physics", year: 2024, question: "A resistor of 10 Ω carries a current of 2 A. The potential difference across it is:", option_a: "5 V", option_b: "10 V", option_c: "20 V", option_d: "40 V", correct_answer: "C", explanation: "V = IR = 2 × 10 = 20 V.", topics: ["electricity"] },
  { subject: "physics", year: 2023, question: "The phenomenon where light bends as it passes from one medium to another is called:", option_a: "Reflection", option_b: "Diffraction", option_c: "Refraction", option_d: "Interference", correct_answer: "C", explanation: "Refraction is the bending of light due to change in speed between media.", topics: ["optics"] },
  { subject: "physics", year: 2024, question: "A body weighing 200 N on earth would weigh approximately on the moon (g_moon = g_earth/6):", option_a: "33.3 N", option_b: "1200 N", option_c: "200 N", option_d: "600 N", correct_answer: "A", explanation: "W_moon = 200/6 ≈ 33.3 N.", topics: ["gravitational"] },
  { subject: "physics", year: 2023, question: "Which type of wave is a sound wave?", option_a: "Transverse", option_b: "Longitudinal", option_c: "Electromagnetic", option_d: "Digital", correct_answer: "B", explanation: "Sound waves are longitudinal (compressions and rarefactions).", topics: ["waves"] },
  { subject: "physics", year: 2024, question: "The work done in lifting a 10 kg object through a height of 5 m (g = 10 m/s²) is:", option_a: "50 J", option_b: "100 J", option_c: "250 J", option_d: "500 J", correct_answer: "D", explanation: "W = mgh = 10 × 10 × 5 = 500 J.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2023, question: "Which of the following is NOT a vector quantity?", option_a: "Displacement", option_b: "Velocity", option_c: "Speed", option_d: "Acceleration", correct_answer: "C", explanation: "Speed has magnitude only — it is a scalar.", topics: ["motion"] },
  { subject: "physics", year: 2024, question: "The period of a simple pendulum of length 1 m (g = 10 m/s²) is approximately:", option_a: "1.0 s", option_b: "2.0 s", option_c: "3.14 s", option_d: "0.5 s", correct_answer: "B", explanation: "T = 2π√(L/g) = 2π√(1/10) ≈ 2π × 0.316 ≈ 2.0 s.", topics: ["waves"] },
  { subject: "physics", year: 2023, question: "The efficiency of a machine that does 40 J of useful work from 100 J of input energy is:", option_a: "25%", option_b: "40%", option_c: "60%", option_d: "150%", correct_answer: "B", explanation: "Efficiency = (useful output/input) × 100 = 40/100 × 100 = 40%.", topics: ["simple_machines"] },
  { subject: "physics", year: 2024, question: "Radioactive decay of carbon-14 is used for:", option_a: "Generating electricity", option_b: "Dating ancient artifacts", option_c: "Sterilizing food", option_d: "Treating cancer", correct_answer: "B", explanation: "Carbon-14 dating determines the age of organic materials.", topics: ["nuclear_physics"] },
  { subject: "physics", year: 2023, question: "The phenomenon responsible for the blue colour of the sky is:", option_a: "Reflection", option_b: "Refraction", option_c: "Scattering", option_d: "Dispersion", correct_answer: "C", explanation: "Rayleigh scattering of sunlight by atmospheric molecules.", topics: ["waves"] },
  { subject: "physics", year: 2024, question: "A car accelerates from rest to 20 m/s in 10 s. The distance covered is:", option_a: "50 m", option_b: "100 m", option_c: "200 m", option_d: "400 m", correct_answer: "B", explanation: "s = ½at², a = (20−0)/10 = 2 m/s², s = ½ × 2 × 100 = 100 m.", topics: ["motion"] },
  { subject: "physics", year: 2023, question: "The device used to measure electric current is a:", option_a: "Voltmeter", option_b: "Ammeter", option_c: "Ohmmeter", option_d: "Galvanometer", correct_answer: "B", explanation: "An ammeter measures current and is connected in series.", topics: ["electricity"] },
  { subject: "physics", year: 2024, question: "When a metal rod is heated, it expands. This is an example of:", option_a: "Linear expansion", option_b: "Surface expansion", option_c: "Volume expansion", option_d: "Contraction", correct_answer: "A", explanation: "Heating a rod causes expansion along its length.", topics: ["thermodynamics"] },
  { subject: "physics", year: 2023, question: "The angle of incidence equals the angle of reflection. This law applies to:", option_a: "Refraction", option_b: "Diffraction", option_c: "Regular reflection", option_d: "Diffuse reflection", correct_answer: "C", explanation: "Law of reflection applies to regular (specular) reflection.", topics: ["optics"] },
  { subject: "physics", year: 2024, question: "A body moves in a circle of radius 10 m at a speed of 10 m/s. Its centripetal acceleration is:", option_a: "1 m/s²", option_b: "10 m/s²", option_c: "100 m/s²", option_d: "1000 m/s²", correct_answer: "B", explanation: "a = v²/r = 100/10 = 10 m/s².", topics: ["circular_motion"] },
  { subject: "physics", year: 2023, question: "Which of the following is the correct unit for power?", option_a: "Joule", option_b: "Newton", option_c: "Watt", option_d: "Pascal", correct_answer: "C", explanation: "Watt (W) = Joule/second is the unit of power.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2024, question: "Light travels fastest in:", option_a: "Glass", option_b: "Water", option_c: "Diamond", option_d: "Vacuum", correct_answer: "D", explanation: "Light speed is maximum in vacuum (3 × 10⁸ m/s).", topics: ["optics"] },
  { subject: "physics", year: 2023, question: "An object of mass 4 kg is lifted 3 m above the ground. Its gravitational potential energy (g=10) is:", option_a: "12 J", option_b: "40 J", option_c: "120 J", option_d: "70 J", correct_answer: "C", explanation: "PE = mgh = 4 × 10 × 3 = 120 J.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2024, question: "The phenomenon where waves bend around obstacles is called:", option_a: "Reflection", option_b: "Refraction", option_c: "Diffraction", option_d: "Polarization", correct_answer: "C", explanation: "Diffraction = bending of waves around obstacles or through openings.", topics: ["waves"] },
  { subject: "physics", year: 2023, question: "In a series circuit with three resistors of 2 Ω each, the total resistance is:", option_a: "2/3 Ω", option_b: "3 Ω", option_c: "6 Ω", option_d: "8 Ω", correct_answer: "C", explanation: "R_total = R₁ + R₂ + R₃ = 2 + 2 + 2 = 6 Ω.", topics: ["electricity"] },
  { subject: "physics", year: 2024, question: "The frequency of alternating current in Nigeria is:", option_a: "50 Hz", option_b: "60 Hz", option_c: "100 Hz", option_d: "220 Hz", correct_answer: "A", explanation: "Nigeria uses 50 Hz AC supply.", topics: ["electricity"] },
  { subject: "physics", year: 2023, question: "Which color of light has the longest wavelength?", option_a: "Violet", option_b: "Green", option_c: "Yellow", option_d: "Red", correct_answer: "D", explanation: "Red has the longest wavelength (~700 nm) in the visible spectrum.", topics: ["waves"] },
  { subject: "physics", year: 2024, question: "The kinetic energy of a 1 kg object moving at 4 m/s is:", option_a: "2 J", option_b: "4 J", option_c: "8 J", option_d: "16 J", correct_answer: "C", explanation: "KE = ½mv² = ½ × 1 × 16 = 8 J.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2023, question: "A transformer with 1000 turns on the primary and 100 turns on the secondary is a:", option_a: "Step-up transformer", option_b: "Step-down transformer", option_c: "Auto transformer", option_d: "None of these", correct_answer: "B", explanation: "Fewer secondary turns = voltage steps down.", topics: ["electromagnetism"] },

  // ============ CHEMISTRY (30 questions) ============
  { subject: "chemistry", year: 2024, question: "The pH of a solution with [H⁺] = 10⁻³ mol/dm³ is:", option_a: "3", option_b: "7", option_c: "11", option_d: "14", correct_answer: "A", explanation: "pH = −log[H⁺] = −log(10⁻³) = 3.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2023, question: "Which of the following is a strong acid?", option_a: "Ethanoic acid", option_b: "Hydrochloric acid", option_c: "Carbonic acid", option_d: "Citric acid", correct_answer: "B", explanation: "HCl completely ionizes in water — it is a strong acid.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "The electronic configuration of sodium (Z=11) is:", option_a: "2,8,1", option_b: "2,8,2", option_c: "2,2,8,1", option_d: "1,2,8", correct_answer: "A", explanation: "11 electrons fill as 2 in K, 8 in L, 1 in M.", topics: ["atomic_structure"] },
  { subject: "chemistry", year: 2023, question: "Which of the following undergoes substitution reaction?", option_a: "Ethene", option_b: "Ethyne", option_c: "Methane", option_d: "Benzene", correct_answer: "C", explanation: "Alkanes like methane undergo substitution with halogens.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "The number of moles in 36 g of water (H=1, O=16) is:", option_a: "1", option_b: "2", option_c: "3", option_d: "18", correct_answer: "B", explanation: "M(H₂O) = 18 g/mol. n = 36/18 = 2 mol.", topics: ["stoichiometry"] },
  { subject: "chemistry", year: 2023, question: "Which gas is produced when zinc reacts with dilute hydrochloric acid?", option_a: "Oxygen", option_b: "Chlorine", option_c: "Hydrogen", option_d: "Carbon dioxide", correct_answer: "C", explanation: "Zn + 2HCl → ZnCl₂ + H₂.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "In the reaction N₂ + 3H₂ ⇌ 2NH₃, increasing pressure shifts equilibrium to:", option_a: "Left (reactants)", option_b: "Right (products)", option_c: "Nowhere", option_d: "Both equally", correct_answer: "B", explanation: "Fewer moles of gas on the product side (2 vs 4). High pressure favours products.", topics: ["equilibrium"] },
  { subject: "chemistry", year: 2023, question: "The atomic number of an element is 17. It is:", option_a: "Sodium", option_b: "Chlorine", option_c: "Argon", option_d: "Sulphur", correct_answer: "B", explanation: "Z = 17 is chlorine (Cl).", topics: ["atomic_structure"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is an electrolyte?", option_a: "Distilled water", option_b: "Ethanol", option_c: "Sodium chloride solution", option_d: "Kerosene", correct_answer: "C", explanation: "NaCl solution conducts electricity — it is an electrolyte.", topics: ["electrochemistry"] },
  { subject: "chemistry", year: 2023, question: "The IUPAC name of CH₃CH₂OH is:", option_a: "Methanol", option_b: "Ethanol", option_c: "Propanol", option_d: "Ethanoic acid", correct_answer: "B", explanation: "Two carbons with -OH group = ethanol.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "Which process involves the conversion of electrical energy to chemical energy?", option_a: "Galvanic cell", option_b: "Electrolysis", option_c: "Combustion", option_d: "Distillation", correct_answer: "B", explanation: "Electrolysis uses electricity to drive non-spontaneous reactions.", topics: ["electrochemistry"] },
  { subject: "chemistry", year: 2023, question: "Which of the following is a homologous series?", option_a: "Alkanes", option_b: "Metals", option_c: "Noble gases", option_d: "Acids only", correct_answer: "A", explanation: "Alkanes form a homologous series with general formula CₙH₂ₙ₊₂.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "The mass of one mole of CO₂ (C=12, O=16) is:", option_a: "28 g", option_b: "44 g", option_c: "32 g", option_d: "16 g", correct_answer: "B", explanation: "M(CO₂) = 12 + 2(16) = 44 g/mol.", topics: ["stoichiometry"] },
  { subject: "chemistry", year: 2023, question: "The product of incomplete combustion of hydrocarbons is:", option_a: "CO₂ and H₂O", option_b: "CO and H₂O", option_c: "C and H₂", option_d: "CO₂ only", correct_answer: "B", explanation: "Incomplete combustion produces carbon monoxide and water.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is a redox reaction?", option_a: "NaCl + AgNO₃", option_b: "Zn + CuSO₄", option_c: "HCl + NaOH", option_d: "CaCO₃ → CaO + CO₂", correct_answer: "B", explanation: "Zn is oxidized (0→+2), Cu²⁺ is reduced (+2→0).", topics: ["redox"] },
  { subject: "chemistry", year: 2023, question: "The solubility of most solid solutes in water increases with:", option_a: "Decrease in temperature", option_b: "Increase in temperature", option_c: "Decrease in pressure", option_d: "Increase in volume", correct_answer: "B", explanation: "Higher temperature generally increases solubility of solids.", topics: ["solutions"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is an acid salt?", option_a: "NaCl", option_b: "NaHCO₃", option_c: "Na₂SO₄", option_d: "KNO₃", correct_answer: "B", explanation: "NaHCO₃ (sodium hydrogen carbonate) contains a replaceable H.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2023, question: "The volume of gas at STP occupied by 2 moles is:", option_a: "11.2 dm³", option_b: "22.4 dm³", option_c: "44.8 dm³", option_d: "2.24 dm³", correct_answer: "C", explanation: "At STP, 1 mol = 22.4 dm³. 2 mol = 44.8 dm³.", topics: ["gas_laws"] },
  { subject: "chemistry", year: 2024, question: "Which element has the electronic configuration 2,8,7?", option_a: "Sodium", option_b: "Chlorine", option_c: "Argon", option_d: "Calcium", correct_answer: "B", explanation: "17 electrons: 2,8,7 = Chlorine.", topics: ["atomic_structure"] },
  { subject: "chemistry", year: 2023, question: "Which of the following is a base?", option_a: "HCl", option_b: "NaOH", option_c: "H₂SO₄", option_d: "CH₃COOH", correct_answer: "B", explanation: "NaOH is sodium hydroxide — a strong base.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "The empirical formula of butane (C₄H₁₀) is:", option_a: "CH₂", option_b: "C₂H₅", option_c: "C₄H₁₀", option_d: "CH₃", correct_answer: "B", explanation: "C₄H₁₀ → divide by 2 → C₂H₅.", topics: ["stoichiometry"] },
  { subject: "chemistry", year: 2023, question: "Electrolysis of molten NaCl produces:", option_a: "Na and O₂", option_b: "Na and Cl₂", option_c: "H₂ and Cl₂", option_d: "NaOH and Cl₂", correct_answer: "B", explanation: "Molten NaCl: Na⁺ → Na at cathode, Cl⁻ → Cl₂ at anode.", topics: ["electrochemistry"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is NOT a property of ionic compounds?", option_a: "High melting point", option_b: "Conduct electricity when molten", option_c: "Are soluble in organic solvents", option_d: "Form crystal lattices", correct_answer: "C", explanation: "Ionic compounds are generally insoluble in organic solvents.", topics: ["chemical_bonding"] },
  { subject: "chemistry", year: 2023, question: "The reaction rate increases with increase in:", option_a: "Volume", option_b: "Temperature", option_c: "Concentration of products", option_d: "Container size", correct_answer: "B", explanation: "Higher temperature → more kinetic energy → more successful collisions.", topics: ["chemical_kinetics"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is a characteristic of transition metals?", option_a: "Always form colourless compounds", option_b: "Low melting points", option_c: "Variable oxidation states", option_d: "Poor conductors of heat", correct_answer: "C", explanation: "Transition metals exhibit multiple oxidation states.", topics: ["periodic_table"] },
  { subject: "chemistry", year: 2023, question: "The gas produced when copper reacts with concentrated nitric acid is:", option_a: "Hydrogen", option_b: "Oxygen", option_c: "Nitrogen dioxide", option_d: "Nitrogen", correct_answer: "C", explanation: "Cu + 4HNO₃ → Cu(NO₃)₂ + 2NO₂ + 2H₂O.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is used as a catalyst in the Haber process?", option_a: "Vanadium pentoxide", option_b: "Iron", option_c: "Platinum", option_d: "Manganese dioxide", correct_answer: "B", explanation: "Iron (with promoters) catalyzes N₂ + 3H₂ → 2NH₃.", topics: ["equilibrium", "chemical_kinetics"] },
  { subject: "chemistry", year: 2023, question: "The oxidation state of sulphur in H₂SO₄ is:", option_a: "+2", option_b: "+4", option_c: "+6", option_d: "−2", correct_answer: "C", explanation: "2(+1) + S + 4(−2) = 0 → S = +6.", topics: ["redox"] },
  { subject: "chemistry", year: 2024, question: "An isotope of an element has:", option_a: "Different number of electrons", option_b: "Different number of neutrons", option_c: "Different number of protons", option_d: "Different chemical properties", correct_answer: "B", explanation: "Isotopes have same Z but different A (different neutrons).", topics: ["atomic_structure"] },

  // ============ BIOLOGY (30 questions) ============
  { subject: "biology", year: 2024, question: "The site of protein synthesis in a cell is the:", option_a: "Nucleus", option_b: "Ribosome", option_c: "Mitochondria", option_d: "Golgi apparatus", correct_answer: "B", explanation: "Ribosomes are the sites of protein synthesis.", topics: ["cell_biology"] },
  { subject: "biology", year: 2023, question: "Which blood group is the universal donor?", option_a: "A", option_b: "B", option_c: "AB", option_d: "O", correct_answer: "D", explanation: "Blood group O has no A or B antigens — safe for all recipients.", topics: ["circulatory_system"] },
  { subject: "biology", year: 2024, question: "Photosynthesis occurs in the:", option_a: "Mitochondria", option_b: "Chloroplast", option_c: "Ribosome", option_d: "Nucleus", correct_answer: "B", explanation: "Chloroplasts contain chlorophyll for photosynthesis.", topics: ["plant_biology"] },
  { subject: "biology", year: 2023, question: "Which hormone regulates blood sugar level?", option_a: "Thyroxine", option_b: "Adrenaline", option_c: "Insulin", option_d: "Growth hormone", correct_answer: "C", explanation: "Insulin lowers blood glucose by promoting cellular uptake.", topics: ["homeostasis"] },
  { subject: "biology", year: 2024, question: "The structure that carries impulse from one neuron to another is the:", option_a: "Axon", option_b: "Dendrite", option_c: "Synapse", option_d: "Cell body", correct_answer: "C", explanation: "The synapse is the gap where neurotransmitters cross.", topics: ["nervous_system"] },
  { subject: "biology", year: 2023, question: "Which of these is a function of the white blood cell?", option_a: "Transport oxygen", option_b: "Fight infection", option_c: "Carry nutrients", option_d: "Clot blood", correct_answer: "B", explanation: "WBCs are part of the immune system — they fight pathogens.", topics: ["immunity"] },
  { subject: "biology", year: 2024, question: "The gene responsible for sickle cell anaemia is located on:", option_a: "X chromosome", option_b: "Y chromosome", option_c: "Autosome", option_d: "Mitochondrial DNA", correct_answer: "C", explanation: "Sickle cell is autosomal recessive (chromosome 11).", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "Which of the following is NOT a component of the mammalian heart?", option_a: "Tricuspid valve", option_b: "Bicuspid valve", option_c: "Semi-lunar valve", option_d: "Hepatic valve", correct_answer: "D", explanation: "There is no 'hepatic valve' in the heart.", topics: ["circulatory_system"] },
  { subject: "biology", year: 2024, question: "In a cross between Tt and Tt, the expected phenotypic ratio is:", option_a: "1:1", option_b: "1:2:1", option_c: "3:1", option_d: "9:3:3:1", correct_answer: "C", explanation: "3 dominant (TT + Tt) : 1 recessive (tt) = 3:1.", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "The primary function of the large intestine is:", option_a: "Digest proteins", option_b: "Absorb water", option_c: "Absorb glucose", option_d: "Secrete bile", correct_answer: "B", explanation: "The large intestine absorbs water and electrolytes from undigested food.", topics: ["digestive_system"] },
  { subject: "biology", year: 2024, question: "Which of the following organisms is a producer?", option_a: "Lion", option_b: "Grass", option_c: "Mushroom", option_d: "Eagle", correct_answer: "B", explanation: "Grass is a producer — it makes its own food via photosynthesis.", topics: ["ecology"] },
  { subject: "biology", year: 2023, question: "The process by which water moves from a region of high concentration to low through a semipermeable membrane is:", option_a: "Diffusion", option_b: "Osmosis", option_c: "Active transport", option_d: "Facilitated diffusion", correct_answer: "B", explanation: "Osmosis is specifically the movement of water across a semipermeable membrane.", topics: ["cell_biology"] },
  { subject: "biology", year: 2024, question: "The human egg cell contains how many chromosomes?", option_a: "23", option_b: "44", option_c: "46", option_d: "48", correct_answer: "A", explanation: "Human gametes are haploid (23 chromosomes).", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "Bile is produced by the:", option_a: "Pancreas", option_b: "Stomach", option_c: "Liver", option_d: "Small intestine", correct_answer: "C", explanation: "The liver produces bile, which is stored in the gall bladder.", topics: ["digestive_system"] },
  { subject: "biology", year: 2024, question: "The process of converting glucose into ethanol in the absence of oxygen is called:", option_a: "Aerobic respiration", option_b: "Fermentation", option_c: "Photosynthesis", option_d: "Decomposition", correct_answer: "B", explanation: "Fermentation is anaerobic respiration producing ethanol + CO₂.", topics: ["respiration"] },
  { subject: "biology", year: 2023, question: "Which of the following is an example of mutualism?", option_a: "Tapeworm in human intestine", option_b: "Lion eating a zebra", option_c: "Bee and flower", option_d: "Mistletoe on a tree", correct_answer: "C", explanation: "Bees get nectar, flowers get pollinated — both benefit.", topics: ["ecology"] },
  { subject: "biology", year: 2024, question: "DNA replication occurs during which phase of cell division?", option_a: "Prophase", option_b: "Metaphase", option_c: "S phase of interphase", option_d: "Telophase", correct_answer: "C", explanation: "DNA replicates during the S (synthesis) phase of interphase.", topics: ["cell_biology"] },
  { subject: "biology", year: 2023, question: "Which organ filters blood and produces urine?", option_a: "Liver", option_b: "Kidney", option_c: "Spleen", option_d: "Lung", correct_answer: "B", explanation: "The kidneys filter blood in nephrons to produce urine.", topics: ["excretion"] },
  { subject: "biology", year: 2024, question: "The term 'phenotype' refers to:", option_a: "Genetic makeup", option_b: "Physical appearance", option_c: "Chromosome number", option_d: "DNA sequence", correct_answer: "B", explanation: "Phenotype = observable traits (vs genotype = genetic makeup).", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "The function of chlorophyll in photosynthesis is to:", option_a: "Release oxygen", option_b: "Absorb light energy", option_c: "Fix carbon dioxide", option_d: "Produce glucose", correct_answer: "B", explanation: "Chlorophyll absorbs light energy for the light-dependent reactions.", topics: ["plant_biology"] },
  { subject: "biology", year: 2024, question: "Which of the following is a characteristic of viruses?", option_a: "They have cells", option_b: "They reproduce independently", option_c: "They have DNA or RNA", option_d: "They have ribosomes", correct_answer: "C", explanation: "Viruses have genetic material (DNA or RNA) but no cellular structure.", topics: ["classification"] },
  { subject: "biology", year: 2023, question: "The part of the brain that controls balance and coordination is the:", option_a: "Cerebrum", option_b: "Cerebellum", option_c: "Medulla oblongata", option_d: "Hypothalamus", correct_answer: "B", explanation: "The cerebellum coordinates voluntary movements and balance.", topics: ["nervous_system"] },
  { subject: "biology", year: 2024, question: "Which gas is taken in during inhalation and used in respiration?", option_a: "Carbon dioxide", option_b: "Nitrogen", option_c: "Oxygen", option_d: "Hydrogen", correct_answer: "C", explanation: "Oxygen is used in aerobic respiration to break down glucose.", topics: ["respiration"] },
  { subject: "biology", year: 2023, question: "The process by which neutrophils engulf bacteria is called:", option_a: "Antibody production", option_b: "Phagocytosis", option_c: "Opsonization", option_d: "Agglutination", correct_answer: "B", explanation: "Phagocytosis = engulfing and digesting pathogens.", topics: ["immunity"] },
  { subject: "biology", year: 2024, question: "Which of the following is NOT a sexually transmitted infection?", option_a: "Gonorrhoea", option_b: "Syphilis", option_c: "Malaria", option_d: "HIV/AIDS", correct_answer: "C", explanation: "Malaria is transmitted by Anopheles mosquitoes, not sexually.", topics: ["immunity"] },
  { subject: "biology", year: 2023, question: "The main function of the xylem tissue in plants is to:", option_a: "Transport food", option_b: "Transport water and minerals", option_c: "Store food", option_d: "Provide flexibility", correct_answer: "B", explanation: "Xylem transports water and dissolved minerals from roots to leaves.", topics: ["plant_biology"] },
  { subject: "biology", year: 2024, question: "A population is defined as:", option_a: "All organisms in an area", option_b: "All species in an area", option_c: "All individuals of one species in an area", option_d: "All communities in an area", correct_answer: "C", explanation: "Population = all individuals of ONE species in a given area.", topics: ["ecology"] },
  { subject: "biology", year: 2023, question: "Which blood vessels carry blood AWAY from the heart?", option_a: "Veins", option_b: "Capillaries", option_c: "Venules", option_d: "Arteries", correct_answer: "D", explanation: "Arteries carry blood away from the heart (usually oxygenated).", topics: ["circulatory_system"] },
  { subject: "biology", year: 2024, question: "The deficiency of vitamin C causes:", option_a: "Rickets", option_b: "Scurvy", option_c: "Beriberi", option_d: "Pellagra", correct_answer: "B", explanation: "Scurvy is caused by vitamin C deficiency (bleeding gums, weakness).", topics: ["nutrition"] },
  { subject: "biology", year: 2023, question: "In which part of the alimentary canal does most chemical digestion occur?", option_a: "Stomach", option_b: "Mouth", option_c: "Duodenum", option_d: "Oesophagus", correct_answer: "C", explanation: "The duodenum receives bile and pancreatic juice for complete digestion.", topics: ["digestive_system"] },

  // ============ ENGLISH (20 questions) ============
  { subject: "english", year: 2024, question: "Choose the option that best completes: 'She ___ to school every day.'", option_a: "go", option_b: "goes", option_c: "going", option_d: "gone", correct_answer: "B", explanation: "Third person singular present tense requires 'goes'.", topics: ["sentence_completion"] },
  { subject: "english", year: 2023, question: "The synonym of 'eloquent' is:", option_a: "Silent", option_b: "Fluent", option_c: "Rude", option_d: "Slow", correct_answer: "B", explanation: "Eloquent = fluent or persuasive in speaking or writing.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Choose the correctly spelt word:", option_a: "Occurence", option_b: "Occurrence", option_c: "Ocurrence", option_d: "Occurrance", correct_answer: "B", explanation: "Occurrence — double r, single c.", topics: ["spelling"] },
  { subject: "english", year: 2023, question: "Identify the figure of speech: 'The wind whispered through the trees.'", option_a: "Simile", option_b: "Metaphor", option_c: "Personification", option_d: "Hyperbole", correct_answer: "C", explanation: "Giving human quality (whisper) to non-human (wind) = personification.", topics: ["figures_of_speech"] },
  { subject: "english", year: 2024, question: "'Neither the students nor the teacher ___ present.' Choose the correct verb:", option_a: "were", option_b: "are", option_c: "was", option_d: "have been", correct_answer: "C", explanation: "With 'neither...nor', the verb agrees with the nearer subject (teacher = singular).", topics: ["sentence_completion"] },
  { subject: "english", year: 2023, question: "The antonym of 'benevolent' is:", option_a: "Kind", option_b: "Generous", option_c: "Malevolent", option_d: "Gentle", correct_answer: "C", explanation: "Benevolent = kind; malevolent = evil/wishing harm.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Choose the correct option: 'I would have helped if I ___ known.'", option_a: "have", option_b: "had", option_c: "was", option_d: "did", correct_answer: "B", explanation: "Third conditional: 'if I had known' (past perfect).", topics: ["tenses"] },
  { subject: "english", year: 2023, question: "The word 'administer' has stress on which syllable?", option_a: "First", option_b: "Second", option_c: "Third", option_d: "Fourth", correct_answer: "B", explanation: "ad-MIN-ister — stress is on the second syllable.", topics: ["stress"] },
  { subject: "english", year: 2024, question: "Choose the option with the correct punctuation:", option_a: "Stop! he shouted.", option_b: "\"Stop!\" he shouted.", option_c: "\"Stop!\" He shouted.", option_d: "Stop, he shouted.", correct_answer: "B", explanation: "Direct speech: \"Stop!\" he shouted. (Exclamation in quotes, lowercase after.)", topics: ["punctuation"] },
  { subject: "english", year: 2023, question: "The passive voice of 'The police caught the thief' is:", option_a: "The thief was caught by the police.", option_b: "The thief is caught by the police.", option_c: "The thief has been caught by the police.", option_d: "The police was caught by the thief.", correct_answer: "A", explanation: "Simple past passive: object + was/were + past participle + by + agent.", topics: ["voice"] },
  { subject: "english", year: 2024, question: "Choose the correct option: 'Every student ___ a textbook.'", option_a: "have", option_b: "has", option_c: "having", option_d: "having had", correct_answer: "B", explanation: "'Every' takes a singular verb — 'has'.", topics: ["agreement"] },
  { subject: "english", year: 2023, question: "The word 'ubiquitous' means:", option_a: "Rare", option_b: "Present everywhere", option_c: "Unique", option_d: "Useful", correct_answer: "B", explanation: "Ubiquitous = found everywhere.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Which sentence is grammatically correct?", option_a: "Him and me went to the market.", option_b: "He and I went to the market.", option_c: "He and me went to the market.", option_d: "Him and I went to the market.", correct_answer: "B", explanation: "Subject pronouns: 'He and I' (not 'him' or 'me' as subjects).", topics: ["pronouns"] },
  { subject: "english", year: 2023, question: "The plural of 'mouse' is:", option_a: "Mouses", option_b: "Mice", option_c: "Mices", option_d: "Mousies", correct_answer: "B", explanation: "Mouse → mice (irregular plural).", topics: ["plurals"] },
  { subject: "english", year: 2024, question: "Choose the correct option: 'If I ___ rich, I would travel the world.'", option_a: "am", option_b: "was", option_c: "were", option_d: "be", correct_answer: "C", explanation: "Second conditional uses 'were' for all subjects (subjunctive mood).", topics: ["tenses"] },
  { subject: "english", year: 2023, question: "The word 'ephemeral' means:", option_a: "Eternal", option_b: "Short-lived", option_c: "Enormous", option_d: "Essential", correct_answer: "B", explanation: "Ephemeral = lasting for a very short time.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Choose the option with the correct indirect speech: He said, 'I am tired.'", option_a: "He said that he is tired.", option_b: "He said that he was tired.", option_c: "He said that I am tired.", option_d: "He said I was tired.", correct_answer: "B", explanation: "Direct → indirect: 'am' becomes 'was' (backshift).", topics: ["reported_speech"] },
  { subject: "english", year: 2023, question: "Which word is an adverb in: 'She sang beautifully'?", option_a: "She", option_b: "Sang", option_c: "Beautifully", option_d: "None", correct_answer: "C", explanation: "'Beautifully' modifies the verb 'sang' — it is an adverb.", topics: ["parts_of_speech"] },
  { subject: "english", year: 2024, question: "The idiom 'to burn the midnight oil' means:", option_a: "To waste resources", option_b: "To work late at night", option_c: "To start a fire", option_d: "To be angry", correct_answer: "B", explanation: "The idiom means to work or study late into the night.", topics: ["idioms"] },
  { subject: "english", year: 2023, question: "Choose the correct option: 'The book is ___ the table.'", option_a: "in", option_b: "at", option_c: "on", option_d: "by", correct_answer: "C", explanation: "Books rest ON surfaces.", topics: ["prepositions"] },

  // ============ MATHEMATICS (20 questions) ============
  { subject: "mathematics", year: 2024, question: "If 3x + 5 = 20, find x.", option_a: "3", option_b: "5", option_c: "7", option_d: "15", correct_answer: "B", explanation: "3x = 20 − 5 = 15 → x = 15/3 = 5." },
  { subject: "mathematics", year: 2023, question: "The factorization of x² − 9 is:", option_a: "(x−3)²", option_b: "(x+3)²", option_c: "(x−3)(x+3)", option_d: "(x−9)(x+1)", correct_answer: "C", explanation: "Difference of two squares: a² − b² = (a−b)(a+b)." },
  { subject: "mathematics", year: 2024, question: "Solve: 2(x − 3) = 8.", option_a: "x = 5", option_b: "x = 7", option_c: "x = 4", option_d: "x = 11", correct_answer: "B", explanation: "2x − 6 = 8 → 2x = 14 → x = 7." },
  { subject: "mathematics", year: 2023, question: "The probability of throwing a fair die and getting a 4 is:", option_a: "1/2", option_b: "1/3", option_c: "1/4", option_d: "1/6", correct_answer: "D", explanation: "One favorable outcome out of 6 possible outcomes." },
  { subject: "mathematics", year: 2024, question: "The gradient of the line y = 3x + 7 is:", option_a: "7", option_b: "3", option_c: "10", option_d: "−3", correct_answer: "B", explanation: "In y = mx + c, m (gradient) = 3." },
  { subject: "mathematics", year: 2023, question: "Convert 110 base 2 to base 10.", option_a: "4", option_b: "5", option_c: "6", option_d: "7", correct_answer: "C", explanation: "1×4 + 1×2 + 0×1 = 4 + 2 = 6." },
  { subject: "mathematics", year: 2024, question: "If log₂x = 5, find x.", option_a: "10", option_b: "25", option_c: "32", option_d: "64", correct_answer: "C", explanation: "x = 2⁵ = 32." },
  { subject: "mathematics", year: 2023, question: "The sum of angles in a triangle is:", option_a: "90°", option_b: "180°", option_c: "270°", option_d: "360°", correct_answer: "B", explanation: "The interior angles of any triangle sum to 180°." },
  { subject: "mathematics", year: 2024, question: "Simplify: (3/4) ÷ (2/5).", option_a: "3/10", option_b: "6/20", option_c: "15/8", option_d: "8/15", correct_answer: "C", explanation: "(3/4) × (5/2) = 15/8." },
  { subject: "mathematics", year: 2023, question: "The area of a circle with radius 7 cm (use π = 22/7) is:", option_a: "44 cm²", option_b: "154 cm²", option_c: "88 cm²", option_d: "308 cm²", correct_answer: "B", explanation: "A = πr² = (22/7) × 49 = 154 cm²." },
  { subject: "mathematics", year: 2024, question: "Solve simultaneously: x + y = 7, x − y = 3.", option_a: "x=5, y=2", option_b: "x=4, y=3", option_c: "x=3, y=4", option_d: "x=6, y=1", correct_answer: "A", explanation: "Adding: 2x = 10 → x = 5, y = 7 − 5 = 2." },
  { subject: "mathematics", year: 2023, question: "The median of 3, 5, 7, 9, 11 is:", option_a: "5", option_b: "7", option_c: "9", option_d: "6", correct_answer: "B", explanation: "Middle value of ordered data: 7." },
  { subject: "mathematics", year: 2024, question: "The simple interest on ₦5000 at 10% per annum for 3 years is:", option_a: "₦500", option_b: "₦1000", option_c: "₦1500", option_d: "₦2000", correct_answer: "C", explanation: "I = PRT/100 = 5000 × 10 × 3/100 = ₦1500." },
  { subject: "mathematics", year: 2023, question: "The derivative of x³ is:", option_a: "x²", option_b: "3x", option_c: "3x²", option_d: "3x³", correct_answer: "C", explanation: "d/dx(xⁿ) = nxⁿ⁻¹ → d/dx(x³) = 3x²." },
  { subject: "mathematics", year: 2024, question: "Evaluate: ∫2x dx.", option_a: "x² + c", option_b: "2x² + c", option_c: "x + c", option_d: "2 + c", correct_answer: "A", explanation: "∫2x dx = 2(x²/2) + c = x² + c." },
  { subject: "mathematics", year: 2023, question: "A polygon has 8 sides. The sum of its interior angles is:", option_a: "720°", option_b: "900°", option_c: "1080°", option_d: "1260°", correct_answer: "C", explanation: "(n−2)×180 = (8−2)×180 = 1080°." },
  { subject: "mathematics", year: 2024, question: "If sin θ = 3/5, find cos θ.", option_a: "4/5", option_b: "3/4", option_c: "5/3", option_d: "5/4", correct_answer: "A", explanation: "cos θ = √(1 − sin²θ) = √(1 − 9/25) = √(16/25) = 4/5." },
  { subject: "mathematics", year: 2023, question: "The HCF of 12 and 18 is:", option_a: "3", option_b: "6", option_c: "12", option_d: "36", correct_answer: "B", explanation: "12 = 2²×3, 18 = 2×3², HCF = 2×3 = 6." },
  { subject: "mathematics", year: 2024, question: "Express 0.75 as a fraction in its simplest form.", option_a: "3/4", option_b: "75/100", option_c: "7/10", option_d: "3/5", correct_answer: "A", explanation: "0.75 = 75/100 = 3/4." },
  { subject: "mathematics", year: 2023, question: "The distance between points (1,2) and (4,6) is:", option_a: "3", option_b: "4", option_c: "5", option_d: "7", correct_answer: "C", explanation: "d = √[(4−1)² + (6−2)²] = √[9+16] = √25 = 5." },

  // ============ GOVERNMENT (20 questions) ============
  { subject: "government", year: 2024, question: "The 1999 Constitution of Nigeria came into effect on:", option_a: "October 1, 1960", option_b: "May 29, 1999", option_c: "January 1, 2000", option_d: "June 12, 1993", correct_answer: "B", explanation: "The 1999 Constitution took effect on 29 May 1999." },
  { subject: "government", year: 2023, question: "Which of the following is a feature of federalism?", option_a: "Single central government", option_b: "Division of power between levels of government", option_c: "No state governments", option_d: "Absolute power at the centre", correct_answer: "B", explanation: "Federalism involves division of powers between central and state/regional governments." },
  { subject: "government", year: 2024, question: "The Independent National Electoral Commission (INEC) was established in:", option_a: "1960", option_b: "1978", option_c: "1999", option_d: "2010", correct_answer: "B", explanation: "INEC was established by the 1979 Constitution (initially as Federal Electoral Commission)." },
  { subject: "government", year: 2023, question: "Democracy is defined as:", option_a: "Rule by the military", option_b: "Government of the people, by the people, for the people", option_c: "Rule by a single party", option_d: "Government by the elite", correct_answer: "B", explanation: "Classic Lincoln definition of democracy." },
  { subject: "government", year: 2024, question: "A unitary system of government is one where:", option_a: "Power is shared between centres", option_b: "All power is concentrated at the centre", option_c: "States have more power", option_d: "Military rules", correct_answer: "B", explanation: "In a unitary system, the central government holds supreme authority." },
  { subject: "government", year: 2023, question: "Which of the following is NOT a function of the legislature?", option_a: "Law making", option_b: "Budget approval", option_c: "Implementation of laws", option_d: "Oversight of executive", correct_answer: "C", explanation: "Implementation is the function of the executive, not the legislature." },
  { subject: "government", year: 2024, question: "Nigeria operated a parliamentary system during the:", option_a: "First Republic (1963–66)", option_b: "Second Republic (1979–83)", option_c: "Third Republic (1993)", option_d: "Fourth Republic (1999–present)", correct_answer: "A", explanation: "Nigeria used a parliamentary system in the First Republic (Westminster model)." },
  { subject: "government", year: 2023, question: "A bill that has been passed by both houses of the National Assembly is called:", option_a: "White paper", option_b: "Executive bill", option_c: "Act of Parliament", option_d: "Green paper", correct_answer: "C", explanation: "A bill becomes an Act after presidential assent." },
  { subject: "government", year: 2024, question: "The body responsible for interpreting the constitution in Nigeria is the:", option_a: "Executive", option_b: "Legislature", option_c: "Judiciary", option_d: "INEC", correct_answer: "C", explanation: "The judiciary interprets laws and the constitution." },
  { subject: "government", year: 2023, question: "Which of the following is a characteristic of a democratic government?", option_a: "Rule of force", option_b: "Free and fair elections", option_c: "Censorship of press", option_d: "One-party system", correct_answer: "B", explanation: "Free and fair elections are a hallmark of democracy." },
  { subject: "government", year: 2024, question: "The Nigerian Senate has how many members?", option_a: "109", option_b: "360", option_c: "369", option_d: "250", correct_answer: "A", explanation: "The Senate has 109 members: 3 per state + 1 for FCT." },
  { subject: "government", year: 2023, question: "Political socialization refers to:", option_a: "Running for office", option_b: "The process of acquiring political attitudes and values", option_c: "Voting behavior", option_d: "Campaigning", correct_answer: "B", explanation: "Political socialization is how individuals develop their political beliefs." },
  { subject: "government", year: 2024, question: "Which is NOT a function of the executive?", option_a: "Implementation of policies", option_b: "Making laws", option_c: "Maintenance of law and order", option_d: "Foreign affairs", correct_answer: "B", explanation: "Making laws is a legislative function." },
  { subject: "government", year: 2023, question: "The concept of 'separation of powers' means:", option_a: "Power is shared equally", option_b: "Each arm of government is independent in its functions", option_c: "One arm controls all others", option_d: "Power is given to the military", correct_answer: "B", explanation: "Separation of powers ensures independence of legislature, executive, and judiciary." },
  { subject: "government", year: 2024, question: "The National Assembly consists of:", option_a: "Senate only", option_b: "House of Representatives only", option_c: "Senate and House of Representatives", option_d: "Senate and State Assemblies", correct_answer: "C", explanation: "The National Assembly is bicameral: Senate + House of Representatives." },
  { subject: "government", year: 2023, question: "A citizen is a person who:", option_a: "Lives in a country", option_b: "Has legal membership and rights in a country", option_c: "Has a passport", option_d: "Was born in a country", correct_answer: "B", explanation: "Citizenship implies legal membership with rights and obligations." },
  { subject: "government", year: 2024, question: "Which of these is NOT a function of local government?", option_a: "Providing local roads", option_b: "Collecting rates and taxes", option_c: "Declaring war", option_d: "Maintaining primary education", correct_answer: "C", explanation: "Declaring war is a federal function." },
  { subject: "government", year: 2023, question: "The electoral system used in Nigeria is:", option_a: "Proportional representation", option_b: "First-past-the-post", option_c: "Alternative vote", option_d: "Single transferable vote", correct_answer: "B", explanation: "Nigeria uses the simple majority (first-past-the-post) system." },
  { subject: "government", year: 2024, question: "Pressure groups differ from political parties in that:", option_a: "They contest elections", option_b: "They seek to influence government policy without seeking office", option_c: "They have a manifesto", option_d: "They nominate candidates", correct_answer: "B", explanation: "Pressure groups influence policy but do not contest elections." },
  { subject: "government", year: 2023, question: "The Nigerian civil war (1967–70) was fought between:", option_a: "North and South", option_b: "Federal government and Biafra", option_c: "Army and Navy", option_d: "Two political parties", correct_answer: "B", explanation: "The war was between the Federal Government and the secessionist state of Biafra." },

  // ============ ECONOMICS (20 questions) ============
  { subject: "economics", year: 2024, question: "Scarcity in economics means:", option_a: "Goods are expensive", option_b: "Resources are limited while wants are unlimited", option_c: "People are poor", option_d: "There is no production", correct_answer: "B", explanation: "Scarcity = unlimited wants vs limited resources." },
  { subject: "economics", year: 2023, question: "The factor of production that organizes other factors is:", option_a: "Land", option_b: "Labour", option_c: "Capital", option_d: "Entrepreneur", correct_answer: "D", explanation: "The entrepreneur combines and organizes the other factors of production." },
  { subject: "economics", year: 2024, question: "A normal good is one where demand:", option_a: "Falls when income rises", option_b: "Rises when income rises", option_c: "Does not change with income", option_d: "Is always zero", correct_answer: "B", explanation: "Normal goods have positive income elasticity — demand rises with income." },
  { subject: "economics", year: 2023, question: "The market where many sellers and many buyers exist is:", option_a: "Monopoly", option_b: "Oligopoly", option_c: "Perfect competition", option_d: "Monopsony", correct_answer: "C", explanation: "Perfect competition has many buyers and sellers with homogeneous products." },
  { subject: "economics", year: 2024, question: "Depreciation refers to:", option_a: "Increase in asset value", option_b: "Decrease in the value of an asset over time", option_c: "Rise in price level", option_d: "Fall in demand", correct_answer: "B", explanation: "Depreciation = reduction in the value of fixed assets through wear and tear." },
  { subject: "economics", year: 2023, question: "Which is an example of a direct tax?", option_a: "VAT", option_b: "Customs duty", option_c: "Company income tax", option_d: "Excise duty", correct_answer: "C", explanation: "Company income tax is levied directly on income/profits." },
  { subject: "economics", year: 2024, question: "The law of diminishing returns states that:", option_a: "Output always increases", option_b: "Adding more of a variable factor eventually gives smaller increases in output", option_c: "Costs always decrease", option_d: "Demand always falls", correct_answer: "B", explanation: "As more units of a variable factor are added to fixed factors, marginal product eventually declines." },
  { subject: "economics", year: 2023, question: "Which of the following is a function of money?", option_a: "Medium of exchange", option_b: "Source of power", option_c: "Means of production", option_d: "Factor of production", correct_answer: "A", explanation: "Money serves as medium of exchange, store of value, unit of account, and standard of deferred payment." },
  { subject: "economics", year: 2024, question: "Balance of payments records:", option_a: "Only imports", option_b: "Only exports", option_c: "All economic transactions between a country and the rest of the world", option_d: "Only foreign aid", correct_answer: "C", explanation: "BoP is a comprehensive record of all international economic transactions." },
  { subject: "economics", year: 2023, question: "Which organization is responsible for monetary policy in Nigeria?", option_a: "Federal Ministry of Finance", option_b: "Central Bank of Nigeria", option_c: "Nigeria Deposit Insurance Corporation", option_d: "Securities and Exchange Commission", correct_answer: "B", explanation: "The CBN formulates and implements monetary policy." },
  { subject: "economics", year: 2024, question: "An isoquant shows:", option_a: "Different quantities of output at different prices", option_b: "Combinations of inputs that produce the same output", option_c: "Consumer preferences", option_d: "Market equilibrium", correct_answer: "B", explanation: "Isoquant = equal output curve showing input combinations." },
  { subject: "economics", year: 2023, question: "The multiplier effect means:", option_a: "Money supply decreases", option_b: "An initial increase in spending leads to a larger final increase in national income", option_c: "Tax increases", option_d: "Prices fall", correct_answer: "B", explanation: "The multiplier = 1/(1−MPC). Initial spending creates a chain of further spending." },
  { subject: "economics", year: 2024, question: "Which is NOT a component of aggregate demand?", option_a: "Consumption", option_b: "Investment", option_c: "Savings", option_d: "Government spending", correct_answer: "C", explanation: "AD = C + I + G + (X−M). Savings is a leakage, not a component." },
  { subject: "economics", year: 2023, question: "Elastic demand means:", option_a: "Quantity demanded changes proportionally less than price", option_b: "Quantity demanded changes proportionally more than price", option_c: "Quantity demanded does not change", option_d: "Price is fixed", correct_answer: "B", explanation: "Elastic demand: PED > 1, quantity responds significantly to price changes." },
  { subject: "economics", year: 2024, question: "Comparative advantage means:", option_a: "Having more resources", option_b: "Being able to produce at a lower opportunity cost", option_c: "Producing more than others", option_d: "Having cheaper labour", correct_answer: "B", explanation: "A country has comparative advantage when it can produce at a lower opportunity cost." },
  { subject: "economics", year: 2023, question: "GDP at market price includes:", option_a: "Only government spending", option_b: "Total value of all final goods and services produced in a country", option_c: "Only exports", option_d: "Only investment", correct_answer: "B", explanation: "GDP = total value of all final goods/services produced within a country's borders." },
  { subject: "economics", year: 2024, question: "The Phillips curve shows the relationship between:", option_a: "GDP and inflation", option_b: "Unemployment and inflation", option_c: "Interest rate and savings", option_d: "Supply and demand", correct_answer: "B", explanation: "The Phillips curve shows an inverse relationship between unemployment and inflation." },
  { subject: "economics", year: 2023, question: "Which is a function of commercial banks?", option_a: "Issuing currency", option_b: "Accepting deposits and granting loans", option_c: "Implementing monetary policy", option_d: "Regulating the financial system", correct_answer: "B", explanation: "Commercial banks accept deposits and make loans." },
  { subject: "economics", year: 2024, question: "Devaluation of the naira means:", option_a: "Increase in the value of naira", option_b: "Deliberate reduction in the official value of naira", option_c: "Increase in foreign reserves", option_d: "Fall in import prices", correct_answer: "B", explanation: "Devaluation is a deliberate downward adjustment of the currency's official value." },
  { subject: "economics", year: 2023, question: "The concept of opportunity cost is best illustrated by:", option_a: "The total cost of production", option_b: "What is given up to produce one more unit of a good", option_c: "The price of goods", option_d: "Revenue earned", correct_answer: "B", explanation: "Opportunity cost = value of the next best alternative forgone." },

  // ============ LITERATURE (15 questions) ============
  { subject: "literature", year: 2024, question: "In literature, 'irony' means:", option_a: "Being funny", option_b: "A contrast between expectation and reality", option_c: "Telling a lie", option_d: "Using big words", correct_answer: "B", explanation: "Irony involves a discrepancy between what is expected and what actually happens." },
  { subject: "literature", year: 2023, question: "A protagonist is:", option_a: "The villain", option_b: "The main character", option_c: "The narrator", option_d: "The setting", correct_answer: "B", explanation: "The protagonist is the central character in a story." },
  { subject: "literature", year: 2024, question: "'It was the best of times, it was the worst of times' is an example of:", option_a: "Simile", option_b: "Oxymoron", option_c: "Antithesis", option_d: "Alliteration", correct_answer: "C", explanation: "Antithesis places opposite ideas in parallel structure for contrast." },
  { subject: "literature", year: 2023, question: "A monologue is:", option_a: "A dialogue between two characters", option_b: "A long speech by one character", option_c: "A poem with no rhythm", option_d: "A type of novel", correct_answer: "B", explanation: "A monologue is an extended speech by one character in a play or poem." },
  { subject: "literature", year: 2024, question: "Setting in a novel refers to:", option_a: "The plot", option_b: "The time and place of the story", option_c: "The characters", option_d: "The theme", correct_answer: "B", explanation: "Setting is the time, place, and environment in which a story takes place." },
  { subject: "literature", year: 2023, question: "An allegory is:", option_a: "A type of poem", option_b: "A story with a hidden moral or political meaning", option_c: "A comedy", option_d: "A short story", correct_answer: "B", explanation: "An allegory is a narrative where characters and events symbolize deeper meanings." },
  { subject: "literature", year: 2024, question: "The theme of a literary work is:", option_a: "The setting", option_b: "The main idea or message", option_c: "The first chapter", option_d: "The author's name", correct_answer: "B", explanation: "Theme is the central message or insight about life conveyed by the work." },
  { subject: "literature", year: 2023, question: "Dramatic monologue was popularized by:", option_a: "William Shakespeare", option_b: "Robert Browning", option_c: "John Keats", option_d: "William Wordsworth", correct_answer: "B", explanation: "Robert Browning perfected the dramatic monologue form." },
  { subject: "literature", year: 2024, question: "Which is NOT a type of conflict in literature?", option_a: "Man vs. nature", option_b: "Man vs. man", option_c: "Man vs. society", option_d: "Man vs. author", correct_answer: "D", explanation: "Common conflicts: man vs. man, nature, society, self, fate, technology." },
  { subject: "literature", year: 2023, question: "Foreshadowing is:", option_a: "Looking back at events", option_b: "Giving hints about what will happen later", option_c: "Describing the setting", option_d: "A type of character", correct_answer: "B", explanation: "Foreshadowing provides clues about events that will occur later in the story." },
  { subject: "literature", year: 2024, question: "The denouement is:", option_a: "The beginning of a story", option_b: "The climax", option_c: "The resolution of the plot", option_d: "The rising action", correct_answer: "C", explanation: "Denouement is the final part where loose ends are tied up." },
  { subject: "literature", year: 2023, question: "A stanza in poetry is a:", option_a: "Line", option_b: "Group of lines", option_c: "Single word", option_d: "Paragraph", correct_answer: "B", explanation: "A stanza is a grouped set of lines in a poem, like a verse." },
  { subject: "literature", year: 2024, question: "Which literary device uses 'like' or 'as' for comparison?", option_a: "Metaphor", option_b: "Simile", option_c: "Hyperbole", option_d: "Personification", correct_answer: "B", explanation: "A simile compares two things using 'like' or 'as'." },
  { subject: "literature", year: 2023, question: "Pathetic fallacy is:", option_a: "A fallacy in logic", option_b: "Attributing human emotions to nature", option_c: "A type of rhyme", option_d: "A character flaw", correct_answer: "B", explanation: "Pathetic fallacy = attributing human feelings to nature (e.g., 'angry storm')." },
  { subject: "literature", year: 2024, question: "Which of these is a prose form?", option_a: "Sonnet", option_b: "Haiku", option_c: "Novel", option_d: "Ballad", correct_answer: "C", explanation: "A novel is a long prose narrative. The others are poetry forms." },

  // ============ GEOGRAPHY (15 questions) ============
  { subject: "geography", year: 2024, question: "The process of soil formation is called:", option_a: "Erosion", option_b: "Pedogenesis", option_c: "Deposition", option_d: "Weathering", correct_answer: "B", explanation: "Pedogenesis is the process of soil formation from parent rock." },
  { subject: "geography", year: 2023, question: "Which of the following is a renewable resource?", option_a: "Coal", option_b: "Petroleum", option_c: "Solar energy", option_d: "Natural gas", correct_answer: "C", explanation: "Solar energy is inexhaustible and renewable." },
  { subject: "geography", year: 2024, question: "The imaginary line that divides the earth into northern and southern hemispheres is:", option_a: "Prime Meridian", option_b: "Tropic of Cancer", option_c: "Equator", option_d: "Arctic Circle", correct_answer: "C", explanation: "The Equator (0° latitude) divides Earth into Northern and Southern Hemispheres." },
  { subject: "geography", year: 2023, question: "Which climate type has distinct wet and dry seasons?", option_a: "Tropical rainforest", option_b: "Tropical savanna", option_c: "Desert", option_d: "Tundra", correct_answer: "B", explanation: "Savanna climate has wet and dry seasons." },
  { subject: "geography", year: 2024, question: "Urbanization refers to:", option_a: "Rural development", option_b: "The growth of cities and towns", option_c: "Agricultural expansion", option_d: "Deforestation", correct_answer: "B", explanation: "Urbanization = increasing proportion of people living in urban areas." },
  { subject: "geography", year: 2023, question: "Which is the longest river in the world?", option_a: "Amazon", option_b: "Mississippi", option_c: "Nile", option_d: "Niger", correct_answer: "C", explanation: "The Nile is approximately 6,650 km long." },
  { subject: "geography", year: 2024, question: "The international date line passes through:", option_a: "0° longitude", option_b: "180° longitude", option_c: "90° East", option_d: "90° West", correct_answer: "B", explanation: "The International Date Line roughly follows 180° longitude." },
  { subject: "geography", year: 2023, question: "Which of the following is a sedimentary rock?", option_a: "Granite", option_b: "Basalt", option_c: "Limestone", option_d: "Marble", correct_answer: "C", explanation: "Limestone is formed from sedimentary deposits of calcium carbonate." },
  { subject: "geography", year: 2024, question: "The study of earthquakes is called:", option_a: "Meteorology", option_b: "Seismology", option_c: "Volcanology", option_d: "Geology", correct_answer: "B", explanation: "Seismology is the scientific study of earthquakes and seismic waves." },
  { subject: "geography", year: 2023, question: "Which is the largest continent by area?", option_a: "Africa", option_b: "North America", option_c: "Asia", option_d: "Europe", correct_answer: "C", explanation: "Asia is the largest continent with approximately 44.58 million km²." },
  { subject: "geography", year: 2024, question: "The line connecting points of equal temperature on a map is called:", option_a: "Isobar", option_b: "Isotherm", option_c: "Contour", option_d: "Meridian", correct_answer: "B", explanation: "Isotherms connect points of equal temperature." },
  { subject: "geography", year: 2023, question: "Which gas is most abundant in the Earth's atmosphere?", option_a: "Oxygen", option_b: "Carbon dioxide", option_c: "Nitrogen", option_d: "Hydrogen", correct_answer: "C", explanation: "Nitrogen makes up approximately 78% of the atmosphere." },
  { subject: "geography", year: 2024, question: "The Tropic of Capricorn passes through which country?", option_a: "Nigeria", option_b: "South Africa", option_c: "Kenya", option_d: "Egypt", correct_answer: "B", explanation: "The Tropic of Capricorn (23.5°S) passes through South Africa." },
  { subject: "geography", year: 2023, question: "Which of the following is an impact of deforestation?", option_a: "Increased rainfall", option_b: "Soil erosion", option_c: "Lower temperatures", option_d: "More wildlife", correct_answer: "B", explanation: "Deforestation exposes soil to wind and water, causing erosion." },
  { subject: "geography", year: 2024, question: "The prime meridian passes through:", option_a: "Lagos", option_b: "London", option_c: "New York", option_d: "Tokyo", correct_answer: "B", explanation: "The Prime Meridian (0° longitude) passes through Greenwich, London." },

  // ============ NEW: ACCOUNTING (15 questions) ============
  { subject: "accounting", year: 2024, question: "The accounting equation is:", option_a: "Assets = Liabilities + Equity", option_b: "Assets = Revenue − Expenses", option_c: "Assets = Capital + Drawings", option_d: "Assets = Profit + Loss", correct_answer: "A", explanation: "The fundamental accounting equation: Assets = Liabilities + Owner's Equity." },
  { subject: "accounting", year: 2023, question: "Which of the following is a real account?", option_a: "Sales account", option_b: "Rent expense", option_c: "Cash account", option_d: "Commission received", correct_answer: "C", explanation: "Real accounts relate to assets (e.g., cash, equipment) and carry forward balances." },
  { subject: "accounting", year: 2024, question: "Double-entry bookkeeping means:", option_a: "Recording transactions twice", option_b: "Every transaction has equal debit and credit entries", option_c: "Only cash transactions are recorded", option_d: "Two ledgers are used", correct_answer: "B", explanation: "Every transaction affects at least two accounts with equal debits and credits." },
  { subject: "accounting", year: 2023, question: "The trial balance is prepared to:", option_a: "Calculate profit", option_b: "Check if total debits equal total credits", option_c: "Prepare financial statements", option_d: "Record transactions", correct_answer: "B", explanation: "A trial balance ensures debits = credits before preparing financial statements." },
  { subject: "accounting", year: 2024, question: "Depreciation is the:", option_a: "Increase in asset value", option_b: "Systematic allocation of cost over useful life", option_c: "Cash payment for repairs", option_d: "Market value of an asset", correct_answer: "B", explanation: "Depreciation allocates the cost of a fixed asset over its estimated useful life." },
  { subject: "accounting", year: 2023, question: "Which of the following is an income statement item?", option_a: "Equipment", option_b: "Accounts payable", option_c: "Cost of goods sold", option_d: "Retained earnings", correct_answer: "C", explanation: "Cost of goods sold appears on the income statement (not the balance sheet)." },
  { subject: "accounting", year: 2024, question: "The purpose of depreciation is to:", option_a: "Reduce tax by showing fake expenses", option_b: "Match the cost of using an asset with the revenue it generates", option_c: "Increase the cash balance", option_d: "Show the market value of assets", correct_answer: "B", explanation: "Depreciation follows the matching principle — matching cost with revenue." },
  { subject: "accounting", year: 2023, question: "A debit entry in a ledger account increases:", option_a: "Liabilities", option_b: "Revenue", option_c: "Assets", option_d: "Owner's equity", correct_answer: "C", explanation: "Debit increases assets, expenses, and drawings; decreases liabilities, equity, and revenue." },
  { subject: "accounting", year: 2024, question: "The balance sheet shows:", option_a: "Revenue and expenses", option_b: "Assets, liabilities, and equity at a point in time", option_c: "Cash inflows and outflows", option_d: "Profit or loss", correct_answer: "B", explanation: "The balance sheet (statement of financial position) shows the financial position at a date." },
  { subject: "accounting", year: 2023, question: "Capital expenditure is:", option_a: "Day-to-day running costs", option_b: "Spending on long-term assets", option_c: "Payment of salaries", option_d: "Purchase of raw materials", correct_answer: "B", explanation: "Capital expenditure is spending on assets that provide benefit for more than one year." },
  { subject: "accounting", year: 2024, question: "Which of the following is a current liability?", option_a: "Building", option_b: "Loan due in 5 years", option_c: "Accounts payable", option_d: "Machinery", correct_answer: "C", explanation: "Accounts payable is due within one year — a current liability." },
  { subject: "accounting", year: 2023, question: "The income statement shows:", option_a: "Assets and liabilities", option_b: "Revenue and expenses to determine profit/loss", option_c: "Cash balance", option_d: "Owner's investment", correct_answer: "B", explanation: "The income statement (profit and loss account) shows revenues − expenses = profit/loss." },
  { subject: "accounting", year: 2024, question: "Goodwill is:", option_a: "A tangible asset", option_b: "An intangible asset representing reputation and customer loyalty", option_c: "A liability", option_d: "An expense", correct_answer: "B", explanation: "Goodwill is an intangible asset that arises when a business is worth more than its net assets." },
  { subject: "accounting", year: 2023, question: "The cash book records:", option_a: "All transactions", option_b: "Only cash and bank transactions", option_c: "Credit transactions only", option_d: "Non-cash transactions", correct_answer: "B", explanation: "The cash book is a special journal that records all cash receipts and payments." },
  { subject: "accounting", year: 2024, question: "Which accounting principle requires recording revenue when earned?", option_a: "Consistency", option_b: "Matching", option_c: "Revenue recognition", option_d: "Materiality", correct_answer: "C", explanation: "Revenue recognition principle requires revenue to be recorded when earned, not when cash is received." },

  // ============ NEW: COMMERCE (15 questions) ============
  { subject: "commerce", year: 2024, question: "Commerce includes:", option_a: "Only trade", option_b: "Trade and aids to trade", option_c: "Only production", option_d: "Only distribution", correct_answer: "B", explanation: "Commerce = trade (buying and selling) + aids to trade (banking, insurance, transport)." },
  { subject: "commerce", year: 2023, question: "Which of the following is a function of a wholesaler?", option_a: "Selling directly to consumers", option_b: "Breaking bulk for retailers", option_c: "Providing after-sales service", option_d: "Manufacturing goods", correct_answer: "B", explanation: "Wholesalers buy in large quantities and sell in smaller quantities to retailers." },
  { subject: "commerce", year: 2024, question: "A bill of lading is:", option_a: "A receipt for goods shipped by sea", option_b: "A customs document", option_c: "An insurance policy", option_d: "A letter of credit", correct_answer: "A", explanation: "A bill of lading is a document issued by a carrier to acknowledge receipt of cargo for shipment." },
  { subject: "commerce", year: 2023, question: "The stock exchange is a market for:", option_a: "Buying and selling goods", option_b: "Buying and selling securities/shares", option_c: "Foreign exchange only", option_d: "Agricultural products", correct_answer: "B", explanation: "The stock exchange is a secondary market for buying and selling existing securities." },
  { subject: "commerce", year: 2024, question: "Which of the following is NOT an aid to trade?", option_a: "Banking", option_b: "Insurance", option_c: "Manufacturing", option_d: "Transport", correct_answer: "C", explanation: "Manufacturing is a production activity, not an aid to trade." },
  { subject: "commerce", year: 2023, question: "A joint-stock company has:", option_a: "Unlimited liability", option_b: "Limited liability and separate legal personality", option_c: "No shares", option_d: "Only one owner", correct_answer: "B", explanation: "A joint-stock company is a separate legal entity with limited liability for shareholders." },
  { subject: "commerce", year: 2024, question: "FOB (Free on Board) means:", option_a: "Buyer pays all costs", option_b: "Seller pays costs until goods are loaded on ship", option_c: "Goods are delivered free", option_d: "No charges apply", correct_answer: "B", explanation: "FOB means the seller delivers goods on board the vessel at the named port of shipment." },
  { subject: "commerce", year: 2023, question: "A trademark is:", option_a: "A type of patent", option_b: "A legal protection for brand names and logos", option_c: "A business license", option_d: "A type of copyright", correct_answer: "B", explanation: "A trademark protects brand names, logos, and slogans used to identify goods/services." },
  { subject: "commerce", year: 2024, question: "Which of the following is a function of insurance?", option_a: "Providing loans", option_b: "Protecting against financial loss from risks", option_c: "Manufacturing goods", option_d: "Selling products", correct_answer: "B", explanation: "Insurance transfers the risk of financial loss from the insured to the insurer." },
  { subject: "commerce", year: 2023, question: "Entrepot trade is:", option_a: "Trade within a country", option_b: "Importing goods and re-exporting them", option_c: "Trade between two countries", option_d: "Local trade", correct_answer: "B", explanation: "Entrepot trade involves importing goods and re-exporting them after processing or without change." },
  { subject: "commerce", year: 2024, question: "A promissory note is:", option_a: "A promise to deliver goods", option_b: "A written promise to pay a sum of money", option_c: "A type of insurance", option_d: "A bank statement", correct_answer: "B", explanation: "A promissory note is an unconditional written promise to pay a certain sum of money." },
  { subject: "commerce", year: 2023, question: "Which of the following is a characteristic of a partnership?", option_a: "Separate legal entity", option_b: "Mutual agency", option_c: "Limited liability", option_d: "Transferable shares", correct_answer: "B", explanation: "Mutual agency means each partner can bind the partnership in business transactions." },
  { subject: "commerce", year: 2024, question: "A warehouse is used for:", option_a: "Manufacturing goods", option_b: "Storing goods before sale or distribution", option_c: "Selling goods", option_d: "Transporting goods", correct_answer: "B", explanation: "A warehouse is a facility for storing goods safely until they are needed." },
  { subject: "commerce", year: 2023, question: "Customs duty is:", option_a: "A tax on domestic goods", option_b: "A tax on imported or exported goods", option_c: "A payment for services", option_d: "A type of fine", correct_answer: "B", explanation: "Customs duty is a tariff/tax imposed on imports and exports at international borders." },
  { subject: "commerce", year: 2024, question: "Which of the following is a function of advertising?", option_a: "Reducing production costs", option_b: "Informing and persuading potential customers", option_c: "Manufacturing products", option_d: "Distributing goods", correct_answer: "B", explanation: "Advertising communicates product information and persuades consumers to buy." },

  // ============ NEW: CRS (15 questions) ============
  { subject: "crs", year: 2024, question: "The first book of the Bible is:", option_a: "Exodus", option_b: "Genesis", option_c: "Leviticus", option_d: "Numbers", correct_answer: "B", explanation: "Genesis is the first book of the Bible, describing creation and early human history." },
  { subject: "crs", year: 2023, question: "Who led the Israelites out of Egypt?", option_a: "Abraham", option_b: "David", option_c: "Moses", option_d: "Joshua", correct_answer: "C", explanation: "Moses led the Israelites out of Egyptian bondage (the Exodus)." },
  { subject: "crs", year: 2024, question: "The Ten Commandments were given to:", option_a: "Abraham", option_b: "Moses", option_c: "David", option_d: "Solomon", correct_answer: "B", explanation: "God gave the Ten Commandments to Moses on Mount Sinai." },
  { subject: "crs", year: 2023, question: "Which prophet was swallowed by a great fish?", option_a: "Elijah", option_b: "Jonah", option_c: "Isaiah", option_d: "Jeremiah", correct_answer: "B", explanation: "Jonah was swallowed by a great fish for three days and three nights." },
  { subject: "crs", year: 2024, question: "The birthplace of Jesus Christ is:", option_a: "Nazareth", option_b: "Bethlehem", option_c: "Jerusalem", option_d: "Galilee", correct_answer: "B", explanation: "Jesus was born in Bethlehem, as prophesied in the Old Testament." },
  { subject: "crs", year: 2023, question: "Who betrayed Jesus to the Roman soldiers?", option_a: "Peter", option_b: "John", option_c: "Judas Iscariot", option_d: "Thomas", correct_answer: "C", explanation: "Judas Iscariot betrayed Jesus for thirty pieces of silver." },
  { subject: "crs", year: 2024, question: "The resurrection of Jesus is celebrated as:", option_a: "Christmas", option_b: "Easter", option_c: "Pentecost", option_d: "Good Friday", correct_answer: "B", explanation: "Easter celebrates the resurrection of Jesus from the dead." },
  { subject: "crs", year: 2023, question: "Which book contains the Psalms?", option_a: "Proverbs", option_b: "Job", option_c: "Psalms", option_d: "Ecclesiastes", correct_answer: "C", explanation: "The Book of Psalms contains 150 poems and songs used in worship." },
  { subject: "crs", year: 2024, question: "The Great Commission was given by Jesus to:", option_a: "The Pharisees", option_b: "His disciples", option_c: "The Romans", option_d: "The Sadducees", correct_answer: "B", explanation: "Jesus commanded His disciples to go and make disciples of all nations (Matthew 28:19-20)." },
  { subject: "crs", year: 2023, question: "Who was the first king of Israel?", option_a: "David", option_b: "Solomon", option_c: "Saul", option_d: "Rehoboam", correct_answer: "C", explanation: "Saul was anointed as the first king of Israel by Samuel." },
  { subject: "crs", year: 2024, question: "The book of Revelation was written by:", option_a: "Paul", option_b: "Peter", option_c: "John", option_d: "Luke", correct_answer: "C", explanation: "The Apostle John wrote the Book of Revelation while exiled on Patmos." },
  { subject: "crs", year: 2023, question: "Jesus performed His first miracle at:", option_a: "Capernaum", option_b: "Cana", option_c: "Nazareth", option_d: "Jericho", correct_answer: "B", explanation: "Jesus turned water into wine at a wedding in Cana (John 2:1-11)." },
  { subject: "crs", year: 2024, question: "The parable of the prodigal son teaches about:", option_a: "Hard work", option_b: "God's forgiveness and mercy", option_c: "Obedience", option_d: "Wealth", correct_answer: "B", explanation: "The parable illustrates God's unconditional love and forgiveness for repentant sinners." },
  { subject: "crs", year: 2023, question: "Which disciple doubted the resurrection until he saw Jesus?", option_a: "Peter", option_b: "Andrew", option_c: "Thomas", option_d: "Philip", correct_answer: "C", explanation: "Thomas doubted until he saw and touched Jesus' wounds (John 20:24-29)." },
  { subject: "crs", year: 2024, question: "The Pentecost occurred after Jesus':", option_a: "Birth", option_b: "Crucifixion", option_c: "Ascension", option_d: "Baptism", correct_answer: "C", explanation: "The Holy Spirit descended on the disciples at Pentecost, ten days after Jesus' ascension." },

  // ============ NEW: IRS (15 questions) ============
  { subject: "irs", year: 2024, question: "Islam is classified as a:", option_a: "Polytheistic religion", option_b: "Monotheistic religion", option_c: "Atheistic religion", option_d: "Polyandrous religion", correct_answer: "B", explanation: "Islam believes in one God (Allah) — it is strictly monotheistic." },
  { subject: "irs", year: 2023, question: "The holy book of Islam is:", option_a: "Bible", option_b: "Torah", option_c: "Qur'an", option_d: "Bhagavad Gita", correct_answer: "C", explanation: "The Qur'an is the central religious text of Islam, believed to be the word of God." },
  { subject: "irs", year: 2024, question: "How many pillars of Islam are there?", option_a: "4", option_b: "5", option_c: "6", option_d: "7", correct_answer: "B", explanation: "The Five Pillars of Islam are: Shahada, Salat, Zakat, Sawm, and Hajj." },
  { subject: "irs", year: 2023, question: "Zakat refers to:", option_a: "Prayer", option_b: "Fasting", option_c: "Almsgiving/charity", option_d: "Pilgrimage", correct_answer: "C", explanation: "Zakat is the compulsory giving of a fixed proportion of wealth to charity." },
  { subject: "irs", year: 2024, question: "The Prophet Muhammad was born in:", option_a: "Medina", option_b: "Jerusalem", option_c: "Mecca", option_d: "Cairo", correct_answer: "C", explanation: "Prophet Muhammad (PBUH) was born in Mecca, present-day Saudi Arabia." },
  { subject: "irs", year: 2023, question: "The first revelation of the Qur'an occurred on:", option_a: "Mount Sinai", option_b: "Mount Uhud", option_c: "Mount Hira", option_d: "Mount Arafat", correct_answer: "C", explanation: "The first revelation came to Muhammad (PBUH) in the Cave of Hira on Mount Hira." },
  { subject: "irs", year: 2024, question: "Which direction do Muslims face during prayer?", option_a: "North", option_b: "East", option_c: "Qiblah (Ka'bah in Mecca)", option_d: "West", correct_answer: "C", explanation: "Muslims face the Ka'bah in Mecca (the Qiblah) during prayer." },
  { subject: "irs", year: 2023, question: "Sawm (fasting) is observed during which month?", option_a: "Muharram", option_b: "Sha'ban", option_c: "Ramadan", option_d: "Rajab", correct_answer: "C", explanation: "Muslims fast from dawn to sunset during the month of Ramadan." },
  { subject: "irs", year: 2024, question: "Hajj is the pilgrimage to:", option_a: "Medina", option_b: "Jerusalem", option_c: "Mecca", option_d: "Damascus", correct_answer: "C", explanation: "Hajj is the annual pilgrimage to Mecca that every Muslim must undertake at least once." },
  { subject: "irs", year: 2023, question: "Which of the following is a source of Islamic law?", option_a: "The Bible", option_b: "The Qur'an and Hadith", option_c: "The Torah", option_d: "The Vedas", correct_answer: "B", explanation: "The primary sources of Islamic law are the Qur'an and the Hadith (sayings of the Prophet)." },
  { subject: "irs", year: 2024, question: "The term 'Jihad' in Islam means:", option_a: "Holy war", option_b: "Struggle or striving in the cause of God", option_c: "Pilgrimage", option_d: "Prayer", correct_answer: "B", explanation: "Jihad literally means 'struggle' and can refer to spiritual, personal, or communal effort." },
  { subject: "irs", year: 2023, question: "Which prophet is considered the founder of Islam?", option_a: "Abraham", option_b: "Moses", option_c: "Muhammad", option_d: "Jesus", correct_answer: "C", explanation: "Prophet Muhammad (PBUH) is the founder and final prophet of Islam." },
  { subject: "irs", year: 2024, question: "The Islamic calendar is based on:", option_a: "Solar year", option_b: "Lunar year", option_c: "Agricultural cycle", option_d: "Roman calendar", correct_answer: "B", explanation: "The Islamic (Hijri) calendar is purely lunar, with 12 months of 29-30 days each." },
  { subject: "irs", year: 2023, question: "Salat refers to:", option_a: "Fasting", option_b: "Charity", option_c: "Daily prayers", option_d: "Pilgrimage", correct_answer: "C", explanation: "Salat is the five daily prayers performed by Muslims facing the Ka'bah." },
  { subject: "irs", year: 2024, question: "Which of the following is NOT one of the Five Pillars of Islam?", option_a: "Shahada", option_b: "Salat", option_c: "Christmas", option_d: "Zakat", correct_answer: "C", explanation: "Christmas is a Christian festival, not one of the Five Pillars of Islam." },

  // ============ NEW: AGRICULTURAL SCIENCE (15 questions) ============
  { subject: "agricultural_science", year: 2024, question: "Which of the following is a cereal crop?", option_a: "Cassava", option_b: "Maize", option_c: "Yam", option_d: "Cocoa", correct_answer: "B", explanation: "Maize (corn) is a cereal crop belonging to the grass family Poaceae." },
  { subject: "agricultural_science", year: 2023, question: "The process of controlling pests in farming is called:", option_a: "Irrigation", option_b: "Pest control", option_c: "Tillage", option_d: "Harvesting", correct_answer: "B", explanation: "Pest control involves methods to manage or eliminate pests that damage crops." },
  { subject: "agricultural_science", year: 2024, question: "Which soil type has the largest particles?", option_a: "Clay", option_b: "Silt", option_c: "Sand", option_d: "Loam", correct_answer: "C", explanation: "Sand has the largest soil particles (0.05-2.0 mm diameter)." },
  { subject: "agricultural_science", year: 2023, question: "Photosynthesis requires:", option_a: "Oxygen and water", option_b: "Carbon dioxide and water", option_c: "Nitrogen and sunlight", option_d: "Glucose and oxygen", correct_answer: "B", explanation: "Plants use CO₂ and water in the presence of sunlight to produce glucose and oxygen." },
  { subject: "agricultural_science", year: 2024, question: "Rearing of fish is called:", option_a: "Sericulture", option_b: "Apiculture", option_c: "Pisciculture", option_d: "Horticulture", correct_answer: "C", explanation: "Pisciculture is the breeding, rearing, and farming of fish." },
  { subject: "agricultural_science", year: 2023, question: "Which of the following is a leguminous crop?", option_a: "Maize", option_b: "Cowpea", option_c: "Rice", option_d: "Millet", correct_answer: "B", explanation: "Cowpea (beans) is a legume that fixes nitrogen in the soil." },
  { subject: "agricultural_science", year: 2024, question: "The breaking up of soil for planting is called:", option_a: "Harvesting", option_b: "Tillage", option_c: "Irrigation", option_d: "Mulching", correct_answer: "B", explanation: "Tillage is the preparation of soil by ploughing, harrowing, and ridging." },
  { subject: "agricultural_science", year: 2023, question: "Which nutrient is primarily responsible for vegetative growth?", option_a: "Phosphorus", option_b: "Potassium", option_c: "Nitrogen", option_d: "Calcium", correct_answer: "C", explanation: "Nitrogen promotes leaf and stem growth (vegetative growth)." },
  { subject: "agricultural_science", year: 2024, question: "An agricultural extension officer:", option_a: "Farms for farmers", option_b: "Educates farmers on improved farming techniques", option_c: "Sells farm produce", option_d: "Processes agricultural products", correct_answer: "B", explanation: "Extension officers bridge the gap between research and farmers through education." },
  { subject: "agricultural_science", year: 2023, question: "Irrigation is:", option_a: "Protection from pests", option_b: "Artificial supply of water to crops", option_c: "Harvesting of crops", option_d: "Soil preparation", correct_answer: "B", explanation: "Irrigation provides water to crops when rainfall is insufficient." },
  { subject: "agricultural_science", year: 2024, question: "Which of the following is a perennial crop?", option_a: "Maize", option_b: "Cocoa", option_c: "Rice", option_c: "Millet", correct_answer: "B", explanation: "Cocoa is a perennial tree crop that produces for many years." },
  { subject: "agricultural_science", year: 2023, question: "The rearing of bees for honey is called:", option_a: "Pisciculture", option_b: "Apiculture", option_c: "Sericulture", option_d: "Aviculture", correct_answer: "B", explanation: "Apiculture is the maintenance of bee colonies for honey production." },
  { subject: "agricultural_science", year: 2024, question: "Mulching involves:", option_a: "Ploughing the soil", option_b: "Covering the soil surface with organic material", option_c: "Spraying pesticides", option_d: "Draining water from fields", correct_answer: "B", explanation: "Mulching covers soil with straw, leaves, or plastic to conserve moisture and suppress weeds." },
  { subject: "agricultural_science", year: 2023, question: "Which type of farming uses greenhouses?", option_a: "Subsistence farming", option_b: "Commercial farming", option_c: "Shifting cultivation", option_d: "Nomadic herding", correct_answer: "B", explanation: "Greenhouses are used in commercial farming for controlled environment agriculture." },
  { subject: "agricultural_science", year: 2024, question: "The process of removing unwanted plants from farmland is called:", option_a: "Thinning", option_b: "Weeding", option_c: "Pruning", option_d: "Grafting", correct_answer: "B", explanation: "Weeding removes competing plants that consume nutrients and water meant for crops." },

  // ============ NEW: COMMERCE (additional 5) ============
  { subject: "commerce", year: 2024, question: "A letter of credit is:", option_a: "A personal letter", option_b: "A bank guarantee to pay on behalf of a buyer", option_c: "A credit card", option_d: "An invoice", correct_answer: "B", explanation: "A letter of credit is a document from a bank guaranteeing payment to the seller." },
  { subject: "commerce", year: 2023, question: "Which of the following is a feature of a sole proprietorship?", option_a: "Limited liability", option_b: "Unlimited liability", option_c: "Separate legal entity", option_d: "Transferable ownership", correct_answer: "B", explanation: "A sole trader has unlimited personal liability for business debts." },
  { subject: "commerce", year: 2024, question: "The process of selecting the best alternative is called:", option_a: "Planning", option_b: "Decision making", option_c: "Organizing", option_d: "Directing", correct_answer: "B", explanation: "Decision making involves evaluating alternatives and choosing the best one." },
  { subject: "commerce", year: 2023, question: "A franchise is:", option_a: "A government license", option_b: "The right to use a company's brand and business model", option_c: "A type of partnership", option_d: "A government grant", correct_answer: "B", explanation: "A franchise allows an individual to operate a business using the brand's proven model." },
  { subject: "commerce", year: 2024, question: "Which of the following is a function of the stock exchange?", option_a: "Printing money", option_b: "Providing a market for buying and selling securities", option_c: "Collecting taxes", option_d: "Regulating banks", correct_answer: "B", explanation: "The stock exchange provides liquidity and a marketplace for securities trading." },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const results = { inserted: 0, errors: 0, duplicates: 0, errorMessages: [] as string[] };

    for (const q of QUESTIONS) {
      // Check for duplicates first
      const { data: existing } = await supabase
        .from("jamb_questions")
        .select("id")
        .eq("subject", q.subject)
        .eq("question", q.question)
        .limit(1);

      if (existing && existing.length > 0) {
        results.duplicates++;
        continue;
      }

      const { error } = await supabase
        .from("jamb_questions")
        .insert({
          subject: q.subject,
          year: q.year,
          question: q.question,
          option_a: q.option_a,
          option_b: q.option_b,
          option_c: q.option_c,
          option_d: q.option_d,
          correct_answer: q.correct_answer,
          explanation: q.explanation,
          topics: q.topics || [],
        });

      if (error) {
        results.errors++;
        results.errorMessages.push(`${q.subject}: ${error.message}`);
      } else {
        results.inserted++;
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        ...results,
        message: `Inserted ${results.inserted} questions, skipped ${results.duplicates} duplicates, ${results.errors} errors`
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
