import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const QUESTIONS = [
  // ============ MATHEMATICS (20 questions) ============
  { subject: "mathematics", year: 2024, question: "If 3x + 5 = 20, find x.", option_a: "3", option_b: "5", option_c: "7", option_d: "15", correct_answer: "B", explanation: "3x = 20 − 5 = 15 → x = 15/3 = 5." },
  { subject: "mathematics", year: 2023, question: "The factorization of x² − 9 is:", option_a: "(x−3)²", option_b: "(x+3)²", option_c: "(x−3)(x+3)", option_d: "(x−9)(x+1)", correct_answer: "C", explanation: "Difference of two squares: a² − b² = (a−b)(a+b)." },
  { subject: "mathematics", year: 2024, question: "Solve: 2(x − 3) = 8.", option_a: "x = 5", option_b: "x = 7", option_c: "x = 4", option_d: "x = 11", correct_answer: "B", explanation: "2x − 6 = 8 → 2x = 14 → x = 7." },
  { subject: "mathematics", year: 2023, question: "The probability of throwing a fair die and getting a 4 is:", option_a: "1/2", option_b: "1/3", option_c: "1/4", option_d: "1/6", correct_answer: "D", explanation: "One favorable outcome out of 6 possible outcomes." },
  { subject: "mathematics", year: 2024, question: "The gradient of the line y = 3x + 7 is:", option_a: "7", option_b: "3", option_c: "10", option_d: "−3", correct_answer: "B", explanation: "In y = mx + c, m (gradient) = 3." },
  { subject: "mathematics", year: 2023, question: "Convert 110 base 2 to base 10.", option_a: "4", option_b: "5", option_c: "6", option_d: "7", correct_answer: "C", explanation: "1×4 + 1×2 + 0×1 = 4 + 2 = 6." },
  { subject: "mathematics", year: 2024, question: "If log₂x = 5, find x.", option_a: "10", option_b: "25", option_c: "32", option_d: "64", correct_answer: "C", explanation: "x = 2⁵ = 32." },
  { subject: "mathematics", year: 2023, question: "The sum of angles in a triangle is:", option_a: "90°", option_b: "180°", option_c: "270°", option_d: "360°", correct_answer: "B", explanation: "The interior angles of any triangle sum to 180°." },
  { subject: "mathematics", year: 2024, question: "Simplify: (3/4) ÷ (2/5).", option_a: "3/10", option_b: "6/20", option_c: "15/8", option_d: "8/15", correct_answer: "C", explanation: "(3/4) × (5/2) = 15/8." },
  { subject: "mathematics", year: 2023, question: "The area of a circle with radius 7 cm (use π = 22/7) is:", option_a: "44 cm²", option_b: "154 cm²", option_c: "88 cm²", option_d: "308 cm²", correct_answer: "B", explanation: "A = πr² = (22/7) × 49 = 154 cm²." },
  { subject: "mathematics", year: 2024, question: "Solve simultaneously: x + y = 7, x − y = 3.", option_a: "x=5, y=2", option_b: "x=4, y=3", option_c: "x=3, y=4", option_d: "x=6, y=1", correct_answer: "A", explanation: "Adding: 2x = 10 → x = 5, y = 7 − 5 = 2." },
  { subject: "mathematics", year: 2023, question: "The median of 3, 5, 7, 9, 11 is:", option_a: "5", option_b: "7", option_c: "9", option_d: "6", correct_answer: "B", explanation: "Middle value of ordered data: 7." },
  { subject: "mathematics", year: 2024, question: "The simple interest on ₦5000 at 10% per annum for 3 years is:", option_a: "₦500", option_b: "₦1000", option_c: "₦1500", option_d: "₦2000", correct_answer: "C", explanation: "I = PRT/100 = 5000 × 10 × 3/100 = ₦1500." },
  { subject: "mathematics", year: 2023, question: "The derivative of x³ is:", option_a: "x²", option_b: "3x", option_c: "3x²", option_d: "3x³", correct_answer: "C", explanation: "d/dx(xⁿ) = nxⁿ⁻¹ → d/dx(x³) = 3x²." },
  { subject: "mathematics", year: 2024, question: "Evaluate: ∫2x dx.", option_a: "x² + c", option_b: "2x² + c", option_c: "x + c", option_d: "2 + c", correct_answer: "A", explanation: "∫2x dx = 2(x²/2) + c = x² + c." },
  { subject: "mathematics", year: 2023, question: "A polygon has 8 sides. The sum of its interior angles is:", option_a: "720°", option_b: "900°", option_c: "1080°", option_d: "1260°", correct_answer: "C", explanation: "(n−2)×180 = (8−2)×180 = 1080°." },
  { subject: "mathematics", year: 2024, question: "If sin θ = 3/5, find cos θ.", option_a: "4/5", option_b: "3/4", option_c: "5/3", option_d: "5/4", correct_answer: "A", explanation: "cos θ = √(1 − sin²θ) = √(1 − 9/25) = √(16/25) = 4/5." },
  { subject: "mathematics", year: 2023, question: "The HCF of 12 and 18 is:", option_a: "3", option_b: "6", option_c: "12", option_d: "36", correct_answer: "B", explanation: "12 = 2²×3, 18 = 2×3², HCF = 2×3 = 6." },
  { subject: "mathematics", year: 2024, question: "Express 0.75 as a fraction in its simplest form.", option_a: "3/4", option_b: "75/100", option_c: "7/10", option_d: "3/5", correct_answer: "A", explanation: "0.75 = 75/100 = 3/4." },
  { subject: "mathematics", year: 2023, question: "The distance between points (1,2) and (4,6) is:", option_a: "3", option_b: "4", option_c: "5", option_d: "7", correct_answer: "C", explanation: "d = √[(4−1)² + (6−2)²] = √[9+16] = √25 = 5." },

  // ============ GOVERNMENT (20 questions) ============
  { subject: "government", year: 2024, question: "The 1999 Constitution of Nigeria came into effect on:", option_a: "October 1, 1960", option_b: "May 29, 1999", option_c: "January 1, 2000", option_d: "June 12, 1993", correct_answer: "B", explanation: "The 1999 Constitution took effect on 29 May 1999." },
  { subject: "government", year: 2023, question: "Which of the following is a feature of federalism?", option_a: "Single central government", option_b: "Division of power between levels of government", option_c: "No state governments", option_d: "Absolute power at the centre", correct_answer: "B", explanation: "Federalism involves division of powers between central and state/regional governments." },
  { subject: "government", year: 2024, question: "The Independent National Electoral Commission (INEC) was established in:", option_a: "1960", option_b: "1978", option_c: "1999", option_d: "2010", correct_answer: "B", explanation: "INEC was established by the 1979 Constitution (initially as Federal Electoral Commission)." },
  { subject: "government", year: 2023, question: "Democracy is defined as:", option_a: "Rule by the military", option_b: "Government of the people, by the people, for the people", option_c: "Rule by a single party", option_d: "Government by the elite", correct_answer: "B", explanation: "Classic Lincoln definition of democracy." },
  { subject: "government", year: 2024, question: "A unitary system of government is one where:", option_a: "Power is shared between centres", option_b: "All power is concentrated at the centre", option_c: "States have more power", option_d: "Military rules", correct_answer: "B", explanation: "In a unitary system, the central government holds supreme authority." },
  { subject: "government", year: 2023, question: "Which of the following is NOT a function of the legislature?", option_a: "Law making", option_b: "Budget approval", option_c: "Implementation of laws", option_d: "Oversight of executive", correct_answer: "C", explanation: "Implementation is the function of the executive, not the legislature." },
  { subject: "government", year: 2024, question: "Nigeria operated a parliamentary system during the:", option_a: "First Republic (1963–66)", option_b: "Second Republic (1979–83)", option_c: "Third Republic (1993)", option_d: "Fourth Republic (1999–present)", correct_answer: "A", explanation: "Nigeria used a parliamentary system in the First Republic (Westminster model)." },
  { subject: "government", year: 2023, question: "A bill that has been passed by both houses of the National Assembly is called:", option_a: "White paper", option_b: "Executive bill", option_c: "Act of Parliament", option_d: "Green paper", correct_answer: "C", explanation: "A bill becomes an Act after presidential assent." },
  { subject: "government", year: 2024, question: "The body responsible for interpreting the constitution in Nigeria is the:", option_a: "Executive", option_b: "Legislature", option_c: "Judiciary", option_d: "INEC", correct_answer: "C", explanation: "The judiciary interprets laws and the constitution." },
  { subject: "government", year: 2023, question: "Which of the following is a characteristic of a democratic government?", option_a: "Rule of force", option_b: "Free and fair elections", option_c: "Censorship of press", option_d: "One-party system", correct_answer: "B", explanation: "Free and fair elections are a hallmark of democracy." },
  { subject: "government", year: 2024, question: "The Nigerian Senate has how many members?", option_a: "109", option_b: "360", option_c: "369", option_d: "250", correct_answer: "A", explanation: "The Senate has 109 members: 3 per state + 1 for FCT." },
  { subject: "government", year: 2023, question: "Political socialization refers to:", option_a: "Running for office", option_b: "The process of acquiring political attitudes and values", option_c: "Voting behavior", option_d: "Campaigning", correct_answer: "B", explanation: "Political socialization is how individuals develop their political beliefs." },
  { subject: "government", year: 2024, question: "Which is NOT a function of the executive?", option_a: "Implementation of policies", option_b: "Making laws", option_c: "Maintenance of law and order", option_d: "Foreign affairs", correct_answer: "B", explanation: "Making laws is a legislative function." },
  { subject: "government", year: 2023, question: "The concept of 'separation of powers' means:", option_a: "Power is shared equally", option_b: "Each arm of government is independent in its functions", option_c: "One arm controls all others", option_d: "Power is given to the military", correct_answer: "B", explanation: "Separation of powers ensures independence of legislature, executive, and judiciary." },
  { subject: "government", year: 2024, question: "The National Assembly consists of:", option_a: "Senate only", option_b: "House of Representatives only", option_c: "Senate and House of Representatives", option_d: "Senate and State Assemblies", correct_answer: "C", explanation: "The National Assembly is bicameral: Senate + House of Representatives." },
  { subject: "government", year: 2023, question: "A citizen is a person who:", option_a: "Lives in a country", option_b: "Has legal membership and rights in a country", option_c: "Has a passport", option_d: "Was born in a country", correct_answer: "B", explanation: "Citizenship implies legal membership with rights and obligations." },
  { subject: "government", year: 2024, question: "Which of these is NOT a function of local government?", option_a: "Providing local roads", option_b: "Collecting rates and taxes", option_c: "Declaring war", option_d: "Maintaining primary education", correct_answer: "C", explanation: "Declaring war is a federal function." },
  { subject: "government", year: 2023, question: "The electoral system used in Nigeria is:", option_a: "Proportional representation", option_b: "First-past-the-post", option_c: "Alternative vote", option_d: "Single transferable vote", correct_answer: "B", explanation: "Nigeria uses the simple majority (first-past-the-post) system." },
  { subject: "government", year: 2024, question: "Pressure groups differ from political parties in that:", option_a: "They contest elections", option_b: "They seek to influence government policy without seeking office", option_c: "They have a manifesto", option_d: "They nominate candidates", correct_answer: "B", explanation: "Pressure groups influence policy but do not contest elections." },
  { subject: "government", year: 2023, question: "The Nigerian civil war (1967–70) was fought between:", option_a: "North and South", option_b: "Federal government and Biafra", option_c: "Army and Navy", option_d: "Two political parties", correct_answer: "B", explanation: "The war was between the Federal Government and the secessionist state of Biafra." },

  // ============ ECONOMICS (20 questions) ============
  { subject: "economics", year: 2024, question: "Scarcity in economics means:", option_a: "Goods are expensive", option_b: "Resources are limited while wants are unlimited", option_c: "People are poor", option_d: "There is no production", correct_answer: "B", explanation: "Scarcity = unlimited wants vs limited resources." },
  { subject: "economics", year: 2023, question: "The factor of production that organizes other factors is:", option_a: "Land", option_b: "Labour", option_c: "Capital", option_d: "Entrepreneur", correct_answer: "D", explanation: "The entrepreneur combines and organizes the other factors of production." },
  { subject: "economics", year: 2024, question: "A normal good is one where demand:", option_a: "Falls when income rises", option_b: "Rises when income rises", option_c: "Does not change with income", option_d: "Is always zero", correct_answer: "B", explanation: "Normal goods have positive income elasticity — demand rises with income." },
  { subject: "economics", year: 2023, question: "The market where many sellers and many buyers exist is:", option_a: "Monopoly", option_b: "Oligopoly", option_c: "Perfect competition", option_d: "Monopsony", correct_answer: "C", explanation: "Perfect competition has many buyers and sellers with homogeneous products." },
  { subject: "economics", year: 2024, question: "Depreciation refers to:", option_a: "Increase in asset value", option_b: "Decrease in the value of an asset over time", option_c: "Rise in price level", option_d: "Fall in demand", correct_answer: "B", explanation: "Depreciation = reduction in the value of fixed assets through wear and tear." },
  { subject: "economics", year: 2023, question: "Which is an example of a direct tax?", option_a: "VAT", option_b: "Customs duty", option_c: "Company income tax", option_d: "Excise duty", correct_answer: "C", explanation: "Company income tax is levied directly on income/profits." },
  { subject: "economics", year: 2024, question: "The law of diminishing returns states that:", option_a: "Output always increases", option_b: "Adding more of a variable factor eventually gives smaller increases in output", option_c: "Costs always decrease", option_d: "Demand always falls", correct_answer: "B", explanation: "As more units of a variable factor are added to fixed factors, marginal product eventually declines." },
  { subject: "economics", year: 2023, question: "Which of the following is a function of money?", option_a: "Medium of exchange", option_b: "Source of power", option_c: "Means of production", option_d: "Factor of production", correct_answer: "A", explanation: "Money serves as medium of exchange, store of value, unit of account, and standard of deferred payment." },
  { subject: "economics", year: 2024, question: "Balance of payments records:", option_a: "Only imports", option_b: "Only exports", option_c: "All economic transactions between a country and the rest of the world", option_d: "Only foreign aid", correct_answer: "C", explanation: "BoP is a comprehensive record of all international economic transactions." },
  { subject: "economics", year: 2023, question: "Which organization is responsible for monetary policy in Nigeria?", option_a: "Federal Ministry of Finance", option_b: "Central Bank of Nigeria", option_c: "Nigeria Deposit Insurance Corporation", option_d: "Securities and Exchange Commission", correct_answer: "B", explanation: "The CBN formulates and implements monetary policy." },
  { subject: "economics", year: 2024, question: "An isoquant shows:", option_a: "Different quantities of output at different prices", option_b: "Combinations of inputs that produce the same output", option_c: "Consumer preferences", option_d: "Market equilibrium", correct_answer: "B", explanation: "Isoquant = equal output curve showing input combinations." },
  { subject: "economics", year: 2023, question: "The multiplier effect means:", option_a: "Money supply decreases", option_b: "An initial increase in spending leads to a larger final increase in national income", option_c: "Tax increases", option_d: "Prices fall", correct_answer: "B", explanation: "The multiplier = 1/(1−MPC). Initial spending creates a chain of further spending." },
  { subject: "economics", year: 2024, question: "Which is NOT a component of aggregate demand?", option_a: "Consumption", option_b: "Investment", option_c: "Savings", option_d: "Government spending", correct_answer: "C", explanation: "AD = C + I + G + (X−M). Savings is a leakage, not a component." },
  { subject: "economics", year: 2023, question: "Elastic demand means:", option_a: "Quantity demanded changes proportionally less than price", option_b: "Quantity demanded changes proportionally more than price", option_c: "Quantity demanded does not change", option_d: "Price is fixed", correct_answer: "B", explanation: "Elastic demand: PED > 1, quantity responds significantly to price changes." },
  { subject: "economics", year: 2024, question: "Comparative advantage means:", option_a: "Having more resources", option_b: "Being able to produce at a lower opportunity cost", option_c: "Producing more than others", option_d: "Having cheaper labour", correct_answer: "B", explanation: "A country has comparative advantage when it can produce at a lower opportunity cost." },
  { subject: "economics", year: 2023, question: "GDP at market price includes:", option_a: "Only government spending", option_b: "Total value of all final goods and services produced in a country", option_c: "Only exports", option_d: "Only investment", correct_answer: "B", explanation: "GDP = total value of all final goods/services produced within a country's borders." },
  { subject: "economics", year: 2024, question: "The Phillips curve shows the relationship between:", option_a: "GDP and inflation", option_b: "Unemployment and inflation", option_c: "Interest rate and savings", option_d: "Supply and demand", correct_answer: "B", explanation: "The Phillips curve shows an inverse relationship between unemployment and inflation." },
  { subject: "economics", year: 2023, question: "Which is a function of commercial banks?", option_a: "Issuing currency", option_b: "Accepting deposits and granting loans", option_c: "Implementing monetary policy", option_d: "Regulating the financial system", correct_answer: "B", explanation: "Commercial banks accept deposits and make loans." },
  { subject: "economics", year: 2024, question: "Devaluation of the naira means:", option_a: "Increase in the value of naira", option_b: "Deliberate reduction in the official value of naira", option_c: "Increase in foreign reserves", option_d: "Fall in import prices", correct_answer: "B", explanation: "Devaluation is a deliberate downward adjustment of the currency's official value." },
  { subject: "economics", year: 2023, question: "The concept of opportunity cost is best illustrated by:", option_a: "The total cost of production", option_b: "What is given up to produce one more unit of a good", option_c: "The price of goods", option_d: "Revenue earned", correct_answer: "B", explanation: "Opportunity cost = value of the next best alternative forgone." },

  // ============ LITERATURE (15 questions) ============
  { subject: "literature", year: 2024, question: "In literature, 'irony' means:", option_a: "Being funny", option_b: "A contrast between expectation and reality", option_c: "Telling a lie", option_d: "Using big words", correct_answer: "B", explanation: "Irony involves a discrepancy between what is expected and what actually happens." },
  { subject: "literature", year: 2023, question: "A protagonist is:", option_a: "The villain", option_b: "The main character", option_c: "The narrator", option_d: "The setting", correct_answer: "B", explanation: "The protagonist is the central character in a story." },
  { subject: "literature", year: 2024, question: "'It was the best of times, it was the worst of times' is an example of:", option_a: "Simile", option_b: "Oxymoron", option_c: "Antithesis", option_d: "Alliteration", correct_answer: "C", explanation: "Antithesis places opposite ideas in parallel structure for contrast." },
  { subject: "literature", year: 2023, question: "A monologue is:", option_a: "A dialogue between two characters", option_b: "A long speech by one character", option_c: "A poem with no rhythm", option_d: "A type of novel", correct_answer: "B", explanation: "A monologue is an extended speech by one character in a play or poem." },
  { subject: "literature", year: 2024, question: "Setting in a novel refers to:", option_a: "The plot", option_b: "The time and place of the story", option_c: "The characters", option_d: "The theme", correct_answer: "B", explanation: "Setting is the time, place, and environment in which a story takes place." },
  { subject: "literature", year: 2023, question: "An allegory is:", option_a: "A type of poem", option_b: "A story with a hidden moral or political meaning", option_c: "A comedy", option_d: "A short story", correct_answer: "B", explanation: "An allegory is a narrative where characters and events symbolize deeper meanings." },
  { subject: "literature", year: 2024, question: "The theme of a literary work is:", option_a: "The setting", option_b: "The main idea or message", option_c: "The first chapter", option_d: "The author's name", correct_answer: "B", explanation: "Theme is the central message or insight about life conveyed by the work." },
  { subject: "literature", year: 2023, question: "Dramatic monologue was popularized by:", option_a: "William Shakespeare", option_b: "Robert Browning", option_c: "John Keats", option_d: "William Wordsworth", correct_answer: "B", explanation: "Robert Browning perfected the dramatic monologue form." },
  { subject: "literature", year: 2024, question: "Which is NOT a type of conflict in literature?", option_a: "Man vs. nature", option_b: "Man vs. man", option_c: "Man vs. society", option_d: "Man vs. author", correct_answer: "D", explanation: "Common conflicts: man vs. man, nature, society, self, fate, technology." },
  { subject: "literature", year: 2023, question: "Foreshadowing is:", option_a: "Looking back at events", option_b: "Giving hints about what will happen later", option_c: "Describing the setting", option_d: "A type of character", correct_answer: "B", explanation: "Foreshadowing provides clues about events that will occur later in the story." },
  { subject: "literature", year: 2024, question: "The denouement is:", option_a: "The beginning of a story", option_b: "The climax", option_c: "The resolution of the plot", option_d: "The rising action", correct_answer: "C", explanation: "Denouement is the final part where loose ends are tied up." },
  { subject: "literature", year: 2023, question: "Astanza in poetry is a:", option_a: "Line", option_b: "Group of lines", option_c: "Single word", option_d: "Paragraph", correct_answer: "B", explanation: "A stanza is a grouped set of lines in a poem, like a verse." },
  { subject: "literature", year: 2024, question: "Which literary device uses 'like' or 'as' for comparison?", option_a: "Metaphor", option_b: "Simile", option_c: "Hyperbole", option_d: "Personification", correct_answer: "B", explanation: "A simile compares two things using 'like' or 'as'." },
  { subject: "literature", year: 2023, question: "Pathetic fallacy is:", option_a: "A fallacy in logic", option_b: "Attributing human emotions to nature", option_c: "A type of rhyme", option_d: "A character flaw", correct_answer: "B", explanation: "Pathetic fallacy = attributing human feelings to nature (e.g., 'angry storm')." },
  { subject: "literature", year: 2024, question: "Which of these is a prose form?", option_a: "Sonnet", option_b: "Haiku", option_c: "Novel", option_d: "Ballad", correct_answer: "C", explanation: "A novel is a long prose narrative. The others are poetry forms." },

  // ============ GEOGRAPHY (15 questions) ============
  { subject: "geography", year: 2024, question: "The process of soil formation is called:", option_a: "Erosion", option_b: "Pedogenesis", option_c: "Deposition", option_d: "Weathering", correct_answer: "B", explanation: "Pedogenesis is the process of soil formation from parent rock." },
  { subject: "geography", year: 2023, question: "Which of the following is a renewable resource?", option_a: "Coal", option_b: "Petroleum", option_c: "Solar energy", option_d: "Natural gas", correct_answer: "C", explanation: "Solar energy is inexhaustible and renewable." },
  { subject: "geography", year: 2024, question: "The imaginary line that divides the earth into northern and southern hemispheres is:", option_a: "Prime Meridian", option_b: "Tropic of Cancer", option_c: "Equator", option_d: "Arctic Circle", correct_answer: "C", explanation: "The Equator (0° latitude) divides Earth into Northern and Southern Hemispheres." },
  { subject: "geography", year: 2023, question: "Which climate type has distinct wet and dry seasons?", option_a: "Tropical rainforest", option_b: "Tropical savanna", option_c: "Desert", option_d: "Tundra", correct_answer: "B", explanation: "Savanna climate has wet and dry seasons." },
  { subject: "geography", year: 2024, question: "Urbanization refers to:", option_a: "Rural development", option_b: "The growth of cities and towns", option_c: "Agricultural expansion", option_d: "Deforestation", correct_answer: "B", explanation: "Urbanization = increasing proportion of people living in urban areas." },
  { subject: "geography", year: 2023, question: "Which is the longest river in the world?", option_a: "Amazon", option_b: "Mississippi", option_c: "Nile", option_d: "Niger", correct_answer: "C", explanation: "The Nile is approximately 6,650 km long." },
  { subject: "geography", year: 2024, question: "The international date line passes through:", option_a: "0° longitude", option_b: "180° longitude", option_c: "90° East", option_d: "90° West", correct_answer: "B", explanation: "The International Date Line roughly follows 180° longitude." },
  { subject: "geography", year: 2023, question: "Which type of rock is formed from cooled magma?", option_a: "Sedimentary", option_b: "Metamorphic", option_c: "Igneous", option_d: "Fossil", correct_answer: "C", explanation: "Igneous rocks form when magma or lava cools and solidifies." },
  { subject: "geography", year: 2024, question: "The humidex measures:", option_a: "Wind speed", option_b: "How hot it feels combining temperature and humidity", option_c: "Rainfall", option_d: "Air pressure", correct_answer: "B", explanation: "The humidex combines temperature and humidity to indicate perceived heat." },
  { subject: "geography", year: 2023, question: "Nigeria's main export crop is:", option_a: "Cotton", option_b: "Cocoa", option_c: "Rubber", option_d: "Palm oil", correct_answer: "B", explanation: "Cocoa has historically been Nigeria's leading agricultural export." },
  { subject: "geography", year: 2024, question: "Desertification refers to:", option_a: "Formation of deserts", option_b: "Land degradation in arid and semi-arid areas", option_c: "Flood formation", option_d: "Mountain building", correct_answer: "B", explanation: "Desertification is the degradation of land in dry areas due to climate and human activities." },
  { subject: "geography", year: 2023, question: "The tectonic plates are parts of:", option_a: "The atmosphere", option_b: "The Earth's lithosphere", option_c: "The hydrosphere", option_d: "The biosphere", correct_answer: "B", explanation: "Tectonic plates are large pieces of the Earth's lithosphere (crust + upper mantle)." },
  { subject: "geography", year: 2024, question: "The study of population distribution is called:", option_a: "Climatology", option_b: "Demography", option_c: "Cartography", option_d: "Topography", correct_answer: "B", explanation: "Demography is the statistical study of populations." },
  { subject: "geography", year: 2023, question: "Which of these is NOT a type of plate boundary?", option_a: "Convergent", option_b: "Divergent", option_c: "Transform", option_d: "Equatorial", correct_answer: "D", explanation: "The three plate boundaries are convergent, divergent, and transform." },
  { subject: "geography", year: 2024, question: "The Benue River is a tributary of:", option_a: "Atlantic Ocean", option_b: "Niger River", option_c: "Congo River", option_d: "Lake Chad", correct_answer: "B", explanation: "The Benue joins the Niger at Lokoja." },

  // ============ CRS (15 questions) ============
  { subject: "crs", year: 2024, question: "The burning bush experience of Moses is recorded in:", option_a: "Genesis", option_b: "Exodus", option_c: "Leviticus", option_d: "Numbers", correct_answer: "B", explanation: "Exodus chapter 3 records God speaking from the burning bush." },
  { subject: "crs", year: 2023, question: "The fruit of the Spirit includes all EXCEPT:", option_a: "Love", option_b: "Joy", option_c: "Wealth", option_d: "Patience", correct_answer: "C", explanation: "Galatians 5:22-23 lists love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control." },
  { subject: "crs", year: 2024, question: "Who wrote most of the New Testament epistles?", option_a: "Peter", option_b: "John", option_c: "Paul", option_d: "James", correct_answer: "C", explanation: "Paul the Apostle wrote 13 of the 21 epistles." },
  { subject: "crs", year: 2023, question: "The Ark of the Covenant was kept in:", option_a: "The outer court", option_b: "The Holy of Holies", option_c: "The tabernacle entrance", option_d: "The priest's house", correct_answer: "B", explanation: "The Ark was placed in the Most Holy Place (Holy of Holies)." },
  { subject: "crs", year: 2024, question: "Which prophet was swallowed by a great fish?", option_a: "Elijah", option_b: "Isaiah", option_c: "Jonah", option_d: "Jeremiah", correct_answer: "C", explanation: "Jonah was swallowed by a great fish for three days (Jonah 1-2)." },
  { subject: "crs", year: 2023, question: "The parable of the prodigal son teaches about:", option_a: "Hard work", option_b: "God's forgiveness and mercy", option_c: "Wealth creation", option_d: "Obedience to parents", correct_answer: "B", explanation: "The parable illustrates God's unconditional love and willingness to forgive." },
  { subject: "crs", year: 2024, question: "Jesus performed His first miracle at:", option_a: "Bethlehem", option_b: "Nazareth", option_c: "Cana of Galilee", option_d: "Jerusalem", correct_answer: "C", explanation: "Turning water into wine at the wedding in Cana (John 2)." },
  { subject: "crs", year: 2023, question: "The Great Commission is found in:", option_a: "Matthew 28:19-20", option_b: "Mark 1:15", option_c: "Luke 24:47", option_d: "John 3:16", correct_answer: "A", explanation: "Jesus commanded His disciples to go and make disciples of all nations." },
  { subject: "crs", year: 2024, question: "The Psalms were mainly attributed to:", option_a: "Solomon", option_b: "David", option_c: "Moses", option_d: "Abraham", correct_answer: "B", explanation: "David is traditionally credited with writing many of the Psalms." },
  { subject: "crs", year: 2023, question: "The Last Supper was held during which feast?", option_a: "Feast of Tabernacles", option_b: "Passover", option_c: "Pentecost", option_d: "New Moon", correct_answer: "B", explanation: "The Last Supper was a Passover meal (Matthew 26:17-19)." },
  { subject: "crs", year: 2024, question: "Which book comes first in the New Testament?", option_a: "Acts", option_b: "Mark", option_c: "Matthew", option_d: "John", correct_answer: "C", explanation: "The Gospel of Matthew is the first book of the New Testament." },
  { subject: "crs", year: 2023, question: "The Israelites crossed the Red Sea during the time of:", option_a: "Joshua", option_b: "Samuel", option_c: "Moses", option_d: "David", correct_answer: "C", explanation: "Moses led the Israelites through the Red Sea (Exodus 14)." },
  { subject: "crs", year: 2024, question: "Which of the following is a Beatitude?", option_a: "Blessed are the poor in spirit", option_b: "Blessed are the rich", option_c: "Blessed are the powerful", option_d: "Blessed are the famous", correct_answer: "A", explanation: "Matthew 5:3 — 'Blessed are the poor in spirit, for theirs is the kingdom of heaven.'" },
  { subject: "crs", year: 2023, question: "Solomon is known for building:", option_a: "The Tabernacle", option_b: "The Temple", option_c: "The Ark", option_d: "The Cross", correct_answer: "B", explanation: "Solomon built the First Temple in Jerusalem (1 Kings 6)." },
  { subject: "crs", year: 2024, question: "Which apostle denied Jesus three times?", option_a: "Andrew", option_b: "Thomas", option_c: "Peter", option_d: "Judas", correct_answer: "C", explanation: "Peter denied knowing Jesus three times before the cock crowed (Luke 22:54-62)." },

  // ============ IRS (10 questions) ============
  { subject: "irs", year: 2024, question: "The first mosque built in Islam is:", option_a: "Al-Aqsa", option_b: "Al-Haram", option_c: "Quba", option_d: "Medina", correct_answer: "C", explanation: "Masjid Quba in Madinah was the first mosque." },
  { subject: "irs", year: 2023, question: "How many times a day do Muslims pray?", option_a: "3", option_b: "4", option_c: "5", option_d: "7", correct_answer: "C", explanation: "Muslims pray five daily prayers: Fajr, Dhuhr, Asr, Maghrib, Isha." },
  { subject: "irs", year: 2024, question: "The Sadaqat al-Fitr is paid:", option_a: "During Ramadan", option_b: "Before Eid prayer", option_c: "During Hajj", option_d: "After Ramadan", correct_answer: "B", explanation: "Sadaqat al-Fitr is paid before the Eid prayer to purify the fasting person." },
  { subject: "irs", year: 2023, question: "Which Surah is called the heart of the Qur'an?", option_a: "Al-Fatihah", option_b: "Ayat al-Kursi", option_c: "Ya-Sin", option_d: "Al-Baqarah", correct_answer: "C", explanation: "Surah Ya-Sin is often referred to as the heart of the Qur'an." },
  { subject: "irs", year: 2024, question: "The Qiblah direction was changed from Jerusalem to Makkah in:", option_a: "Makkah period", option_b: "Early Madinah period", option_c: "Late Madinah period", option_d: "After Hajj", correct_answer: "B", explanation: "The Qiblah was changed during the early Madinah period (Surah Al-Baqarah:144)." },
  { subject: "irs", year: 2023, question: "Which companion was the first Caliph?", option_a: "Umar ibn al-Khattab", option_b: "Uthman ibn Affan", option_c: "Ali ibn Abi Talib", option_d: "Abu Bakr as-Siddiq", correct_answer: "D", explanation: "Abu Bakr was the first Caliph after the Prophet's death." },
  { subject: "irs", year: 2024, question: "The Hajj pilgrimage is obligatory:", option_a: "Once a year", option_b: "Once in a lifetime", option_c: "Twice a year", option_d: "Every Ramadan", correct_answer: "B", explanation: "Hajj is obligatory once in a lifetime for those who are physically and financially able." },
  { subject: "irs", year: 2023, question: "The first revelation came to Prophet Muhammad in:", option_a: "Makkah", option_b: "Madinah", option_c: "Mount Arafat", option_d: "Taif", correct_answer: "A", explanation: "The first revelation came in the Cave of Hira, near Makkah." },
  { subject: "irs", year: 2024, question: "Which of these is one of the five pillars of Islam?", option_a: "Pilgrimage", option_b: "Charity to relatives only", option_c: "Fasting every Monday", option_d: "Praying at night only", correct_answer: "A", explanation: "Hajj (pilgrimage) is the fifth pillar of Islam." },
  { subject: "irs", year: 2023, question: "The Surah that begins with 'Alhamdulillah' is:", option_a: "Al-Ikhlas", option_b: "Al-Fatihah", option_c: "An-Nas", option_d: "Al-Falaq", correct_answer: "B", explanation: "Surah Al-Fatihah begins with 'Alhamdulillahi Rabbil Alamin'." },

  // ============ AGRICULTURAL SCIENCE (10 questions) ============
  { subject: "agricultural_science", year: 2024, question: "Mixed cropping involves:", option_a: "Growing one crop only", option_b: "Growing two or more crops together", option_c: "Growing crops in rotation", option_d: "Planting at different times", correct_answer: "B", explanation: "Mixed cropping = growing two or more crops simultaneously on the same land." },
  { subject: "agricultural_science", year: 2023, question: "The process of removing unwanted plants from farmland is:", option_a: "Mulching", option_b: "Weeding", option_c: "Ridging", option_d: "Harrowing", correct_answer: "B", explanation: "Weeding removes competing plants from farmland." },
  { subject: "agricultural_science", year: 2024, question: "Which of these is a barrier method of pest control?", option_a: "Chemical spraying", option_b: "Use of traps", option_c: "Use of nets/screens", option_d: "Biological control", correct_answer: "C", explanation: "Physical barriers like screens prevent pest access." },
  { subject: "agricultural_science", year: 2023, question: "Poultry farming is the rearing of:", option_a: "Cattle", option_b: "Sheep", option_c: "Chickens and other birds", option_d: "Goats", correct_answer: "C", explanation: "Poultry refers to domesticated birds kept for eggs, meat, or feathers." },
  { subject: "agricultural_science", year: 2024, question: "Contour ploughing helps to:", option_a: "Increase soil acidity", option_b: "Reduce soil erosion", option_c: "Increase pest population", option_d: "Decrease water retention", correct_answer: "B", explanation: "Ploughing along contours reduces water runoff and soil erosion." },
  { subject: "agricultural_science", year: 2023, question: "The rearing of fish is called:", option_a: "Apiary", option_b: "Sericulture", option_c: "Pisciculture", option_d: "Apiculture", correct_answer: "C", explanation: "Pisciculture is fish farming. (Sericulture = silkworm; Apiculture = bees)." },
  { subject: "agricultural_science", year: 2024, question: "Which of these is a leguminous crop?", option_a: "Maize", option_b: "Groundnut", option_c: "Yam", option_d: "Cassava", correct_answer: "B", explanation: "Groundnut is a legume that fixes nitrogen in the soil." },
  { subject: "agricultural_science", year: 2023, question: "Mulching is done to:", option_a: "Kill pests", option_b: "Conserve soil moisture and suppress weeds", option_c: "Increase soil pH", option_d: "Aerate the soil", correct_answer: "B", explanation: "Mulching covers the soil to retain moisture and suppress weed growth." },
  { subject: "agricultural_science", year: 2024, question: "The SI unit of land area measurement in agriculture is:", option_a: "Kilometre", option_b: "Hectare", option_c: "Litre", option_d: "Gram", correct_answer: "B", explanation: "A hectare (10,000 m²) is the standard unit for land area." },
  { subject: "agricultural_science", year: 2023, question: "Crop rotation helps to:", option_a: "Increase pest population", option_b: "Maintain soil fertility", option_c: "Reduce farm size", option_d: "Increase weeds", correct_answer: "B", explanation: "Alternating crops maintains soil nutrients and breaks pest cycles." },

  // ============ COMMERCE (10 questions) ============
  { subject: "commerce", year: 2024, question: "A bill of lading is:", option_a: "A receipt for goods", option_b: "A document showing ownership of goods shipped by sea", option_c: "An invoice", option_d: "A delivery note", correct_answer: "B", explanation: "A bill of lading serves as a receipt, contract of carriage, and document of title." },
  { subject: "commerce", year: 2023, question: "Which of the following is NOT a function of commercial banks?", option_a: "Accepting deposits", option_b: "Issuing currency notes", option_c: "Granting loans", option_d: "Providing safe deposit boxes", correct_answer: "B", explanation: "Issuing currency is the function of the Central Bank, not commercial banks." },
  { subject: "commerce", year: 2024, question: "FOB stands for:", option_a: "Free on Board", option_b: "Full Order Book", option_c: "Freight on Board", option_d: "Free of Bonds", correct_answer: "A", explanation: "FOB (Free on Board) means the seller delivers goods on board the vessel." },
  { subject: "commerce", year: 2023, question: "A partnership has a maximum of how many partners?", option_a: "5", option_b: "10", option_c: "20", option_d: "50", correct_answer: "C", explanation: "A general partnership can have up to 20 partners." },
  { subject: "commerce", year: 2024, question: "The document that orders a bank to pay a specific sum is a:", option_a: "Promissory note", option_b: "Cheque", option_c: "Receipt", option_d: "Invoice", correct_answer: "B", explanation: "A cheque is a written order to a bank to pay a specific amount." },
  { subject: "commerce", year: 2023, question: "Which type of insurance covers goods in transit?", option_a: "Life insurance", option_b: "Fire insurance", option_c: "Marine insurance", option_d: "Motor insurance", correct_answer: "C", explanation: "Marine insurance covers goods while being transported by sea/land/air." },
  { subject: "commerce", year: 2024, question: "A public limited company must have:", option_a: "1 director", option_b: "Minimum 2 directors", option_c: "7 shareholders", option_d: "Both B and C", correct_answer: "D", explanation: "A PLC requires minimum 2 directors and 7 shareholders." },
  { subject: "commerce", year: 2023, question: "The stock exchange is a market for:", option_a: "Fresh produce", option_b: "Second-hand goods", option_c: "Government securities and company shares", option_d: "Foreign exchange only", correct_answer: "C", explanation: "The stock exchange trades securities (shares, bonds, etc.)." },
  { subject: "commerce", year: 2024, question: "Joint venture differs from a partnership in that:", option_a: "It is permanent", option_b: "It is usually for a single project", option_c: "It requires many partners", option_d: "It cannot make profit", correct_answer: "B", explanation: "A joint venture is typically for a specific project, while a partnership is ongoing." },
  { subject: "commerce", year: 2023, question: "An endorsement on a cheque means:", option_a: "Cancelling the cheque", option_b: "Signing the back to transfer ownership", option_c: "Depositing the cheque", option_d: "Destroying the cheque", correct_answer: "B", explanation: "Endorsement = signing the back of a cheque to transfer it to another person." },

  // ============ ACCOUNTING (10 questions) ============
  { subject: "accounting", year: 2024, question: "The accounting equation is:", option_a: "Assets = Liabilities", option_b: "Assets = Capital + Liabilities", option_c: "Capital = Assets + Liabilities", option_d: "Liabilities = Capital + Assets", correct_answer: "B", explanation: "The fundamental equation: Assets = Owner's Equity (Capital) + Liabilities." },
  { subject: "accounting", year: 2023, question: "An income statement shows:", option_a: "Assets and liabilities", option_b: "Revenue, expenses, and profit or loss", option_c: "Cash flow only", option_d: "Owner's capital only", correct_answer: "B", explanation: "The income statement (P&L) shows revenues, expenses, and the resulting profit or loss." },
  { subject: "accounting", year: 2024, question: "Which account is debited when cash is received?", option_a: "Capital account", option_b: "Cash account", option_c: "Income account", option_d: "Expense account", correct_answer: "B", explanation: "Cash account is debited when cash comes in (increases an asset)." },
  { subject: "accounting", year: 2023, question: "The purpose of a balance sheet is to:", option_a: "Calculate profit", option_b: "Show the financial position at a point in time", option_c: "Record daily transactions", option_d: "Calculate turnover", correct_answer: "B", explanation: "The balance sheet shows assets, liabilities, and capital at a specific date." },
  { subject: "accounting", year: 2024, question: "Stocks (inventory) are valued at:", option_a: "Selling price", option_b: "Cost or net realizable value, whichever is lower", option_c: "Purchase price only", option_d: "Replacement cost", correct_answer: "B", explanation: "IAS 2 requires inventory at the lower of cost and net realizable value." },
  { subject: "accounting", year: 2023, question: "Carriage inwards is treated as:", option_a: "An expense", option_b: "Part of the cost of purchases", option_c: "Income", option_d: "A liability", correct_answer: "B", explanation: "Carriage inwards (transport on purchases) is added to the cost of goods purchased." },
  { subject: "accounting", year: 2024, question: "Bad debts are written off to:", option_a: "Debit side of P&L", option_b: "Credit side of P&L", option_c: "Balance sheet", option_d: "Cash book", correct_answer: "A", explanation: "Bad debts are expenses and appear on the debit side of the income statement." },
  { subject: "accounting", year: 2023, question: "Drawings reduce:", option_a: "Assets", option_b: "Liabilities", option_c: "Owner's equity/capital", option_d: "Revenue", correct_answer: "C", explanation: "Drawings are withdrawals by the owner, reducing capital." },
  { subject: "accounting", year: 2024, question: "Accruals relate to:", option_a: "Cash received in advance", option_b: "Income/expenses earned/incurred but not yet received/paid", option_c: "Bank overdrafts", option_d: "Fixed assets", correct_answer: "B", explanation: "Accruals are revenues earned or expenses incurred that haven't been received/paid yet." },
  { subject: "accounting", year: 2023, question: "The cash book records:", option_a: "Only credit transactions", option_b: "Only cash and bank transactions", option_c: "All transactions", option_d: "Only credit sales", correct_answer: "B", explanation: "The cash book is a special journal for all cash and bank receipts and payments." },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const results = { inserted: 0, errors: 0, errorMessages: [] as string[] };

    for (const q of QUESTIONS) {
      const { error } = await supabase
        .from("jamb_questions")
        .insert({
          subject: q.subject,
          year: q.year,
          question: q.question,
          option_a: q.option_a,
          option_b: q.option_b,
          option_c: q.option_c,
          option_d: q.option_d,
          correct_answer: q.correct_answer,
          explanation: q.explanation,
          topics: [],
        });

      if (error) {
        results.errors++;
        results.errorMessages.push(`${q.subject}: ${error.message}`);
      } else {
        results.inserted++;
      }
    }

    return new Response(
      JSON.stringify({ success: true, ...results }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
