
INSERT INTO public.jamb_questions (subject, year, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- ENGLISH
('english',2024,'Choose the option opposite in meaning to "candid": Her response was quite candid.','frank','honest','evasive','sincere','C','Candid means honest/frank; evasive is the opposite.'),
('english',2024,'Identify the correctly punctuated sentence.','"Where are you going" she asked.','"Where are you going?" she asked.','"Where are you going?", she asked','Where are you going, she asked?','B','Question mark inside quotes; comma before "she asked" is unnecessary.'),
('english',2023,'Choose the word nearest in meaning to "meticulous".','careless','thorough','lazy','quick','B','Meticulous means showing great attention to detail = thorough.'),
('english',2024,'The plural of "crisis" is:','crisises','crises','crisisses','crisis','B','Latin-origin nouns ending in -is form plural with -es: crises.'),
('english',2023,'The passive form of "The boy kicked the ball" is:','The ball is kicked by the boy.','The ball was kicked by the boy.','The ball has been kicked.','The ball kicks the boy.','B','Simple past active becomes was/were + past participle.'),
('english',2024,'Choose the word with a different stress pattern.','photograph','photographer','photographic','photography','A','"Photograph" stresses first syllable; others stress the second.'),
('english',2023,'"He ran as fast as a cheetah" is an example of:','metaphor','simile','irony','oxymoron','B','Simile uses "as" or "like" to compare.'),
('english',2024,'Choose the correct question tag: "You are coming, ___?"','are you','aren''t you','isn''t it','do you','B','Positive statement takes a negative tag with the same auxiliary.'),
('english',2023,'The antonym of "abundant" is:','plentiful','ample','scarce','copious','C','Scarce means insufficient — opposite of abundant.'),
('english',2024,'Which sentence contains a split infinitive?','She wants to quickly leave.','She wants to leave quickly.','Quickly, she wants to leave.','She quickly wants to leave.','A','Adverb "quickly" splits "to leave".'),

-- MATHEMATICS
('mathematics',2024,'Simplify (2x²y)³.','6x⁶y³','8x⁶y³','8x⁵y³','6x⁵y³','B','(2)³·(x²)³·y³ = 8x⁶y³.'),
('mathematics',2023,'Find the sum of the roots of 2x²-7x+3=0.','7/2','-7/2','3/2','-3/2','A','Sum of roots = -b/a = 7/2.'),
('mathematics',2024,'Evaluate log₂ 32.','4','5','6','8','B','2⁵=32, so log₂32=5.'),
('mathematics',2023,'A car travels 120 km in 2 hours. Find its average speed in m/s.','16.7','60','30','33.3','A','60 km/h = 60000/3600 ≈ 16.7 m/s.'),
('mathematics',2024,'The nth term of a GP is arⁿ⁻¹. Find the 4th term of 2,6,18,...','54','108','162','36','A','r=3, T₄=2·3³=54.'),
('mathematics',2023,'How many diagonals does a hexagon have?','6','9','12','15','B','n(n-3)/2 = 6·3/2 = 9.'),
('mathematics',2024,'If x:y = 2:3, find (2x+y):(x+2y).','7:8','5:7','4:5','3:4','A','Let x=2,y=3: (4+3):(2+6)=7:8.'),
('mathematics',2023,'Find x if 3ˣ = 1/27.','-3','3','-1/3','1/3','A','27=3³ so 1/27=3⁻³, x=-3.'),
('mathematics',2024,'Find the mode of: 2,4,4,5,6,4,7,8.','4','5','6','2','A','4 appears most frequently.'),
('mathematics',2023,'The angle subtended by a diameter at the circumference of a circle is:','45°','60°','90°','180°','C','Angle in a semicircle is 90°.'),

-- PHYSICS
('physics',2024,'The unit of magnetic flux is:','Tesla','Weber','Henry','Gauss','B','Weber (Wb) is SI unit of magnetic flux.'),
('physics',2023,'A stone dropped from rest falls freely. After 3s (g=10m/s²), its velocity is:','15 m/s','20 m/s','30 m/s','45 m/s','C','v=gt=10·3=30 m/s.'),
('physics',2024,'Which of the following is a scalar quantity?','Force','Momentum','Work','Velocity','C','Work has magnitude only.'),
('physics',2023,'The frequency of an oscillator with period 0.02 s is:','20 Hz','50 Hz','100 Hz','200 Hz','B','f=1/T=1/0.02=50 Hz.'),
('physics',2024,'Which law states F=ma?','Newton''s first law','Newton''s second law','Newton''s third law','Hooke''s law','B','Second law relates force and acceleration.'),
('physics',2023,'Latent heat of fusion is heat required to:','raise temperature','melt a solid at constant temperature','boil a liquid','cool a gas','B','Fusion = solid to liquid at constant T.'),
('physics',2024,'The image formed by a plane mirror is:','real and inverted','virtual and inverted','virtual and erect','real and erect','C','Plane mirror gives virtual, upright, laterally inverted image.'),
('physics',2023,'Which particle has no charge?','Proton','Electron','Neutron','Alpha','C','Neutron is electrically neutral.'),
('physics',2024,'An object of mass 2 kg moving at 5 m/s has KE of:','10 J','20 J','25 J','50 J','C','KE=½mv²=½·2·25=25 J.'),
('physics',2023,'The speed of light in vacuum is approximately:','3×10⁶ m/s','3×10⁸ m/s','3×10¹⁰ m/s','3×10⁵ m/s','B','c ≈ 3×10⁸ m/s.'),

-- CHEMISTRY
('chemistry',2024,'The number of moles in 88 g of CO₂ (C=12,O=16) is:','1','2','3','4','B','M=44, n=88/44=2 mol.'),
('chemistry',2023,'Which of these is an amphoteric oxide?','Na₂O','CaO','Al₂O₃','CO₂','C','Al₂O₃ reacts with both acids and bases.'),
('chemistry',2024,'Avogadro''s number is:','6.02×10²³','6.02×10²²','3.01×10²³','1.6×10⁻¹⁹','A','6.022×10²³ particles per mole.'),
('chemistry',2023,'The bond in NaCl is:','covalent','metallic','ionic','hydrogen','C','Metal + non-metal forms ionic bond.'),
('chemistry',2024,'Which gas turns limewater milky?','O₂','H₂','CO₂','N₂','C','CO₂ + Ca(OH)₂ → CaCO₃ (milky).'),
('chemistry',2023,'The general formula of alkanes is:','CₙH₂ₙ','CₙH₂ₙ₊₂','CₙH₂ₙ₋₂','CₙHₙ','B','Saturated hydrocarbons: CₙH₂ₙ₊₂.'),
('chemistry',2024,'Which of these is a reducing agent?','KMnO₄','K₂Cr₂O₇','H₂S','O₂','C','H₂S readily donates electrons/hydrogen.'),
('chemistry',2023,'Rusting of iron requires:','oxygen only','water only','oxygen and water','oxygen and CO₂','C','Both moisture and oxygen are required.'),
('chemistry',2024,'The empirical formula of glucose C₆H₁₂O₆ is:','CHO','CH₂O','C₂H₄O₂','C₆H₁₂O₆','B','Divide subscripts by 6.'),
('chemistry',2023,'Which is a noble gas?','H₂','Cl₂','Ne','O₂','C','Neon is in group 18.'),

-- BIOLOGY
('biology',2024,'The exchange of gases in plants occurs through:','xylem','phloem','stomata','cuticle','C','Stomata regulate gas exchange in leaves.'),
('biology',2023,'The functional unit of the kidney is the:','neuron','nephron','alveolus','villus','B','Nephron is the filtering unit of the kidney.'),
('biology',2024,'Which vitamin is produced by the skin on exposure to sunlight?','A','B','C','D','D','UV converts a cholesterol precursor to vitamin D.'),
('biology',2023,'The process by which plants lose water vapour is:','transpiration','translocation','respiration','photosynthesis','A','Transpiration = water loss via stomata.'),
('biology',2024,'Sickle cell anaemia is a disease of the:','muscles','blood','bones','nerves','B','It affects red blood cell shape.'),
('biology',2023,'Which organelle contains DNA and directs cell activity?','Ribosome','Nucleus','Lysosome','Vacuole','B','Nucleus houses genetic material.'),
('biology',2024,'The number of chambers in the human heart is:','2','3','4','5','C','Two atria and two ventricles = 4 chambers.'),
('biology',2023,'Which of the following is an enzyme in saliva?','Pepsin','Ptyalin','Trypsin','Lipase','B','Ptyalin (salivary amylase) digests starch.'),
('biology',2024,'Mendel is known as the father of:','evolution','genetics','ecology','taxonomy','B','Gregor Mendel founded modern genetics.'),
('biology',2023,'Malaria parasites are transmitted by:','Aedes mosquito','Culex mosquito','Anopheles mosquito','tsetse fly','C','Female Anopheles mosquitoes transmit Plasmodium.'),

-- LITERATURE
('literature',2024,'A 14-line poem is called a:','ballad','ode','sonnet','elegy','C','Sonnet is a 14-line poem.'),
('literature',2023,'The repetition of consonant sounds at the beginning of words is:','assonance','alliteration','rhyme','onomatopoeia','B','Alliteration = initial consonant repetition.'),
('literature',2024,'A long narrative poem about heroic deeds is called:','lyric','epic','sonnet','elegy','B','Epic tells of heroic exploits.'),
('literature',2023,'The turning point in a plot is called:','exposition','rising action','climax','denouement','C','Climax is the highest point of tension.'),
('literature',2024,'A character who opposes the protagonist is the:','narrator','antagonist','foil','villain','B','Antagonist opposes the protagonist.'),
('literature',2023,'A pause in a line of poetry is called a:','caesura','enjambment','stanza','meter','A','Caesura = natural pause in a line.'),
('literature',2024,'"O Rose thou art sick" employs:','simile','apostrophe','metonymy','pun','B','Address to an absent/inanimate thing = apostrophe.'),
('literature',2023,'A play with a sad ending is called:','comedy','tragedy','farce','satire','B','Tragedy ends unhappily for the protagonist.'),
('literature',2024,'The mood of a literary work refers to:','author''s attitude','feeling evoked in the reader','plot structure','character voice','B','Mood = emotional atmosphere for readers.'),
('literature',2023,'Blank verse is written in:','rhyming couplets','free verse','unrhymed iambic pentameter','trochaic tetrameter','C','Blank verse = unrhymed iambic pentameter.'),

-- GOVERNMENT
('government',2024,'The head of the executive arm of the Nigerian government is the:','Chief Justice','Senate President','President','Speaker','C','President heads the executive.'),
('government',2023,'Sovereignty means:','wealth','supreme authority','freedom','democracy','B','Sovereignty = supreme political authority.'),
('government',2024,'A written constitution is one that is:','unwritten','codified in a single document','flexible','customary','B','Written = contained in a single document.'),
('government',2023,'Nigeria became a republic in:','1960','1963','1966','1979','B','Republic status began 1 October 1963.'),
('government',2024,'The principle of separation of powers was propounded by:','Rousseau','Montesquieu','Locke','Hobbes','B','Montesquieu, in "Spirit of the Laws".'),
('government',2023,'Which is NOT an arm of government?','Legislature','Judiciary','Executive','Bureaucracy','D','Bureaucracy is part of the executive.'),
('government',2024,'A one-party system is common in:','democratic states','communist states','federal states','monarchies','B','Communist states typically allow one party.'),
('government',2023,'The upper legislative chamber in Nigeria is:','House of Representatives','Senate','House of Assembly','Council of State','B','Senate is Nigeria''s upper chamber.'),
('government',2024,'Which document guarantees fundamental human rights in Nigeria?','Electoral Act','Constitution','Penal Code','Land Use Act','B','Chapter IV of the Constitution.'),
('government',2023,'Universal adult suffrage means:','all adults can vote','only males vote','only landowners vote','only literate people vote','A','Right to vote for all qualifying adults.'),

-- ECONOMICS
('economics',2024,'The law of demand states that, other things equal, as price rises quantity demanded:','rises','falls','stays constant','doubles','B','Inverse relationship between price and quantity demanded.'),
('economics',2023,'Opportunity cost is:','money spent','next best alternative forgone','total cost','fixed cost','B','What is given up to obtain something.'),
('economics',2024,'A market with one seller is called a:','monopoly','oligopoly','duopoly','perfect competition','A','Mono = one.'),
('economics',2023,'Inflation refers to a persistent rise in:','wages','unemployment','general price level','exports','C','Sustained rise in general prices.'),
('economics',2024,'GDP stands for:','Gross Domestic Product','General Domestic Price','Government Direct Payment','Gross Direct Profit','A','Gross Domestic Product.'),
('economics',2023,'The central bank of Nigeria was established in:','1958','1959','1960','1963','B','CBN Act 1958, operational 1959.'),
('economics',2024,'A tax levied on income is called:','indirect tax','direct tax','sales tax','VAT','B','Income tax is a direct tax.'),
('economics',2023,'Utility in economics means:','usefulness','profit','cost','satisfaction from consumption','D','Satisfaction derived from consuming a good.'),
('economics',2024,'Money that serves as a store of value must be:','perishable','durable','abundant','worthless','B','Durability is essential to store value.'),
('economics',2023,'A budget deficit occurs when:','revenue > expenditure','revenue = expenditure','expenditure > revenue','no expenditure','C','Deficit = spending exceeds revenue.'),

-- GEOGRAPHY
('geography',2024,'The imaginary line at 0° latitude is the:','Prime Meridian','Equator','Tropic of Cancer','Arctic Circle','B','Equator = 0° latitude.'),
('geography',2023,'The rotation of the earth causes:','seasons','day and night','tides','eclipses','B','Rotation on axis = day/night cycle.'),
('geography',2024,'A narrow strip of land connecting two larger land masses is:','isthmus','strait','peninsula','cape','A','Isthmus links two land masses.'),
('geography',2023,'The largest ocean is the:','Atlantic','Indian','Arctic','Pacific','D','Pacific Ocean is largest.'),
('geography',2024,'The instrument for measuring atmospheric pressure is a:','thermometer','barometer','hygrometer','anemometer','B','Barometer measures pressure.'),
('geography',2023,'Loam soil is best for agriculture because it is:','purely sandy','purely clayey','a balanced mix of sand, silt and clay','waterlogged','C','Loam has ideal balance of components.'),
('geography',2024,'The prime meridian passes through:','Paris','Washington','Greenwich','Tokyo','C','0° longitude runs through Greenwich, London.'),
('geography',2023,'A river that flows into another river is a:','tributary','distributary','delta','estuary','A','Tributary joins a larger river.'),
('geography',2024,'The layer of atmosphere containing the ozone is the:','troposphere','stratosphere','mesosphere','thermosphere','B','Ozone layer sits in the stratosphere.'),
('geography',2023,'Nigeria is located in which continent?','Asia','Europe','Africa','South America','C','Nigeria is in West Africa.'),

-- CRS
('crs',2024,'Who led the Israelites out of Egypt?','Abraham','Moses','Joshua','David','B','Moses led the Exodus.'),
('crs',2023,'Jesus was born in:','Nazareth','Bethlehem','Jerusalem','Capernaum','B','Bethlehem of Judea.'),
('crs',2024,'The first book of the Bible is:','Exodus','Genesis','Leviticus','Numbers','B','Genesis is the first book.'),
('crs',2023,'How many disciples did Jesus have?','10','11','12','13','C','Twelve apostles.'),
('crs',2024,'The Sermon on the Mount is recorded in:','Matthew 5-7','Luke 10','Mark 3','John 6','A','Matthew chapters 5-7.'),
('crs',2023,'Who denied Jesus three times?','Judas','Peter','John','Thomas','B','Peter denied Jesus before the cock crowed.'),
('crs',2024,'The tenth plague on Egypt was the:','frogs','locusts','darkness','death of the firstborn','D','Death of the firstborn.'),
('crs',2023,'David killed Goliath with a:','sword','sling and stone','spear','bow','B','A single stone from a sling.'),
('crs',2024,'The place where Jesus was crucified is called:','Bethany','Golgotha','Gethsemane','Emmaus','B','Golgotha, meaning "place of the skull".'),
('crs',2023,'The last book of the Bible is:','Jude','Revelation','1 John','Acts','B','Revelation closes the New Testament.'),

-- IRS
('irs',2024,'The last prophet in Islam is:','Isa (AS)','Musa (AS)','Muhammad (SAW)','Ibrahim (AS)','C','Muhammad (SAW) is the seal of the Prophets.'),
('irs',2023,'How many pillars of Islam are there?','3','4','5','6','C','Five pillars.'),
('irs',2024,'The holy book of Islam is the:','Torah','Injil','Zabur','Qur''an','D','The Qur''an is the final revelation.'),
('irs',2023,'The direction Muslims face during Salat is called:','Mihrab','Qiblah','Mimbar','Sajdah','B','Qiblah — towards the Ka''bah.'),
('irs',2024,'Fasting during Ramadan is which pillar?','Second','Third','Fourth','Fifth','C','Sawm is the fourth pillar.'),
('irs',2023,'The migration of the Prophet from Makkah to Madinah is called:','Hajj','Hijrah','Umrah','Isra','B','Hijrah in 622 CE.'),
('irs',2024,'How many rak''ah are in Fajr prayer?','2','3','4','5','A','Two rak''ah.'),
('irs',2023,'The compulsory alms in Islam is:','Sadaqah','Zakat','Khums','Fidyah','B','Zakat is obligatory.'),
('irs',2024,'The first Caliph of Islam was:','Umar','Uthman','Abu Bakr','Ali','C','Abu Bakr as-Siddiq.'),
('irs',2023,'The night the Qur''an was first revealed is:','Laylatul Qadr','Laylatul Bara''ah','Laylatul Isra','Laylatul Jumu''ah','A','Night of Power in Ramadan.'),

-- AGRICULTURAL SCIENCE
('agricultural_science',2024,'Which crop is a legume?','Maize','Rice','Cowpea','Cassava','C','Legumes fix nitrogen; cowpea is a legume.'),
('agricultural_science',2023,'The process of turning the soil before planting is:','harrowing','ploughing','ridging','mulching','B','Ploughing loosens and turns soil.'),
('agricultural_science',2024,'Which of these is a ruminant?','Pig','Rabbit','Cow','Chicken','C','Cows have four stomach compartments.'),
('agricultural_science',2023,'NPK fertilizer supplies:','only nitrogen','only phosphorus','nitrogen, phosphorus and potassium','only potassium','C','N, P and K in one blend.'),
('agricultural_science',2024,'Broilers are reared mainly for:','eggs','meat','feathers','manure','B','Broilers are meat-type chickens.'),
('agricultural_science',2023,'Which is a root tuber?','Yam','Cassava','Onion','Ginger','B','Cassava is a root tuber; yam is a stem tuber.'),
('agricultural_science',2024,'Weeds compete with crops for:','only water','only nutrients','only light','water, nutrients, light and space','D','All essential growth resources.'),
('agricultural_science',2023,'Artificial insemination in livestock is used to:','reduce feed cost','improve breed quality','shorten life span','increase parasites','B','Enables use of superior sires.'),
('agricultural_science',2024,'Green manure is derived from:','livestock waste','compost','ploughed-in green plants','poultry droppings','C','Green plants ploughed under to enrich soil.'),
('agricultural_science',2023,'Which farm tool is used for cutting grasses?','Cutlass','Hoe','Rake','Wheelbarrow','A','Cutlass/machete cuts grasses and shrubs.'),

-- COMMERCE
('commerce',2024,'Trade between two countries is called:','home trade','wholesale','foreign trade','retail','C','Foreign trade crosses national borders.'),
('commerce',2023,'A document that lists goods to be delivered is a:','receipt','invoice','waybill','cheque','C','Waybill accompanies goods in transit.'),
('commerce',2024,'The purpose of insurance is to:','make profit','provide indemnity against loss','avoid taxation','save money','B','Insurance indemnifies the insured against loss.'),
('commerce',2023,'A shareholder in a company is entitled to:','wages','salary','dividend','commission','C','Dividends are the shareholder''s return.'),
('commerce',2024,'Trade discount is granted to:','retailers by wholesalers','customers who pay early','all buyers','company staff','A','Trade discount is between traders.'),
('commerce',2023,'A cheque that has passed its validity period is called:','post-dated','stale','dishonoured','open','B','Stale cheque > 6 months old.'),
('commerce',2024,'The middleman between manufacturer and retailer is the:','producer','wholesaler','consumer','agent','B','Wholesaler buys in bulk and sells to retailers.'),
('commerce',2023,'CIF stands for:','Cost, Insurance, Freight','Cash In Full','Company Insurance Fund','Commerce Import Form','A','International trade shipping term.'),
('commerce',2024,'Bank overdraft is a form of:','saving','short-term loan','share capital','investment','B','Bank permits withdrawal beyond balance up to a limit.'),
('commerce',2023,'A limited liability company is owned by:','one person','partners','shareholders','the state','C','Ownership is by shareholders.'),

-- ACCOUNTING
('accounting',2024,'The double entry system requires every transaction to have:','one entry','two entries: a debit and a credit','three entries','no entry','B','Debit and matching credit.'),
('accounting',2023,'The account that records goods returned by customers is:','purchases returns','sales returns','discount received','carriage inwards','B','Sales returns = returns inwards.'),
('accounting',2024,'Assets = Capital + ?','Drawings','Liabilities','Expenses','Losses','B','Basic accounting equation.'),
('accounting',2023,'A trial balance is prepared to:','calculate profit','check arithmetical accuracy of ledgers','value stock','forecast sales','B','Ensures debits equal credits.'),
('accounting',2024,'Depreciation is charged on:','current assets','fixed assets','stock','cash','B','Fixed assets lose value over time.'),
('accounting',2023,'Prepaid expenses are shown in the balance sheet as:','liabilities','current assets','fixed assets','capital','B','Prepayments are current assets.'),
('accounting',2024,'The book of original entry for credit purchases is:','sales day book','purchases day book','cash book','general journal','B','Credit purchases enter the purchases day book.'),
('accounting',2023,'Goodwill is classified as a(n):','current asset','intangible asset','liability','expense','B','Goodwill is intangible.'),
('accounting',2024,'Bank reconciliation statement is prepared to reconcile:','cash book with bank statement','ledger with journal','trial balance with balance sheet','profit with sales','A','Explains differences between the two records.'),
('accounting',2023,'Net profit is transferred to the:','trading account','profit & loss account','capital account','drawings account','C','Net profit increases owner''s capital.');
