import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const QUESTIONS = [
  // ============ PHYSICS (30 questions) ============
  { subject: "physics", year: 2024, question: "A body of mass 5 kg is acted upon by a force of 20 N. Its acceleration is:", option_a: "2 m/s²", option_b: "4 m/s²", option_c: "10 m/s²", option_d: "25 m/s²", correct_answer: "B", explanation: "F = ma → a = F/m = 20/5 = 4 m/s².", topics: ["motion", "forces"] },
  { subject: "physics", year: 2023, question: "The momentum of a 2 kg object moving at 3 m/s is:", option_a: "1.5 kg·m/s", option_b: "5 kg·m/s", option_c: "6 kg·m/s", option_d: "0.67 kg·m/s", correct_answer: "C", explanation: "p = mv = 2 × 3 = 6 kg·m/s.", topics: ["motion"] },
  { subject: "physics", year: 2024, question: "Which of the following energy conversions occurs in a battery?", option_a: "Heat to light", option_b: "Chemical to electrical", option_c: "Mechanical to electrical", option_d: "Solar to chemical", correct_answer: "B", explanation: "Batteries convert stored chemical energy into electrical energy.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2023, question: "The pressure exerted by a 50 N force on an area of 0.5 m² is:", option_a: "25 Pa", option_b: "50 Pa", option_c: "100 Pa", option_d: "200 Pa", correct_answer: "C", explanation: "P = F/A = 50/0.5 = 100 Pa.", topics: ["pressure"] },
  { subject: "physics", year: 2024, question: "An object is placed 30 cm in front of a convex lens of focal length 10 cm. The image distance is:", option_a: "7.5 cm", option_b: "15 cm", option_c: "20 cm", option_d: "30 cm", correct_answer: "B", explanation: "1/f = 1/v + 1/u → 1/10 = 1/v + 1/30 → 1/v = 1/10 − 1/30 = 2/30 → v = 15 cm.", topics: ["optics"] },
  { subject: "physics", year: 2023, question: "The SI unit of electric current is:", option_a: "Volt", option_b: "Ohm", option_c: "Ampere", option_d: "Watt", correct_answer: "C", explanation: "Ampere (A) is the SI unit of electric current.", topics: ["electricity"] },
  { subject: "physics", year: 2024, question: "A resistor of 10 Ω carries a current of 2 A. The potential difference across it is:", option_a: "5 V", option_b: "10 V", option_c: "20 V", option_d: "40 V", correct_answer: "C", explanation: "V = IR = 2 × 10 = 20 V.", topics: ["electricity"] },
  { subject: "physics", year: 2023, question: "The phenomenon where light bends as it passes from one medium to another is called:", option_a: "Reflection", option_b: "Diffraction", option_c: "Refraction", option_d: "Interference", correct_answer: "C", explanation: "Refraction is the bending of light due to change in speed between media.", topics: ["optics"] },
  { subject: "physics", year: 2024, question: "A body weighing 200 N on earth would weigh approximately on the moon (g_moon = g_earth/6):", option_a: "33.3 N", option_b: "1200 N", option_c: "200 N", option_d: "600 N", correct_answer: "A", explanation: "W_moon = 200/6 ≈ 33.3 N.", topics: ["gravitational"] },
  { subject: "physics", year: 2023, question: "Which type of wave is a sound wave?", option_a: "Transverse", option_b: "Longitudinal", option_c: "Electromagnetic", option_d: "Digital", correct_answer: "B", explanation: "Sound waves are longitudinal (compressions and rarefactions).", topics: ["waves"] },
  { subject: "physics", year: 2024, question: "The work done in lifting a 10 kg object through a height of 5 m (g = 10 m/s²) is:", option_a: "50 J", option_b: "100 J", option_c: "250 J", option_d: "500 J", correct_answer: "D", explanation: "W = mgh = 10 × 10 × 5 = 500 J.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2023, question: "Which of the following is NOT a vector quantity?", option_a: "Displacement", option_b: "Velocity", option_c: "Speed", option_d: "Acceleration", correct_answer: "C", explanation: "Speed has magnitude only — it is a scalar.", topics: ["motion"] },
  { subject: "physics", year: 2024, question: "The period of a simple pendulum of length 1 m (g = 10 m/s²) is approximately:", option_a: "1.0 s", option_b: "2.0 s", option_c: "3.14 s", option_d: "0.5 s", correct_answer: "B", explanation: "T = 2π√(L/g) = 2π√(1/10) ≈ 2π × 0.316 ≈ 2.0 s.", topics: ["waves"] },
  { subject: "physics", year: 2023, question: "The efficiency of a machine that does 40 J of useful work from 100 J of input energy is:", option_a: "25%", option_b: "40%", option_c: "60%", option_d: "150%", correct_answer: "B", explanation: "Efficiency = (useful output/input) × 100 = 40/100 × 100 = 40%.", topics: ["simple_machines"] },
  { subject: "physics", year: 2024, question: "Radioactive decay of carbon-14 is used for:", option_a: "Generating electricity", option_b: "Dating ancient artifacts", option_c: "Sterilizing food", option_d: "Treating cancer", correct_answer: "B", explanation: "Carbon-14 dating determines the age of organic materials.", topics: ["nuclear_physics"] },
  { subject: "physics", year: 2023, question: "The phenomenon responsible for the blue colour of the sky is:", option_a: "Reflection", option_b: "Refraction", option_c: "Scattering", option_d: "Dispersion", correct_answer: "C", explanation: "Rayleigh scattering of sunlight by atmospheric molecules.", topics: ["waves"] },
  { subject: "physics", year: 2024, question: "A car accelerates from rest to 20 m/s in 10 s. The distance covered is:", option_a: "50 m", option_b: "100 m", option_c: "200 m", option_d: "400 m", correct_answer: "B", explanation: "s = ½at², a = (20−0)/10 = 2 m/s², s = ½ × 2 × 100 = 100 m.", topics: ["motion"] },
  { subject: "physics", year: 2023, question: "The device used to measure electric current is a:", option_a: "Voltmeter", option_b: "Ammeter", option_c: "Ohmmeter", option_d: "Galvanometer", correct_answer: "B", explanation: "An ammeter measures current and is connected in series.", topics: ["electricity"] },
  { subject: "physics", year: 2024, question: "When a metal rod is heated, it expands. This is an example of:", option_a: "Linear expansion", option_b: "Surface expansion", option_c: "Volume expansion", option_d: "Contraction", correct_answer: "A", explanation: "Heating a rod causes expansion along its length.", topics: ["thermodynamics"] },
  { subject: "physics", year: 2023, question: "The angle of incidence equals the angle of reflection. This law applies to:", option_a: "Refraction", option_b: "Diffraction", option_c: "Regular reflection", option_d: "Diffuse reflection", correct_answer: "C", explanation: "Law of reflection applies to regular (specular) reflection.", topics: ["optics"] },
  { subject: "physics", year: 2024, question: "A body moves in a circle of radius 10 m at a speed of 10 m/s. Its centripetal acceleration is:", option_a: "1 m/s²", option_b: "10 m/s²", option_c: "100 m/s²", option_d: "1000 m/s²", correct_answer: "B", explanation: "a = v²/r = 100/10 = 10 m/s².", topics: ["circular_motion"] },
  { subject: "physics", year: 2023, question: "Which of the following is the correct unit for power?", option_a: "Joule", option_b: "Newton", option_c: "Watt", option_d: "Pascal", correct_answer: "C", explanation: "Watt (W) = Joule/second is the unit of power.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2024, question: "Light travels fastest in:", option_a: "Glass", option_b: "Water", option_c: "Diamond", option_d: "Vacuum", correct_answer: "D", explanation: "Light speed is maximum in vacuum (3 × 10⁸ m/s).", topics: ["optics"] },
  { subject: "physics", year: 2023, question: "An object of mass 4 kg is lifted 3 m above the ground. Its gravitational potential energy (g=10) is:", option_a: "12 J", option_b: "40 J", option_c: "120 J", option_d: "70 J", correct_answer: "C", explanation: "PE = mgh = 4 × 10 × 3 = 120 J.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2024, question: "The phenomenon where waves bend around obstacles is called:", option_a: "Reflection", option_b: "Refraction", option_c: "Diffraction", option_d: "Polarization", correct_answer: "C", explanation: "Diffraction = bending of waves around obstacles or through openings.", topics: ["waves"] },
  { subject: "physics", year: 2023, question: "In a series circuit with three resistors of 2 Ω each, the total resistance is:", option_a: "2/3 Ω", option_b: "3 Ω", option_c: "6 Ω", option_d: "8 Ω", correct_answer: "C", explanation: "R_total = R₁ + R₂ + R₃ = 2 + 2 + 2 = 6 Ω.", topics: ["electricity"] },
  { subject: "physics", year: 2024, question: "The frequency of alternating current in Nigeria is:", option_a: "50 Hz", option_b: "60 Hz", option_c: "100 Hz", option_d: "220 Hz", correct_answer: "A", explanation: "Nigeria uses 50 Hz AC supply.", topics: ["electricity"] },
  { subject: "physics", year: 2023, question: "Which color of light has the longest wavelength?", option_a: "Violet", option_b: "Green", option_c: "Yellow", option_d: "Red", correct_answer: "D", explanation: "Red has the longest wavelength (~700 nm) in the visible spectrum.", topics: ["waves"] },
  { subject: "physics", year: 2024, question: "The kinetic energy of a 1 kg object moving at 4 m/s is:", option_a: "2 J", option_b: "4 J", option_c: "8 J", option_d: "16 J", correct_answer: "C", explanation: "KE = ½mv² = ½ × 1 × 16 = 8 J.", topics: ["work_energy_power"] },
  { subject: "physics", year: 2023, question: "A transformer with 1000 turns on the primary and 100 turns on the secondary is a:", option_a: "Step-up transformer", option_b: "Step-down transformer", option_c: "Auto transformer", option_d: "None of these", correct_answer: "B", explanation: "Fewer secondary turns = voltage steps down.", topics: ["electromagnetism"] },
  { subject: "physics", year: 2024, question: "Newton's third law states that:", option_a: "F = ma", option_b: "Every action has an equal and opposite reaction", option_c: "A body at rest stays at rest", option_d: "Energy is conserved", correct_answer: "B", explanation: "Action-reaction pairs are equal and opposite.", topics: ["motion", "forces"] },

  // ============ CHEMISTRY (30 questions) ============
  { subject: "chemistry", year: 2024, question: "The pH of a solution with [H⁺] = 10⁻³ mol/dm³ is:", option_a: "3", option_b: "7", option_c: "11", option_d: "14", correct_answer: "A", explanation: "pH = −log[H⁺] = −log(10⁻³) = 3.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2023, question: "Which of the following is a strong acid?", option_a: "Ethanoic acid", option_b: "Hydrochloric acid", option_c: "Carbonic acid", option_d: "Citric acid", correct_answer: "B", explanation: "HCl completely ionizes in water — it is a strong acid.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "The electronic configuration of sodium (Z=11) is:", option_a: "2,8,1", option_b: "2,8,2", option_c: "2,2,8,1", option_d: "1,2,8", correct_answer: "A", explanation: "11 electrons fill as 2 in K, 8 in L, 1 in M.", topics: ["atomic_structure"] },
  { subject: "chemistry", year: 2023, question: "Which of the following undergoes substitution reaction?", option_a: "Ethene", option_b: "Ethyne", option_c: "Methane", option_d: "Benzene", correct_answer: "C", explanation: "Alkanes like methane undergo substitution with halogens.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "The number of moles in 36 g of water (H=1, O=16) is:", option_a: "1", option_b: "2", option_c: "3", option_d: "18", correct_answer: "B", explanation: "M(H₂O) = 18 g/mol. n = 36/18 = 2 mol.", topics: ["stoichiometry"] },
  { subject: "chemistry", year: 2023, question: "Which gas is produced when zinc reacts with dilute hydrochloric acid?", option_a: "Oxygen", option_b: "Chlorine", option_c: "Hydrogen", option_d: "Carbon dioxide", correct_answer: "C", explanation: "Zn + 2HCl → ZnCl₂ + H₂.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "In the reaction N₂ + 3H₂ ⇌ 2NH₃, increasing pressure shifts equilibrium to:", option_a: "Left (reactants)", option_b: "Right (products)", option_c: "Nowhere", option_d: "Both equally", correct_answer: "B", explanation: "Fewer moles of gas on the product side (2 vs 4). High pressure favours products.", topics: ["equilibrium"] },
  { subject: "chemistry", year: 2023, question: "The atomic number of an element is 17. It is:", option_a: "Sodium", option_b: "Chlorine", option_c: "Argon", option_d: "Sulphur", correct_answer: "B", explanation: "Z = 17 is chlorine (Cl).", topics: ["atomic_structure"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is an electrolyte?", option_a: "Distilled water", option_b: "Ethanol", option_c: "Sodium chloride solution", option_d: "Kerosene", correct_answer: "C", explanation: "NaCl solution conducts electricity — it is an electrolyte.", topics: ["electrochemistry"] },
  { subject: "chemistry", year: 2023, question: "The IUPAC name of CH₃CH₂OH is:", option_a: "Methanol", option_b: "Ethanol", option_c: "Propanol", option_d: "Ethanoic acid", correct_answer: "B", explanation: "Two carbons with -OH group = ethanol.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "Which process involves the conversion of electrical energy to chemical energy?", option_a: "Galvanic cell", option_b: "Electrolysis", option_c: "Combustion", option_d: "Distillation", correct_answer: "B", explanation: "Electrolysis uses electricity to drive non-spontaneous reactions.", topics: ["electrochemistry"] },
  { subject: "chemistry", year: 2023, question: "Which of the following is a homologous series?", option_a: "Alkanes", option_b: "Metals", option_c: "Noble gases", option_d: "Acids only", correct_answer: "A", explanation: "Alkanes form a homologous series with general formula CₙH₂ₙ₊₂.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "The mass of one mole of CO₂ (C=12, O=16) is:", option_a: "28 g", option_b: "44 g", option_c: "32 g", option_d: "16 g", correct_answer: "B", explanation: "M(CO₂) = 12 + 2(16) = 44 g/mol.", topics: ["stoichiometry"] },
  { subject: "chemistry", year: 2023, question: "The product of incomplete combustion of hydrocarbons is:", option_a: "CO₂ and H₂O", option_b: "CO and H₂O", option_c: "C and H₂", option_d: "CO₂ only", correct_answer: "B", explanation: "Incomplete combustion produces carbon monoxide and water.", topics: ["organic_chemistry"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is a redox reaction?", option_a: "NaCl + AgNO₃", option_b: "Zn + CuSO₄", option_c: "HCl + NaOH", option_d: "CaCO₃ → CaO + CO₂", correct_answer: "B", explanation: "Zn is oxidized (0→+2), Cu²⁺ is reduced (+2→0).", topics: ["redox"] },
  { subject: "chemistry", year: 2023, question: "The solubility of most solid solutes in water increases with:", option_a: "Decrease in temperature", option_b: "Increase in temperature", option_c: "Decrease in pressure", option_d: "Increase in volume", correct_answer: "B", explanation: "Higher temperature generally increases solubility of solids.", topics: ["solutions"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is an acid salt?", option_a: "NaCl", option_b: "NaHCO₃", option_c: "Na₂SO₄", option_d: "KNO₃", correct_answer: "B", explanation: "NaHCO₃ (sodium hydrogen carbonate) contains a replaceable H.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2023, question: "The volume of gas at STP occupied by 2 moles is:", option_a: "11.2 dm³", option_b: "22.4 dm³", option_c: "44.8 dm³", option_d: "2.24 dm³", correct_answer: "C", explanation: "At STP, 1 mol = 22.4 dm³. 2 mol = 44.8 dm³.", topics: ["gas_laws"] },
  { subject: "chemistry", year: 2024, question: "Which element has the electronic configuration 2,8,7?", option_a: "Sodium", option_b: "Chlorine", option_c: "Argon", option_d: "Calcium", correct_answer: "B", explanation: "17 electrons: 2,8,7 = Chlorine.", topics: ["atomic_structure"] },
  { subject: "chemistry", year: 2023, question: "Which of the following is a base?", option_a: "HCl", option_b: "NaOH", option_c: "H₂SO₄", option_d: "CH₃COOH", correct_answer: "B", explanation: "NaOH is sodium hydroxide — a strong base.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "The empirical formula of butane (C₄H₁₀) is:", option_a: "CH₂", option_b: "C₂H₅", option_c: "C₄H₁₀", option_d: "CH₃", correct_answer: "B", explanation: "C₄H₁₀ → divide by 2 → C₂H₅.", topics: ["stoichiometry"] },
  { subject: "chemistry", year: 2023, question: "Electrolysis of molten NaCl produces:", option_a: "Na and O₂", option_b: "Na and Cl₂", option_c: "H₂ and Cl₂", option_d: "NaOH and Cl₂", correct_answer: "B", explanation: "Molten NaCl: Na⁺ → Na at cathode, Cl⁻ → Cl₂ at anode.", topics: ["electrochemistry"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is NOT a property of ionic compounds?", option_a: "High melting point", option_b: "Conduct electricity when molten", option_c: "Are soluble in organic solvents", option_d: "Form crystal lattices", correct_answer: "C", explanation: "Ionic compounds are generally insoluble in organic solvents.", topics: ["chemical_bonding"] },
  { subject: "chemistry", year: 2023, question: "The reaction rate increases with increase in:", option_a: "Volume", option_b: "Temperature", option_c: "Concentration of products", option_d: "Container size", correct_answer: "B", explanation: "Higher temperature → more kinetic energy → more successful collisions.", topics: ["chemical_kinetics"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is a characteristic of transition metals?", option_a: "Always form colourless compounds", option_b: "Low melting points", option_c: "Variable oxidation states", option_d: "Poor conductors of heat", correct_answer: "C", explanation: "Transition metals exhibit multiple oxidation states.", topics: ["periodic_table"] },
  { subject: "chemistry", year: 2023, question: "The gas produced when copper reacts with concentrated nitric acid is:", option_a: "Hydrogen", option_b: "Oxygen", option_c: "Nitrogen dioxide", option_d: "Nitrogen", correct_answer: "C", explanation: "Cu + 4HNO₃ → Cu(NO₃)₂ + 2NO₂ + 2H₂O.", topics: ["acid_base"] },
  { subject: "chemistry", year: 2024, question: "Which of the following is used as a catalyst in the Haber process?", option_a: "Vanadium pentoxide", option_b: "Iron", option_c: "Platinum", option_d: "Manganese dioxide", correct_answer: "B", explanation: "Iron (with promoters) catalyzes N₂ + 3H₂ → 2NH₃.", topics: ["equilibrium", "chemical_kinetics"] },
  { subject: "chemistry", year: 2023, question: "The oxidation state of sulphur in H₂SO₄ is:", option_a: "+2", option_b: "+4", option_c: "+6", option_d: "−2", correct_answer: "C", explanation: "2(+1) + S + 4(−2) = 0 → S = +6.", topics: ["redox"] },
  { subject: "chemistry", year: 2024, question: "An isotope of an element has:", option_a: "Different number of electrons", option_b: "Different number of neutrons", option_c: "Different number of protons", option_d: "Different chemical properties", correct_answer: "B", explanation: "Isotopes have same Z but different A (different neutrons).", topics: ["atomic_structure"] },

  // ============ BIOLOGY (30 questions) ============
  { subject: "biology", year: 2024, question: "The site of protein synthesis in a cell is the:", option_a: "Nucleus", option_b: "Ribosome", option_c: "Mitochondria", option_d: "Golgi apparatus", correct_answer: "B", explanation: "Ribosomes are the sites of protein synthesis.", topics: ["cell_biology"] },
  { subject: "biology", year: 2023, question: "Which blood group is the universal donor?", option_a: "A", option_b: "B", option_c: "AB", option_d: "O", correct_answer: "D", explanation: "Blood group O has no A or B antigens — safe for all recipients.", topics: ["circulatory_system"] },
  { subject: "biology", year: 2024, question: "Photosynthesis occurs in the:", option_a: "Mitochondria", option_b: "Chloroplast", option_c: "Ribosome", option_d: "Nucleus", correct_answer: "B", explanation: "Chloroplasts contain chlorophyll for photosynthesis.", topics: ["plant_biology"] },
  { subject: "biology", year: 2023, question: "Which hormone regulates blood sugar level?", option_a: "Thyroxine", option_b: "Adrenaline", option_c: "Insulin", option_d: "Growth hormone", correct_answer: "C", explanation: "Insulin lowers blood glucose by promoting cellular uptake.", topics: ["homeostasis"] },
  { subject: "biology", year: 2024, question: "The structure that carries impulse from one neuron to another is the:", option_a: "Axon", option_b: "Dendrite", option_c: "Synapse", option_d: "Cell body", correct_answer: "C", explanation: "The synapse is the gap where neurotransmitters cross.", topics: ["nervous_system"] },
  { subject: "biology", year: 2023, question: "Which of these is a function of the white blood cell?", option_a: "Transport oxygen", option_b: "Fight infection", option_c: "Carry nutrients", option_d: "Clot blood", correct_answer: "B", explanation: "WBCs are part of the immune system — they fight pathogens.", topics: ["immunity"] },
  { subject: "biology", year: 2024, question: "The gene responsible for sickle cell anaemia is located on:", option_a: "X chromosome", option_b: "Y chromosome", option_c: "Autosome", option_d: "Mitochondrial DNA", correct_answer: "C", explanation: "Sickle cell is autosomal recessive (chromosome 11).", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "Which of the following is NOT a component of the mammalian heart?", option_a: "Tricuspid valve", option_b: "Bicuspid valve", option_c: "Semi-lunar valve", option_d: "Hepatic valve", correct_answer: "D", explanation: "There is no 'hepatic valve' in the heart.", topics: ["circulatory_system"] },
  { subject: "biology", year: 2024, question: "In a cross between Tt and Tt, the expected phenotypic ratio is:", option_a: "1:1", option_b: "1:2:1", option_c: "3:1", option_d: "9:3:3:1", correct_answer: "C", explanation: "3 dominant (TT + Tt) : 1 recessive (tt) = 3:1.", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "The primary function of the large intestine is:", option_a: "Digest proteins", option_b: "Absorb water", option_c: "Absorb glucose", option_d: "Secrete bile", correct_answer: "B", explanation: "The large intestine absorbs water and electrolytes from undigested food.", topics: ["digestive_system"] },
  { subject: "biology", year: 2024, question: "Which of the following organisms is a producer?", option_a: "Lion", option_b: "Grass", option_c: "Mushroom", option_d: "Eagle", correct_answer: "B", explanation: "Grass is a producer — it makes its own food via photosynthesis.", topics: ["ecology"] },
  { subject: "biology", year: 2023, question: "The process by which water moves from a region of high concentration to low through a semipermeable membrane is:", option_a: "Diffusion", option_b: "Osmosis", option_c: "Active transport", option_d: "Facilitated diffusion", correct_answer: "B", explanation: "Osmosis is specifically the movement of water across a semipermeable membrane.", topics: ["cell_biology"] },
  { subject: "biology", year: 2024, question: "The human egg cell contains how many chromosomes?", option_a: "23", option_b: "44", option_c: "46", option_d: "48", correct_answer: "A", explanation: "Human gametes are haploid (23 chromosomes).", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "Bile is produced by the:", option_a: "Pancreas", option_b: "Stomach", option_c: "Liver", option_d: "Small intestine", correct_answer: "C", explanation: "The liver produces bile, which is stored in the gall bladder.", topics: ["digestive_system"] },
  { subject: "biology", year: 2024, question: "The process of converting glucose into ethanol in the absence of oxygen is called:", option_a: "Aerobic respiration", option_b: "Fermentation", option_c: "Photosynthesis", option_d: "Decomposition", correct_answer: "B", explanation: "Fermentation is anaerobic respiration producing ethanol + CO₂.", topics: ["respiration"] },
  { subject: "biology", year: 2023, question: "Which of the following is an example of mutualism?", option_a: "Tapeworm in human intestine", option_b: "Lion eating a zebra", option_c: "Bee and flower", option_d: "Mistletoe on a tree", correct_answer: "C", explanation: "Bees get nectar, flowers get pollinated — both benefit.", topics: ["ecology"] },
  { subject: "biology", year: 2024, question: "DNA replication occurs during which phase of cell division?", option_a: "Prophase", option_b: "Metaphase", option_c: "S phase of interphase", option_d: "Telophase", correct_answer: "C", explanation: "DNA replicates during the S (synthesis) phase of interphase.", topics: ["cell_biology"] },
  { subject: "biology", year: 2023, question: "Which organ filters blood and produces urine?", option_a: "Liver", option_b: "Kidney", option_c: "Spleen", option_d: "Lung", correct_answer: "B", explanation: "The kidneys filter blood in nephrons to produce urine.", topics: ["excretion"] },
  { subject: "biology", year: 2024, question: "The term 'phenotype' refers to:", option_a: "Genetic makeup", option_b: "Physical appearance", option_c: "Chromosome number", option_d: "DNA sequence", correct_answer: "B", explanation: "Phenotype = observable traits (vs genotype = genetic makeup).", topics: ["genetics"] },
  { subject: "biology", year: 2023, question: "The function of chlorophyll in photosynthesis is to:", option_a: "Release oxygen", option_b: "Absorb light energy", option_c: "Fix carbon dioxide", option_d: "Produce glucose", correct_answer: "B", explanation: "Chlorophyll absorbs light energy for the light-dependent reactions.", topics: ["plant_biology"] },
  { subject: "biology", year: 2024, question: "Which of the following is a characteristic of viruses?", option_a: "They have cells", option_b: "They reproduce independently", option_c: "They have DNA or RNA", option_d: "They have ribosomes", correct_answer: "C", explanation: "Viruses have genetic material (DNA or RNA) but no cellular structure.", topics: ["classification"] },
  { subject: "biology", year: 2023, question: "The part of the brain that controls balance and coordination is the:", option_a: "Cerebrum", option_b: "Cerebellum", option_c: "Medulla oblongata", option_d: "Hypothalamus", correct_answer: "B", explanation: "The cerebellum coordinates voluntary movements and balance.", topics: ["nervous_system"] },
  { subject: "biology", year: 2024, question: "Which gas is taken in during inhalation and used in respiration?", option_a: "Carbon dioxide", option_b: "Nitrogen", option_c: "Oxygen", option_d: "Hydrogen", correct_answer: "C", explanation: "Oxygen is used in aerobic respiration to break down glucose.", topics: ["respiration"] },
  { subject: "biology", year: 2023, question: "The process by which neutrophils engulf bacteria is called:", option_a: "Antibody production", option_b: "Phagocytosis", option_c: "Opsonization", option_d: "Agglutination", correct_answer: "B", explanation: "Phagocytosis = engulfing and digesting pathogens.", topics: ["immunity"] },
  { subject: "biology", year: 2024, question: "Which of the following is NOT a sexually transmitted infection?", option_a: "Gonorrhoea", option_b: "Syphilis", option_c: "Malaria", option_d: "HIV/AIDS", correct_answer: "C", explanation: "Malaria is transmitted by Anopheles mosquitoes, not sexually.", topics: ["immunity"] },
  { subject: "biology", year: 2023, question: "The main function of the xylem tissue in plants is to:", option_a: "Transport food", option_b: "Transport water and minerals", option_c: "Store food", option_d: "Provide flexibility", correct_answer: "B", explanation: "Xylem transports water and dissolved minerals from roots to leaves.", topics: ["plant_biology"] },
  { subject: "biology", year: 2024, question: "A population is defined as:", option_a: "All organisms in an area", option_b: "All species in an area", option_c: "All individuals of one species in an area", option_d: "All communities in an area", correct_answer: "C", explanation: "Population = all individuals of ONE species in a given area.", topics: ["ecology"] },
  { subject: "biology", year: 2023, question: "Which blood vessels carry blood AWAY from the heart?", option_a: "Veins", option_b: "Capillaries", option_c: "Venules", option_d: "Arteries", correct_answer: "D", explanation: "Arteries carry blood away from the heart (usually oxygenated).", topics: ["circulatory_system"] },
  { subject: "biology", year: 2024, question: "The deficiency of vitamin C causes:", option_a: "Rickets", option_b: "Scurvy", option_c: "Beriberi", option_d: "Pellagra", correct_answer: "B", explanation: "Scurvy is caused by vitamin C deficiency (bleeding gums, weakness).", topics: ["nutrition"] },
  { subject: "biology", year: 2023, question: "In which part of the alimentary canal does most chemical digestion occur?", option_a: "Stomach", option_b: "Mouth", option_c: "Duodenum", option_d: "Oesophagus", correct_answer: "C", explanation: "The duodenum receives bile and pancreatic juice for complete digestion.", topics: ["digestive_system"] },

  // ============ ENGLISH (20 questions) ============
  { subject: "english", year: 2024, question: "Choose the option that best completes: 'She ___ to school every day.'", option_a: "go", option_b: "goes", option_c: "going", option_d: "gone", correct_answer: "B", explanation: "Third person singular present tense requires 'goes'.", topics: ["sentence_completion"] },
  { subject: "english", year: 2023, question: "The synonym of 'eloquent' is:", option_a: "Silent", option_b: "Fluent", option_c: "Rude", option_d: "Slow", correct_answer: "B", explanation: "Eloquent = fluent or persuasive in speaking or writing.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Choose the correctly spelt word:", option_a: "Occurence", option_b: "Occurrence", option_c: "Ocurrence", option_d: "Occurrance", correct_answer: "B", explanation: "Occurrence — double r, single c.", topics: ["spelling"] },
  { subject: "english", year: 2023, question: "Identify the figure of speech: 'The wind whispered through the trees.'", option_a: "Simile", option_b: "Metaphor", option_c: "Personification", option_d: "Hyperbole", correct_answer: "C", explanation: "Giving human quality (whisper) to non-human (wind) = personification.", topics: ["figures_of_speech"] },
  { subject: "english", year: 2024, question: "'Neither the students nor the teacher ___ present.' Choose the correct verb:", option_a: "were", option_b: "are", option_c: "was", option_d: "have been", correct_answer: "C", explanation: "With 'neither...nor', the verb agrees with the nearer subject (teacher = singular).", topics: ["sentence_completion"] },
  { subject: "english", year: 2023, question: "The antonym of 'benevolent' is:", option_a: "Kind", option_b: "Generous", option_c: "Malevolent", option_d: "Gentle", correct_answer: "C", explanation: "Benevolent = kind; malevolent = evil/wishing harm.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Choose the correct option: 'I would have helped if I ___ known.'", option_a: "have", option_b: "had", option_c: "was", option_d: "did", correct_answer: "B", explanation: "Third conditional: 'if I had known' (past perfect).", topics: ["tenses"] },
  { subject: "english", year: 2023, question: "The word 'administer' has stress on which syllable?", option_a: "First", option_b: "Second", option_c: "Third", option_d: "Fourth", correct_answer: "B", explanation: "ad-MIN-ister — stress is on the second syllable.", topics: ["stress"] },
  { subject: "english", year: 2024, question: "Choose the option with the correct punctuation:", option_a: "Stop! he shouted.", option_b: "\"Stop!\" he shouted.", option_c: "\"Stop!\" He shouted.", option_d: "Stop, he shouted.", correct_answer: "B", explanation: "Direct speech: \"Stop!\" he shouted. (Exclamation in quotes, lowercase after.)", topics: ["punctuation"] },
  { subject: "english", year: 2023, question: "The passive voice of 'The police caught the thief' is:", option_a: "The thief was caught by the police.", option_b: "The thief is caught by the police.", option_c: "The thief has been caught by the police.", option_d: "The police was caught by the thief.", correct_answer: "A", explanation: "Simple past passive: object + was/were + past participle + by + agent.", topics: ["voice"] },
  { subject: "english", year: 2044, question: "Choose the correct option: 'Every student ___ a textbook.'", option_a: "have", option_b: "has", option_c: "having", option_d: "having had", correct_answer: "B", explanation: "'Every' takes a singular verb — 'has'.", topics: ["agreement"] },
  { subject: "english", year: 2023, question: "The word 'ubiquitous' means:", option_a: "Rare", option_b: "Present everywhere", option_c: "Unique", option_d: "Useful", correct_answer: "B", explanation: "Ubiquitous = found everywhere.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Which sentence is grammatically correct?", option_a: "Him and me went to the market.", option_b: "He and I went to the market.", option_c: "He and me went to the market.", option_d: "Him and I went to the market.", correct_answer: "B", explanation: "Subject pronouns: 'He and I' (not 'him' or 'me' as subjects).", topics: ["pronouns"] },
  { subject: "english", year: 2023, question: "The plural of 'mouse' is:", option_a: "Mouses", option_b: "Mice", option_c: "Mices", option_d: "Mousies", correct_answer: "B", explanation: "Mouse → mice (irregular plural).", topics: ["plurals"] },
  { subject: "english", year: 2024, question: "Choose the correct option: 'If I ___ rich, I would travel the world.'", option_a: "am", option_b: "was", option_c: "were", option_d: "be", correct_answer: "C", explanation: "Second conditional uses 'were' for all subjects (subjunctive mood).", topics: ["tenses"] },
  { subject: "english", year: 2023, question: "The word 'ephemeral' means:", option_a: "Eternal", option_b: "Short-lived", option_c: "Enormous", option_d: "Essential", correct_answer: "B", explanation: "Ephemeral = lasting for a very short time.", topics: ["synonyms"] },
  { subject: "english", year: 2024, question: "Choose the option with the correct indirect speech: He said, 'I am tired.'", option_a: "He said that he is tired.", option_b: "He said that he was tired.", option_c: "He said that I am tired.", option_d: "He said I was tired.", correct_answer: "B", explanation: "Direct → indirect: 'am' becomes 'was' (backshift).", topics: ["reported_speech"] },
  { subject: "english", year: 2023, question: "Which word is an adverb in: 'She sang beautifully'?", option_a: "She", option_b: "Sang", option_c: "Beautifully", option_d: "None", correct_answer: "C", explanation: "'Beautifully' modifies the verb 'sang' — it is an adverb.", topics: ["parts_of_speech"] },
  { subject: "english", year: 2024, question: "The idiom 'to burn the midnight oil' means:", option_a: "To waste resources", option_b: "To work late at night", option_c: "To start a fire", option_d: "To be angry", correct_answer: "B", explanation: "The idiom means to work or study late into the night.", topics: ["idioms"] },
  { subject: "english", year: 2023, question: "Choose the correct option: 'The book is ___ the table.'", option_a: "in", option_b: "at", option_c: "on", option_d: "by", correct_answer: "C", explanation: "Books rest ON surfaces.", topics: ["prepositions"] },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const results = { inserted: 0, errors: 0, errorMessages: [] as string[] };

    for (const q of QUESTIONS) {
      const { error } = await supabase
        .from("jamb_questions")
        .insert({
          subject: q.subject,
          year: q.year,
          question: q.question,
          option_a: q.option_a,
          option_b: q.option_b,
          option_c: q.option_c,
          option_d: q.option_d,
          correct_answer: q.correct_answer,
          explanation: q.explanation,
          topics: q.topics || [],
        });

      if (error) {
        results.errors++;
        results.errorMessages.push(`${q.subject}: ${error.message}`);
      } else {
        results.inserted++;
      }
    }

    return new Response(
      JSON.stringify({ success: true, ...results }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
